// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_tenant.sql

package sqlcgen

import (
	"context"
)

const adminCompanyList = `-- name: AdminCompanyList :many

select id, name, address, total_area_m2, personnel_count, contact_name, contact_phone, sector, created_at, updated_at, deleted_at from companies
where ($1::boolean or deleted_at is null)
  and ($2::text = '' or name ilike '%' || $2::text || '%')
  and ($3::text is null or sector = $3)
order by lower(name)
limit $5 offset $4
`

type AdminCompanyListParams struct {
	IncludeDeleted bool
	NameContains   string
	Sector         *string
	PageOffset     int32
	PageLimit      int32
}

// AdminTenantRepository queries: the platform operator's view across tenants.
func (q *Queries) AdminCompanyList(ctx context.Context, arg AdminCompanyListParams) ([]Company, error) {
	rows, err := q.db.Query(ctx, adminCompanyList,
		arg.IncludeDeleted,
		arg.NameContains,
		arg.Sector,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.TotalAreaM2,
			&i.PersonnelCount,
			&i.ContactName,
			&i.ContactPhone,
			&i.Sector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
