// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_marketdata.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminMarketDataUpsertHourlyPrices = `-- name: AdminMarketDataUpsertHourlyPrices :execrows

insert into market_prices_hourly (ts, ptf, fetched_at)
select unnest($1::timestamptz[]),
       unnest($2::numeric[]),
       unnest($3::timestamptz[])
on conflict (ts) do update set
    ptf = excluded.ptf,
    fetched_at = excluded.fetched_at
`

type AdminMarketDataUpsertHourlyPricesParams struct {
	Ts        []pgtype.Timestamptz
	Ptf       []pgtype.Numeric
	FetchedAt []pgtype.Timestamptz
}

// AdminMarketDataRepository's queries (store.AdminMarketDataRepository,
// implemented in internal/store/postgres/admin/marketdata.go). Neither table
// carries a company_id: these writes are platform-wide by construction, so
// there is no Scope to check here — see repository.go's admin section header.
// NOTE: TestEveryFunctionSQLcMustTypeIsDeclared currently flags
// "market_prices_hourly (" and "conflict (" below as calls to undeclared
// functions — a known false positive being fixed in parallel on
// f1/task-8c; see the task report.
func (q *Queries) AdminMarketDataUpsertHourlyPrices(ctx context.Context, arg AdminMarketDataUpsertHourlyPricesParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminMarketDataUpsertHourlyPrices, arg.Ts, arg.Ptf, arg.FetchedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminMarketDataUpsertYekdem = `-- name: AdminMarketDataUpsertYekdem :execrows
insert into yekdem_monthly (year, month, value, fetched_at)
select unnest($1::smallint[]),
       unnest($2::smallint[]),
       unnest($3::numeric[]),
       unnest($4::timestamptz[])
on conflict (year, month) do update set
    value = excluded.value,
    fetched_at = excluded.fetched_at
`

type AdminMarketDataUpsertYekdemParams struct {
	Year      []int16
	Month     []int16
	Value     []pgtype.Numeric
	FetchedAt []pgtype.Timestamptz
}

func (q *Queries) AdminMarketDataUpsertYekdem(ctx context.Context, arg AdminMarketDataUpsertYekdemParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminMarketDataUpsertYekdem,
		arg.Year,
		arg.Month,
		arg.Value,
		arg.FetchedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
