// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_audit.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminAppendPlatformAudit = `-- name: AdminAppendPlatformAudit :one

insert into audit_log (company_id, user_id, action, entity_type, entity_id, before, after, ip, created_at)
values (null, $1, $2, $3, $4,
        $5, $6, $7, coalesce($8::timestamptz, now()))
returning id, company_id, user_id, action, entity_type, entity_id, before, after, ip, created_at
`

type AdminAppendPlatformAuditParams struct {
	UserID     *uuid.UUID
	Action     string
	EntityType string
	EntityID   *uuid.UUID
	Before     []byte
	After      []byte
	Ip         *netip.Addr
	At         pgtype.Timestamptz
}

// AdminAuditRepository queries (internal/store/postgres/admin).
// company_id is always written as NULL here: a platform action belongs to
// no tenant. The caller (internal/store/postgres/admin) refuses any entry
// whose CompanyID is non-nil before this query ever runs.
//
// coalesce(sqlc.narg(at)::timestamptz, now()): a caller that leaves CreatedAt at its zero
// value gets the database's own now() rather than writing 0001-01-01.
func (q *Queries) AdminAppendPlatformAudit(ctx context.Context, arg AdminAppendPlatformAuditParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, adminAppendPlatformAudit,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Before,
		arg.After,
		arg.Ip,
		arg.At,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Before,
		&i.After,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}
