// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_billing.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const adminBillableBuildings = `-- name: AdminBillableBuildings :many

select b.company_id, b.id as building_id, b.bill_cutoff_day
from buildings b
join companies c on c.id = b.company_id
where b.deleted_at is null and c.deleted_at is null
  and exists (select 1 from analyzers a where a.building_id = b.id and a.deleted_at is null)
order by b.company_id, b.id
`

type AdminBillableBuildingsRow struct {
	CompanyID     uuid.UUID
	BuildingID    uuid.UUID
	BillCutoffDay int16
}

// AdminBillingRepository queries: platform-wide discovery for the billing
// dispatcher, called only from internal/store/postgres/admin/billing.go.
func (q *Queries) AdminBillableBuildings(ctx context.Context) ([]AdminBillableBuildingsRow, error) {
	rows, err := q.db.Query(ctx, adminBillableBuildings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminBillableBuildingsRow
	for rows.Next() {
		var i AdminBillableBuildingsRow
		if err := rows.Scan(&i.CompanyID, &i.BuildingID, &i.BillCutoffDay); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
