// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_journal.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminAppendPlatformMessage = `-- name: AdminAppendPlatformMessage :one
insert into operational_messages
    (company_id, kind, category, status, message, detail, related_type, related_id, metadata)
values (
    null, $1, $2, $3, $4,
    $5::text, $6::text, $7::uuid,
    $8::jsonb
)
returning id, company_id, kind, category, status, message, detail, related_type, related_id, metadata, created_at
`

type AdminAppendPlatformMessageParams struct {
	Kind        string
	Category    string
	Status      string
	Message     string
	Detail      *string
	RelatedType *string
	RelatedID   *uuid.UUID
	Metadata    []byte
}

func (q *Queries) AdminAppendPlatformMessage(ctx context.Context, arg AdminAppendPlatformMessageParams) (OperationalMessage, error) {
	row := q.db.QueryRow(ctx, adminAppendPlatformMessage,
		arg.Kind,
		arg.Category,
		arg.Status,
		arg.Message,
		arg.Detail,
		arg.RelatedType,
		arg.RelatedID,
		arg.Metadata,
	)
	var i OperationalMessage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Kind,
		&i.Category,
		&i.Status,
		&i.Message,
		&i.Detail,
		&i.RelatedType,
		&i.RelatedID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const adminFinishPlatformRun = `-- name: AdminFinishPlatformRun :one
update job_runs set
    finished_at = $1::timestamptz,
    status = $2,
    processed = $3::int,
    skipped = $4::int,
    failed = $5::int,
    error = $6::text,
    detail = $7::jsonb
where id = $8::uuid and company_id is null
returning id, company_id, job_type, scope, started_at, finished_at, status, processed, skipped, failed, error, detail, task_id
`

type AdminFinishPlatformRunParams struct {
	At        pgtype.Timestamptz
	Status    string
	Processed int32
	Skipped   int32
	Failed    int32
	ErrorText *string
	Detail    []byte
	ID        uuid.UUID
}

func (q *Queries) AdminFinishPlatformRun(ctx context.Context, arg AdminFinishPlatformRunParams) (JobRun, error) {
	row := q.db.QueryRow(ctx, adminFinishPlatformRun,
		arg.At,
		arg.Status,
		arg.Processed,
		arg.Skipped,
		arg.Failed,
		arg.ErrorText,
		arg.Detail,
		arg.ID,
	)
	var i JobRun
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.JobType,
		&i.Scope,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Processed,
		&i.Skipped,
		&i.Failed,
		&i.Error,
		&i.Detail,
		&i.TaskID,
	)
	return i, err
}

const adminStartPlatformRun = `-- name: AdminStartPlatformRun :one

insert into job_runs (id, company_id, job_type, scope, status)
values (
    coalesce(nullif($1::uuid, '00000000-0000-0000-0000-000000000000'::uuid),
             gen_random_uuid()),
    null, $2, $3::jsonb, $4
)
returning id, company_id, job_type, scope, started_at, finished_at, status, processed, skipped, failed, error, detail, task_id
`

type AdminStartPlatformRunParams struct {
	ID      uuid.UUID
	JobType string
	Scope   []byte
	Status  string
}

// AdminJournalRepository queries (store.AdminJournalRepository). Owned by
// Task 11b, called only from internal/store/postgres/admin/journal.go.
//
// job_runs.company_id and operational_messages.company_id are nullable
// precisely so a platform-wide job — run for no tenant — has somewhere to
// write. Every statement here writes or touches company_id IS NULL rows
// only, so a tenant's run or message (company_id set) is never reachable
// from this, the unscoped, surface.
func (q *Queries) AdminStartPlatformRun(ctx context.Context, arg AdminStartPlatformRunParams) (JobRun, error) {
	row := q.db.QueryRow(ctx, adminStartPlatformRun,
		arg.ID,
		arg.JobType,
		arg.Scope,
		arg.Status,
	)
	var i JobRun
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.JobType,
		&i.Scope,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Processed,
		&i.Skipped,
		&i.Failed,
		&i.Error,
		&i.Detail,
		&i.TaskID,
	)
	return i, err
}
