// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_auth.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminSessionByRefreshTokenHash = `-- name: AdminSessionByRefreshTokenHash :one
select
    s.id, s.user_id, s.refresh_token_hash, s.device_fingerprint, s.user_agent, s.ip,
    s.expires_at, s.revoked_at, s.created_at as session_created_at,
    u.company_id, u.name, u.email, u.phone, u.password_hash, u.password_changed_at,
    u.role, u.is_active, u.last_login_at, u.created_at as user_created_at,
    u.updated_at, u.deleted_at
from sessions s
join users u on u.id = s.user_id
join companies c on c.id = u.company_id
where s.refresh_token_hash = $1 and u.deleted_at is null and c.deleted_at is null
`

type AdminSessionByRefreshTokenHashRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	RefreshTokenHash  string
	DeviceFingerprint *string
	UserAgent         *string
	Ip                *netip.Addr
	ExpiresAt         pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	SessionCreatedAt  pgtype.Timestamptz
	CompanyID         uuid.UUID
	Name              string
	Email             string
	Phone             *string
	PasswordHash      string
	PasswordChangedAt pgtype.Timestamptz
	Role              UserRole
	IsActive          bool
	LastLoginAt       pgtype.Timestamptz
	UserCreatedAt     pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

// Revoked and expired sessions ARE returned — rejecting them is the caller's
// job (see store.SessionRepository.Revoke's doc). Only a soft-deleted user or
// a soft-deleted company excludes the row, because a session naming either
// one has nothing for the caller to act on.
func (q *Queries) AdminSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (AdminSessionByRefreshTokenHashRow, error) {
	row := q.db.QueryRow(ctx, adminSessionByRefreshTokenHash, refreshTokenHash)
	var i AdminSessionByRefreshTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceFingerprint,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.SessionCreatedAt,
		&i.CompanyID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.UserCreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const adminUserByEmail = `-- name: AdminUserByEmail :one

select u.id, u.company_id, u.name, u.email, u.phone, u.password_hash, u.password_changed_at, u.role, u.is_active, u.last_login_at, u.created_at, u.updated_at, u.deleted_at from users u
join companies c on c.id = u.company_id
where u.email = $1 and u.deleted_at is null and c.deleted_at is null
`

// AdminAuthRepository queries (internal/store/postgres/admin). These are the
// ONLY unscoped reads in the schema: a login and a refresh both carry a
// credential and no tenant, so there is no Scope to filter by.
// users.email is citext, so the match is case-insensitive. A soft-deleted
// user, or a user whose company is soft-deleted, is excluded here rather
// than left for the caller to notice.
func (q *Queries) AdminUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, adminUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
