// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_catalogue.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminDeleteFactorConversions = `-- name: AdminDeleteFactorConversions :exec
delete from emission_factor_conversions where factor_id = $1
`

func (q *Queries) AdminDeleteFactorConversions(ctx context.Context, factorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, adminDeleteFactorConversions, factorID)
	return err
}

const adminInsertFactorConversions = `-- name: AdminInsertFactorConversions :exec
insert into emission_factor_conversions (factor_id, unit, multiplier, label)
select $1, elem->>'unit', (elem->>'multiplier')::numeric, elem->>'label'
from jsonb_array_elements($2::jsonb) as elem
`

type AdminInsertFactorConversionsParams struct {
	FactorID    uuid.UUID
	Conversions []byte
}

func (q *Queries) AdminInsertFactorConversions(ctx context.Context, arg AdminInsertFactorConversionsParams) error {
	_, err := q.db.Exec(ctx, adminInsertFactorConversions, arg.FactorID, arg.Conversions)
	return err
}

const adminPlatformFactorOwnerForShare = `-- name: AdminPlatformFactorOwnerForShare :one
select id from emission_factors where id = $1 and company_id is null for share
`

// AdminPlatformFactorOwnerForShare locks the factor row inside
// ReplacePlatformConversions' transaction and reports whether it is a
// PLATFORM factor (company_id is null). A company-owned factor's id, or one
// that does not exist, yields no row: the repository returns ErrNotFound and
// replaces nothing.
func (q *Queries) AdminPlatformFactorOwnerForShare(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, adminPlatformFactorOwnerForShare, id)
	err := row.Scan(&id)
	return id, err
}

const adminUpsertIntegrationDefinitions = `-- name: AdminUpsertIntegrationDefinitions :execrows
insert into integration_definitions (id, provider, subtype, endpoints)
select coalesce(nullif((elem->>'id')::uuid, '00000000-0000-0000-0000-000000000000'::uuid), gen_random_uuid()),
       (elem->>'provider')::integration_provider, elem->>'subtype', elem->'endpoints'
from jsonb_array_elements($1::jsonb) as elem
on conflict (provider, subtype) do update set
    endpoints = excluded.endpoints,
    updated_at = now()
`

// One jsonb array parameter, unpacked with jsonb_array_elements: see
// carbon.sql's CarbonInsertConversions for why (no multi-array unnest in
// sqlc's catalogue, and jsonb_to_recordset's column-list alias trips
// TestEveryFunctionSQLcMustTypeIsDeclared's relation/call scan).
func (q *Queries) AdminUpsertIntegrationDefinitions(ctx context.Context, defs []byte) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpsertIntegrationDefinitions, defs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpsertNationalTariffSchedule = `-- name: AdminUpsertNationalTariffSchedule :execrows

insert into national_tariff_schedule
    (id, effective_from, user_group, voltage_level, term, energy_price, t1_price, t2_price,
     t3_price, distribution_price, power_price, overuse_price, daily_threshold_kwh, vat_rate, source)
select
    coalesce(nullif((elem->>'id')::uuid, '00000000-0000-0000-0000-000000000000'::uuid), gen_random_uuid()),
    (elem->>'effective_from')::date,
    (elem->>'user_group')::distribution_user_group,
    (elem->>'voltage_level')::voltage_level,
    (elem->>'term')::tariff_term,
    (elem->>'energy_price')::numeric,
    (elem->>'t1_price')::numeric,
    (elem->>'t2_price')::numeric,
    (elem->>'t3_price')::numeric,
    (elem->>'distribution_price')::numeric,
    (elem->>'power_price')::numeric,
    (elem->>'overuse_price')::numeric,
    (elem->>'daily_threshold_kwh')::numeric,
    (elem->>'vat_rate')::numeric,
    elem->>'source'
from jsonb_array_elements($1::jsonb) as elem
on conflict (effective_from, user_group, voltage_level, term) do update set
    energy_price = excluded.energy_price,
    t1_price = excluded.t1_price,
    t2_price = excluded.t2_price,
    t3_price = excluded.t3_price,
    distribution_price = excluded.distribution_price,
    power_price = excluded.power_price,
    overuse_price = excluded.overuse_price,
    daily_threshold_kwh = excluded.daily_threshold_kwh,
    vat_rate = excluded.vat_rate,
    source = excluded.source
`

// AdminCatalogueRepository queries (store.AdminCatalogueRepository). Owned by
// Task 11b, called only from internal/store/postgres/admin/catalogue.go.
//
// Every write here is platform-wide and unscoped by design (see
// repository.go's AdminCatalogueRepository doc). national_tariff_schedule and
// integration_definitions have no company_id at all, so nothing to guard;
// emission_factors and emission_factor_conversions hold both platform and
// company-owned rows, so these two queries are careful to touch ONLY a
// platform row (company_id null), in one atomic statement, never a
// company-owned one — see the doc comments below.
// One jsonb array parameter, unpacked with jsonb_array_elements: see
// carbon.sql's CarbonInsertConversions for why (no multi-array unnest in
// sqlc's catalogue, and jsonb_to_recordset's column-list alias trips
// TestEveryFunctionSQLcMustTypeIsDeclared's relation/call scan).
func (q *Queries) AdminUpsertNationalTariffSchedule(ctx context.Context, entries []byte) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpsertNationalTariffSchedule, entries)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpsertPlatformFactor = `-- name: AdminUpsertPlatformFactor :one
insert into emission_factors
    (id, company_id, key, label, main_category, sub_categories, category_path,
     base_factor, base_unit, fuel_type, vehicle_type, scope, iso_category,
     status, source, source_year, source_url)
values (
    coalesce(nullif($1::uuid, '00000000-0000-0000-0000-000000000000'::uuid),
             gen_random_uuid()),
    null, $2, $3, $4,
    $5::text[], $6::text[],
    $7::numeric, $8, $9::text,
    $10::text, $11::carbon_scope, $12::text,
    $13::text, $14::text, $15::smallint,
    $16::text
)
on conflict (coalesce(company_id, '00000000-0000-0000-0000-000000000000'::uuid), key)
do update set
    label = excluded.label,
    main_category = excluded.main_category,
    sub_categories = excluded.sub_categories,
    category_path = excluded.category_path,
    base_factor = excluded.base_factor,
    base_unit = excluded.base_unit,
    fuel_type = excluded.fuel_type,
    vehicle_type = excluded.vehicle_type,
    scope = excluded.scope,
    iso_category = excluded.iso_category,
    status = excluded.status,
    source = excluded.source,
    source_year = excluded.source_year,
    source_url = excluded.source_url,
    updated_at = now()
returning id, company_id, key, label, main_category, sub_categories, category_path, base_factor, base_unit, fuel_type, vehicle_type, scope, iso_category, status, source, source_year, source_url, created_at, updated_at
`

type AdminUpsertPlatformFactorParams struct {
	ID            uuid.UUID
	Key           string
	Label         string
	MainCategory  string
	SubCategories []string
	CategoryPath  []string
	BaseFactor    pgtype.Numeric
	BaseUnit      string
	FuelType      *string
	VehicleType   *string
	Scope         NullCarbonScope
	IsoCategory   *string
	Status        *string
	Source        *string
	SourceYear    *int16
	SourceUrl     *string
}

// AdminUpsertPlatformFactor writes ONLY a platform factor: company_id is
// hard-coded null in the inserted row (never taken from a parameter), so the
// (coalesce(company_id, zero uuid), key) conflict target can only ever match
// another company_id-null row. A company-owned factor sharing the same key
// lives at a different coalesce value and is untouched.
func (q *Queries) AdminUpsertPlatformFactor(ctx context.Context, arg AdminUpsertPlatformFactorParams) (EmissionFactor, error) {
	row := q.db.QueryRow(ctx, adminUpsertPlatformFactor,
		arg.ID,
		arg.Key,
		arg.Label,
		arg.MainCategory,
		arg.SubCategories,
		arg.CategoryPath,
		arg.BaseFactor,
		arg.BaseUnit,
		arg.FuelType,
		arg.VehicleType,
		arg.Scope,
		arg.IsoCategory,
		arg.Status,
		arg.Source,
		arg.SourceYear,
		arg.SourceUrl,
	)
	var i EmissionFactor
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Key,
		&i.Label,
		&i.MainCategory,
		&i.SubCategories,
		&i.CategoryPath,
		&i.BaseFactor,
		&i.BaseUnit,
		&i.FuelType,
		&i.VehicleType,
		&i.Scope,
		&i.IsoCategory,
		&i.Status,
		&i.Source,
		&i.SourceYear,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
