// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_definitions.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const adminIntegrationDefinitionCreate = `-- name: AdminIntegrationDefinitionCreate :one

insert into integration_definitions (id, provider, subtype, endpoints)
values ($1, $2, $3, $4)
returning id, provider, subtype, endpoints, created_at, updated_at
`

type AdminIntegrationDefinitionCreateParams struct {
	ID        uuid.UUID
	Provider  IntegrationProvider
	Subtype   string
	Endpoints []byte
}

// Integration definition administration (05 §15, F6a R176): platform rows,
// written only by the admin role.
func (q *Queries) AdminIntegrationDefinitionCreate(ctx context.Context, arg AdminIntegrationDefinitionCreateParams) (IntegrationDefinition, error) {
	row := q.db.QueryRow(ctx, adminIntegrationDefinitionCreate,
		arg.ID,
		arg.Provider,
		arg.Subtype,
		arg.Endpoints,
	)
	var i IntegrationDefinition
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Subtype,
		&i.Endpoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminIntegrationDefinitionDeleteUnused = `-- name: AdminIntegrationDefinitionDeleteUnused :execrows
delete from integration_definitions d
where d.id = $1
  and not exists (select 1 from integration_credentials c where c.definition_id = d.id)
`

// Refuses a definition any credential still references (R176).
func (q *Queries) AdminIntegrationDefinitionDeleteUnused(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, adminIntegrationDefinitionDeleteUnused, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminIntegrationDefinitionExists = `-- name: AdminIntegrationDefinitionExists :one
select exists(select 1 from integration_definitions where id = $1)
`

func (q *Queries) AdminIntegrationDefinitionExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, adminIntegrationDefinitionExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const adminIntegrationDefinitionUpdate = `-- name: AdminIntegrationDefinitionUpdate :one
update integration_definitions
set subtype = $1, endpoints = $2, updated_at = now()
where id = $3
returning id, provider, subtype, endpoints, created_at, updated_at
`

type AdminIntegrationDefinitionUpdateParams struct {
	Subtype   string
	Endpoints []byte
	ID        uuid.UUID
}

func (q *Queries) AdminIntegrationDefinitionUpdate(ctx context.Context, arg AdminIntegrationDefinitionUpdateParams) (IntegrationDefinition, error) {
	row := q.db.QueryRow(ctx, adminIntegrationDefinitionUpdate, arg.Subtype, arg.Endpoints, arg.ID)
	var i IntegrationDefinition
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Subtype,
		&i.Endpoints,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
