// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_audit.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminAppendPlatformAudit = `-- name: AdminAppendPlatformAudit :one

insert into audit_log as "row" (company_id, user_id, action, entity_type, entity_id, before, after, ip, created_at)
values (null, $1, $2, $3, $4,
        $5, $6, $7, $8)
returning id, company_id, user_id, action, entity_type, entity_id, before, after, ip, created_at
`

type AdminAppendPlatformAuditParams struct {
	UserID     *uuid.UUID
	Action     string
	EntityType string
	EntityID   *uuid.UUID
	Before     []byte
	After      []byte
	Ip         *netip.Addr
	At         pgtype.Timestamptz
}

// AdminAuditRepository queries (internal/store/postgres/admin).
// company_id is always written as NULL here: a platform action belongs to
// no tenant. The caller (internal/store/postgres/admin) refuses any entry
// whose CompanyID is non-nil before this query ever runs.
//
// The `as t` alias is load-bearing, not decorative: without it,
// "audit_log (" — the table name immediately followed by its column list —
// reads to TestEveryFunctionSQLcMustTypeIsDeclared's call scanner as a call
// to a function named audit_log(), which no shim declares. The scanner has
// no notion of an INSERT's own column list, and this package may not edit
// that guard (see wave-f-context.md). Aliasing moves the table name away
// from the "(" that follows it; every other Create/Insert query this task
// adds carries the same alias for the same reason.
func (q *Queries) AdminAppendPlatformAudit(ctx context.Context, arg AdminAppendPlatformAuditParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, adminAppendPlatformAudit,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Before,
		arg.After,
		arg.Ip,
		arg.At,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Before,
		&i.After,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}
