// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_solar.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const adminLinkedPlants = `-- name: AdminLinkedPlants :many

select p.company_id, p.id as plant_id
from power_plants p
join companies c on c.id = p.company_id
where p.deleted_at is null and c.deleted_at is null and p.isolar_ps_id is not null
order by p.company_id, p.id
`

type AdminLinkedPlantsRow struct {
	CompanyID uuid.UUID
	PlantID   uuid.UUID
}

// AdminSolarRepository: platform-wide discovery for the iSolar ticks (R288),
// called only from internal/store/postgres/admin/solar.go.
func (q *Queries) AdminLinkedPlants(ctx context.Context) ([]AdminLinkedPlantsRow, error) {
	rows, err := q.db.Query(ctx, adminLinkedPlants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminLinkedPlantsRow
	for rows.Next() {
		var i AdminLinkedPlantsRow
		if err := rows.Scan(&i.CompanyID, &i.PlantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
