// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const analyticsConsumptionDaily = `-- name: AnalyticsConsumptionDaily :many
select c.analyzer_id, c.bucket, c.active_import_start, c.active_import_end, c.active_consumption, c.inductive_consumption, c.capacitive_consumption, c.t1_consumption, c.t2_consumption, c.t3_consumption, c.active_generation, c.inductive_generation, c.capacitive_generation, c.t1_generation, c.t2_generation, c.t3_generation, c.max_demand_kw, c.active_index, c.inductive_index, c.capacitive_index, c.t1_index, c.t2_index, c.t3_index, c.active_generation_index, c.reading_count, c.first_ts, c.inductive_consumption_start, c.capacitive_consumption_start, c.t1_consumption_start, c.t2_consumption_start, c.t3_consumption_start, c.active_generation_start, c.inductive_generation_start, c.capacitive_generation_start, c.t1_generation_start, c.t2_generation_start, c.t3_generation_start, c.inductive_generation_index, c.capacitive_generation_index, c.t1_generation_index, c.t2_generation_index, c.t3_generation_index from consumption_daily c
join analyzers a on a.id = c.analyzer_id
where a.company_id = $1
  and ($2::boolean or a.building_id = any($3::uuid[]))
  and a.deleted_at is null
  and c.analyzer_id = any($4::uuid[])
  and c.bucket >= $5::timestamptz
  and c.bucket < $6::timestamptz
order by c.analyzer_id, c.bucket
`

type AnalyticsConsumptionDailyParams struct {
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
	AnalyzerIds  []uuid.UUID
	FromTs       pgtype.Timestamptz
	ToTs         pgtype.Timestamptz
}

// Buckets are Europe/Istanbul-local instants (migration 00005): a day
// boundary here is midnight IN ISTANBUL, not UTC. A caller that constructs
// TimeRange bounds from UTC calendar days will see this window's edges land
// mid-bucket; see AnalyticsRepository's ConsumptionDaily doc comment.
func (q *Queries) AnalyticsConsumptionDaily(ctx context.Context, arg AnalyticsConsumptionDailyParams) ([]ConsumptionDaily, error) {
	rows, err := q.db.Query(ctx, analyticsConsumptionDaily,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
		arg.AnalyzerIds,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsumptionDaily
	for rows.Next() {
		var i ConsumptionDaily
		if err := rows.Scan(
			&i.AnalyzerID,
			&i.Bucket,
			&i.ActiveImportStart,
			&i.ActiveImportEnd,
			&i.ActiveConsumption,
			&i.InductiveConsumption,
			&i.CapacitiveConsumption,
			&i.T1Consumption,
			&i.T2Consumption,
			&i.T3Consumption,
			&i.ActiveGeneration,
			&i.InductiveGeneration,
			&i.CapacitiveGeneration,
			&i.T1Generation,
			&i.T2Generation,
			&i.T3Generation,
			&i.MaxDemandKw,
			&i.ActiveIndex,
			&i.InductiveIndex,
			&i.CapacitiveIndex,
			&i.T1Index,
			&i.T2Index,
			&i.T3Index,
			&i.ActiveGenerationIndex,
			&i.ReadingCount,
			&i.FirstTs,
			&i.InductiveConsumptionStart,
			&i.CapacitiveConsumptionStart,
			&i.T1ConsumptionStart,
			&i.T2ConsumptionStart,
			&i.T3ConsumptionStart,
			&i.ActiveGenerationStart,
			&i.InductiveGenerationStart,
			&i.CapacitiveGenerationStart,
			&i.T1GenerationStart,
			&i.T2GenerationStart,
			&i.T3GenerationStart,
			&i.InductiveGenerationIndex,
			&i.CapacitiveGenerationIndex,
			&i.T1GenerationIndex,
			&i.T2GenerationIndex,
			&i.T3GenerationIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsConsumptionHourly = `-- name: AnalyticsConsumptionHourly :many

select c.analyzer_id, c.bucket, c.active_import_start, c.active_import_end, c.active_consumption, c.inductive_consumption, c.capacitive_consumption, c.t1_consumption, c.t2_consumption, c.t3_consumption, c.active_generation, c.inductive_generation, c.capacitive_generation, c.t1_generation, c.t2_generation, c.t3_generation, c.max_demand_kw, c.active_index, c.inductive_index, c.capacitive_index, c.t1_index, c.t2_index, c.t3_index, c.active_generation_index, c.reading_count, c.first_ts, c.inductive_consumption_start, c.capacitive_consumption_start, c.t1_consumption_start, c.t2_consumption_start, c.t3_consumption_start, c.active_generation_start, c.inductive_generation_start, c.capacitive_generation_start, c.t1_generation_start, c.t2_generation_start, c.t3_generation_start, c.inductive_generation_index, c.capacitive_generation_index, c.t1_generation_index, c.t2_generation_index, c.t3_generation_index from consumption_hourly c
join analyzers a on a.id = c.analyzer_id
where a.company_id = $1
  and ($2::boolean or a.building_id = any($3::uuid[]))
  and a.deleted_at is null
  and c.analyzer_id = any($4::uuid[])
  and c.bucket >= $5::timestamptz
  and c.bucket < $6::timestamptz
order by c.analyzer_id, c.bucket
`

type AnalyticsConsumptionHourlyParams struct {
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
	AnalyzerIds  []uuid.UUID
	FromTs       pgtype.Timestamptz
	ToTs         pgtype.Timestamptz
}

// AnalyticsRepository's queries, over the six continuous aggregates
// (migration 00005). These are MATERIALISED reads for dashboards and
// reports — never the billing-grade surface, which is ReadingRepository.
//
// None of the six aggregates carry a company_id: the consumption_* ones join
// through analyzers, the plant_production_* ones through power_plants (which
// has no building_id at all, per PlantRepository's doc). analyzer_ids /
// plant_ids are REQUIRED POSITIONAL parameters (repository.go's
// AnalyticsRepository doc): EMPTY or nil means NO ROWS, fail-closed,
// identical to Scope.BuildingIDs — there is no "every id visible to scope"
// form. `c.analyzer_id = any(sqlc.arg(analyzer_ids)::uuid[])` gets this for
// free: a nil slice encodes to NULL::uuid[], and `x = any(NULL)` is NULL,
// which the WHERE clause reads as false, matching zero rows; an empty (but
// non-nil) slice encodes to '{}', and `x = any('{}')` is false outright.
func (q *Queries) AnalyticsConsumptionHourly(ctx context.Context, arg AnalyticsConsumptionHourlyParams) ([]ConsumptionHourly, error) {
	rows, err := q.db.Query(ctx, analyticsConsumptionHourly,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
		arg.AnalyzerIds,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsumptionHourly
	for rows.Next() {
		var i ConsumptionHourly
		if err := rows.Scan(
			&i.AnalyzerID,
			&i.Bucket,
			&i.ActiveImportStart,
			&i.ActiveImportEnd,
			&i.ActiveConsumption,
			&i.InductiveConsumption,
			&i.CapacitiveConsumption,
			&i.T1Consumption,
			&i.T2Consumption,
			&i.T3Consumption,
			&i.ActiveGeneration,
			&i.InductiveGeneration,
			&i.CapacitiveGeneration,
			&i.T1Generation,
			&i.T2Generation,
			&i.T3Generation,
			&i.MaxDemandKw,
			&i.ActiveIndex,
			&i.InductiveIndex,
			&i.CapacitiveIndex,
			&i.T1Index,
			&i.T2Index,
			&i.T3Index,
			&i.ActiveGenerationIndex,
			&i.ReadingCount,
			&i.FirstTs,
			&i.InductiveConsumptionStart,
			&i.CapacitiveConsumptionStart,
			&i.T1ConsumptionStart,
			&i.T2ConsumptionStart,
			&i.T3ConsumptionStart,
			&i.ActiveGenerationStart,
			&i.InductiveGenerationStart,
			&i.CapacitiveGenerationStart,
			&i.T1GenerationStart,
			&i.T2GenerationStart,
			&i.T3GenerationStart,
			&i.InductiveGenerationIndex,
			&i.CapacitiveGenerationIndex,
			&i.T1GenerationIndex,
			&i.T2GenerationIndex,
			&i.T3GenerationIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsConsumptionMonthly = `-- name: AnalyticsConsumptionMonthly :many
select c.analyzer_id, c.bucket, c.active_import_start, c.active_import_end, c.active_consumption, c.inductive_consumption, c.capacitive_consumption, c.t1_consumption, c.t2_consumption, c.t3_consumption, c.active_generation, c.inductive_generation, c.capacitive_generation, c.t1_generation, c.t2_generation, c.t3_generation, c.max_demand_kw, c.active_index, c.inductive_index, c.capacitive_index, c.t1_index, c.t2_index, c.t3_index, c.active_generation_index, c.reading_count, c.first_ts, c.inductive_consumption_start, c.capacitive_consumption_start, c.t1_consumption_start, c.t2_consumption_start, c.t3_consumption_start, c.active_generation_start, c.inductive_generation_start, c.capacitive_generation_start, c.t1_generation_start, c.t2_generation_start, c.t3_generation_start, c.inductive_generation_index, c.capacitive_generation_index, c.t1_generation_index, c.t2_generation_index, c.t3_generation_index from consumption_monthly c
join analyzers a on a.id = c.analyzer_id
where a.company_id = $1
  and ($2::boolean or a.building_id = any($3::uuid[]))
  and a.deleted_at is null
  and c.analyzer_id = any($4::uuid[])
  and c.bucket >= $5::timestamptz
  and c.bucket < $6::timestamptz
order by c.analyzer_id, c.bucket
`

type AnalyticsConsumptionMonthlyParams struct {
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
	AnalyzerIds  []uuid.UUID
	FromTs       pgtype.Timestamptz
	ToTs         pgtype.Timestamptz
}

// materialized_only = true (migration 00005): the open month is ABSENT from
// this view, not stale. A caller wanting month-to-date must compose this with
// the open period from consumption_daily or meter_readings; this repository
// does not do that composition, and must not be "fixed" by flipping
// materialized_only (see migration 00005's own header). Buckets are
// Europe/Istanbul-local instants, same as ConsumptionDaily above.
func (q *Queries) AnalyticsConsumptionMonthly(ctx context.Context, arg AnalyticsConsumptionMonthlyParams) ([]ConsumptionMonthly, error) {
	rows, err := q.db.Query(ctx, analyticsConsumptionMonthly,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
		arg.AnalyzerIds,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsumptionMonthly
	for rows.Next() {
		var i ConsumptionMonthly
		if err := rows.Scan(
			&i.AnalyzerID,
			&i.Bucket,
			&i.ActiveImportStart,
			&i.ActiveImportEnd,
			&i.ActiveConsumption,
			&i.InductiveConsumption,
			&i.CapacitiveConsumption,
			&i.T1Consumption,
			&i.T2Consumption,
			&i.T3Consumption,
			&i.ActiveGeneration,
			&i.InductiveGeneration,
			&i.CapacitiveGeneration,
			&i.T1Generation,
			&i.T2Generation,
			&i.T3Generation,
			&i.MaxDemandKw,
			&i.ActiveIndex,
			&i.InductiveIndex,
			&i.CapacitiveIndex,
			&i.T1Index,
			&i.T2Index,
			&i.T3Index,
			&i.ActiveGenerationIndex,
			&i.ReadingCount,
			&i.FirstTs,
			&i.InductiveConsumptionStart,
			&i.CapacitiveConsumptionStart,
			&i.T1ConsumptionStart,
			&i.T2ConsumptionStart,
			&i.T3ConsumptionStart,
			&i.ActiveGenerationStart,
			&i.InductiveGenerationStart,
			&i.CapacitiveGenerationStart,
			&i.T1GenerationStart,
			&i.T2GenerationStart,
			&i.T3GenerationStart,
			&i.InductiveGenerationIndex,
			&i.CapacitiveGenerationIndex,
			&i.T1GenerationIndex,
			&i.T2GenerationIndex,
			&i.T3GenerationIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsConsumptionYearly = `-- name: AnalyticsConsumptionYearly :many
select c.analyzer_id, c.bucket, c.active_import_start, c.active_import_end, c.active_consumption, c.inductive_consumption, c.capacitive_consumption, c.t1_consumption, c.t2_consumption, c.t3_consumption, c.active_generation, c.inductive_generation, c.capacitive_generation, c.t1_generation, c.t2_generation, c.t3_generation, c.max_demand_kw, c.active_index, c.inductive_index, c.capacitive_index, c.t1_index, c.t2_index, c.t3_index, c.active_generation_index, c.reading_count, c.first_ts, c.inductive_consumption_start, c.capacitive_consumption_start, c.t1_consumption_start, c.t2_consumption_start, c.t3_consumption_start, c.active_generation_start, c.inductive_generation_start, c.capacitive_generation_start, c.t1_generation_start, c.t2_generation_start, c.t3_generation_start, c.inductive_generation_index, c.capacitive_generation_index, c.t1_generation_index, c.t2_generation_index, c.t3_generation_index from consumption_yearly c
join analyzers a on a.id = c.analyzer_id
where a.company_id = $1
  and ($2::boolean or a.building_id = any($3::uuid[]))
  and a.deleted_at is null
  and c.analyzer_id = any($4::uuid[])
  and c.bucket >= $5::timestamptz
  and c.bucket < $6::timestamptz
order by c.analyzer_id, c.bucket
`

type AnalyticsConsumptionYearlyParams struct {
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
	AnalyzerIds  []uuid.UUID
	FromTs       pgtype.Timestamptz
	ToTs         pgtype.Timestamptz
}

// materialized_only = true: the open year is ABSENT, same as
// AnalyticsConsumptionMonthly above. Buckets are Europe/Istanbul-local
// instants, same as ConsumptionDaily above.
func (q *Queries) AnalyticsConsumptionYearly(ctx context.Context, arg AnalyticsConsumptionYearlyParams) ([]ConsumptionYearly, error) {
	rows, err := q.db.Query(ctx, analyticsConsumptionYearly,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
		arg.AnalyzerIds,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsumptionYearly
	for rows.Next() {
		var i ConsumptionYearly
		if err := rows.Scan(
			&i.AnalyzerID,
			&i.Bucket,
			&i.ActiveImportStart,
			&i.ActiveImportEnd,
			&i.ActiveConsumption,
			&i.InductiveConsumption,
			&i.CapacitiveConsumption,
			&i.T1Consumption,
			&i.T2Consumption,
			&i.T3Consumption,
			&i.ActiveGeneration,
			&i.InductiveGeneration,
			&i.CapacitiveGeneration,
			&i.T1Generation,
			&i.T2Generation,
			&i.T3Generation,
			&i.MaxDemandKw,
			&i.ActiveIndex,
			&i.InductiveIndex,
			&i.CapacitiveIndex,
			&i.T1Index,
			&i.T2Index,
			&i.T3Index,
			&i.ActiveGenerationIndex,
			&i.ReadingCount,
			&i.FirstTs,
			&i.InductiveConsumptionStart,
			&i.CapacitiveConsumptionStart,
			&i.T1ConsumptionStart,
			&i.T2ConsumptionStart,
			&i.T3ConsumptionStart,
			&i.ActiveGenerationStart,
			&i.InductiveGenerationStart,
			&i.CapacitiveGenerationStart,
			&i.T1GenerationStart,
			&i.T2GenerationStart,
			&i.T3GenerationStart,
			&i.InductiveGenerationIndex,
			&i.CapacitiveGenerationIndex,
			&i.T1GenerationIndex,
			&i.T2GenerationIndex,
			&i.T3GenerationIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsProductionDaily = `-- name: AnalyticsProductionDaily :many
select p.plant_id, p.bucket, p.production_kwh, p.max_active_power_kw from plant_production_daily p
join power_plants pp on pp.id = p.plant_id
where pp.company_id = $1
  and pp.deleted_at is null
  and p.plant_id = any($2::uuid[])
  and p.bucket >= $3::timestamptz
  and p.bucket < $4::timestamptz
order by p.plant_id, p.bucket
`

type AnalyticsProductionDailyParams struct {
	CompanyID uuid.UUID
	PlantIds  []uuid.UUID
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
}

// Buckets are Europe/Istanbul-local instants, same reasoning as the
// consumption side.
func (q *Queries) AnalyticsProductionDaily(ctx context.Context, arg AnalyticsProductionDailyParams) ([]PlantProductionDaily, error) {
	rows, err := q.db.Query(ctx, analyticsProductionDaily,
		arg.CompanyID,
		arg.PlantIds,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlantProductionDaily
	for rows.Next() {
		var i PlantProductionDaily
		if err := rows.Scan(
			&i.PlantID,
			&i.Bucket,
			&i.ProductionKwh,
			&i.MaxActivePowerKw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsProductionMonthly = `-- name: AnalyticsProductionMonthly :many
select p.plant_id, p.bucket, p.production_kwh, p.max_active_power_kw from plant_production_monthly p
join power_plants pp on pp.id = p.plant_id
where pp.company_id = $1
  and pp.deleted_at is null
  and p.plant_id = any($2::uuid[])
  and p.bucket >= $3::timestamptz
  and p.bucket < $4::timestamptz
order by p.plant_id, p.bucket
`

type AnalyticsProductionMonthlyParams struct {
	CompanyID uuid.UUID
	PlantIds  []uuid.UUID
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
}

// materialized_only = true: the open month is ABSENT, same reasoning as the
// consumption side. Buckets are Europe/Istanbul-local instants.
func (q *Queries) AnalyticsProductionMonthly(ctx context.Context, arg AnalyticsProductionMonthlyParams) ([]PlantProductionMonthly, error) {
	rows, err := q.db.Query(ctx, analyticsProductionMonthly,
		arg.CompanyID,
		arg.PlantIds,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlantProductionMonthly
	for rows.Next() {
		var i PlantProductionMonthly
		if err := rows.Scan(
			&i.PlantID,
			&i.Bucket,
			&i.ProductionKwh,
			&i.MaxActivePowerKw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
