// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analyzers.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const analyzerBuildingVisible = `-- name: AnalyzerBuildingVisible :one
select exists(
    select 1 from buildings
    where id = $1
      and company_id = $2
      and ($3::boolean or id = any($4::uuid[]))
      and deleted_at is null
)
`

type AnalyzerBuildingVisibleParams struct {
	BuildingID   uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) AnalyzerBuildingVisible(ctx context.Context, arg AnalyzerBuildingVisibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, analyzerBuildingVisible,
		arg.BuildingID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const analyzerCreate = `-- name: AnalyzerCreate :one
insert into analyzers as "row"
    (id, company_id, building_id, provider, provider_subtype, installation_number,
     customer_name, address, province, district, neighbourhood, street,
     tariff_type, tariff_kind, installation_kind, installed_power_kw, meter_number,
     meter_model, meter_multiplier, counterparty_no, metering_point_name,
     latitude, longitude, etso_code, definition_type, is_active, created_at, updated_at)
values ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9, $10, $11,
        $12, $13, $14, $15,
        $16, $17, $18,
        $19, $20, $21,
        $22, $23, $24, $25,
        $26, $27, $27)
returning id, company_id, building_id, provider, provider_subtype, installation_number, customer_name, address, province, district, neighbourhood, street, tariff_type, tariff_kind, installation_kind, installed_power_kw, meter_number, meter_model, meter_multiplier, counterparty_no, metering_point_name, latitude, longitude, etso_code, definition_type, last_reading_at, is_active, created_at, updated_at, deleted_at
`

type AnalyzerCreateParams struct {
	ID                 uuid.UUID
	CompanyID          uuid.UUID
	BuildingID         *uuid.UUID
	Provider           IntegrationProvider
	ProviderSubtype    string
	InstallationNumber string
	CustomerName       *string
	Address            *string
	Province           *string
	District           *string
	Neighbourhood      *string
	Street             *string
	TariffType         *string
	TariffKind         *string
	InstallationKind   *string
	InstalledPowerKw   pgtype.Numeric
	MeterNumber        *string
	MeterModel         *string
	MeterMultiplier    pgtype.Numeric
	CounterpartyNo     *string
	MeteringPointName  *string
	Latitude           pgtype.Numeric
	Longitude          pgtype.Numeric
	EtsoCode           *string
	DefinitionType     *int16
	IsActive           bool
	At                 pgtype.Timestamptz
}

// The `as "row"` alias dodges TestEveryFunctionSQLcMustTypeIsDeclared's call
// scanner, which otherwise reads "analyzers (" as a call to a function named
// analyzers() — see queries/admin_audit.sql's comment on AdminAppendPlatformAudit.
func (q *Queries) AnalyzerCreate(ctx context.Context, arg AnalyzerCreateParams) (Analyzer, error) {
	row := q.db.QueryRow(ctx, analyzerCreate,
		arg.ID,
		arg.CompanyID,
		arg.BuildingID,
		arg.Provider,
		arg.ProviderSubtype,
		arg.InstallationNumber,
		arg.CustomerName,
		arg.Address,
		arg.Province,
		arg.District,
		arg.Neighbourhood,
		arg.Street,
		arg.TariffType,
		arg.TariffKind,
		arg.InstallationKind,
		arg.InstalledPowerKw,
		arg.MeterNumber,
		arg.MeterModel,
		arg.MeterMultiplier,
		arg.CounterpartyNo,
		arg.MeteringPointName,
		arg.Latitude,
		arg.Longitude,
		arg.EtsoCode,
		arg.DefinitionType,
		arg.IsActive,
		arg.At,
	)
	var i Analyzer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.Provider,
		&i.ProviderSubtype,
		&i.InstallationNumber,
		&i.CustomerName,
		&i.Address,
		&i.Province,
		&i.District,
		&i.Neighbourhood,
		&i.Street,
		&i.TariffType,
		&i.TariffKind,
		&i.InstallationKind,
		&i.InstalledPowerKw,
		&i.MeterNumber,
		&i.MeterModel,
		&i.MeterMultiplier,
		&i.CounterpartyNo,
		&i.MeteringPointName,
		&i.Latitude,
		&i.Longitude,
		&i.EtsoCode,
		&i.DefinitionType,
		&i.LastReadingAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const analyzerGet = `-- name: AnalyzerGet :one

select id, company_id, building_id, provider, provider_subtype, installation_number, customer_name, address, province, district, neighbourhood, street, tariff_type, tariff_kind, installation_kind, installed_power_kw, meter_number, meter_model, meter_multiplier, counterparty_no, metering_point_name, latitude, longitude, etso_code, definition_type, last_reading_at, is_active, created_at, updated_at, deleted_at from analyzers
where id = $1
  and company_id = $2
  and ($3::boolean
       or (building_id is not null and building_id = any($4::uuid[])))
  and deleted_at is null
`

type AnalyzerGetParams struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// AnalyzerRepository queries.
//
// Every read below shares one visibility predicate: an analyzer is visible to
// a Scope when all_buildings is true (whatever building_id holds, including
// NULL), or when building_id is not null and is one of building_ids. That
// single formula is also what makes AnalyzerFilter.Unassigned fail closed for
// a narrow Scope with no extra code: a NULL building_id can never be `any`
// of a concrete list, so adding "and building_id is null" for Unassigned
// combines with the predicate to select nothing unless all_buildings is set.
func (q *Queries) AnalyzerGet(ctx context.Context, arg AnalyzerGetParams) (Analyzer, error) {
	row := q.db.QueryRow(ctx, analyzerGet,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i Analyzer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.Provider,
		&i.ProviderSubtype,
		&i.InstallationNumber,
		&i.CustomerName,
		&i.Address,
		&i.Province,
		&i.District,
		&i.Neighbourhood,
		&i.Street,
		&i.TariffType,
		&i.TariffKind,
		&i.InstallationKind,
		&i.InstalledPowerKw,
		&i.MeterNumber,
		&i.MeterModel,
		&i.MeterMultiplier,
		&i.CounterpartyNo,
		&i.MeteringPointName,
		&i.Latitude,
		&i.Longitude,
		&i.EtsoCode,
		&i.DefinitionType,
		&i.LastReadingAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const analyzerGetByInstallation = `-- name: AnalyzerGetByInstallation :one
select id, company_id, building_id, provider, provider_subtype, installation_number, customer_name, address, province, district, neighbourhood, street, tariff_type, tariff_kind, installation_kind, installed_power_kw, meter_number, meter_model, meter_multiplier, counterparty_no, metering_point_name, latitude, longitude, etso_code, definition_type, last_reading_at, is_active, created_at, updated_at, deleted_at from analyzers
where provider = $1
  and provider_subtype = $2
  and installation_number = $3
  and company_id = $4
  and ($5::boolean
       or (building_id is not null and building_id = any($6::uuid[])))
  and deleted_at is null
`

type AnalyzerGetByInstallationParams struct {
	Provider           IntegrationProvider
	ProviderSubtype    string
	InstallationNumber string
	CompanyID          uuid.UUID
	AllBuildings       bool
	BuildingIds        []uuid.UUID
}

func (q *Queries) AnalyzerGetByInstallation(ctx context.Context, arg AnalyzerGetByInstallationParams) (Analyzer, error) {
	row := q.db.QueryRow(ctx, analyzerGetByInstallation,
		arg.Provider,
		arg.ProviderSubtype,
		arg.InstallationNumber,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i Analyzer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.Provider,
		&i.ProviderSubtype,
		&i.InstallationNumber,
		&i.CustomerName,
		&i.Address,
		&i.Province,
		&i.District,
		&i.Neighbourhood,
		&i.Street,
		&i.TariffType,
		&i.TariffKind,
		&i.InstallationKind,
		&i.InstalledPowerKw,
		&i.MeterNumber,
		&i.MeterModel,
		&i.MeterMultiplier,
		&i.CounterpartyNo,
		&i.MeteringPointName,
		&i.Latitude,
		&i.Longitude,
		&i.EtsoCode,
		&i.DefinitionType,
		&i.LastReadingAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const analyzerList = `-- name: AnalyzerList :many
select id, company_id, building_id, provider, provider_subtype, installation_number, customer_name, address, province, district, neighbourhood, street, tariff_type, tariff_kind, installation_kind, installed_power_kw, meter_number, meter_model, meter_multiplier, counterparty_no, metering_point_name, latitude, longitude, etso_code, definition_type, last_reading_at, is_active, created_at, updated_at, deleted_at from analyzers
where company_id = $1
  and ($2::boolean
       or (building_id is not null and building_id = any($3::uuid[])))
  and (cardinality($4::uuid[]) = 0 or id = any($4::uuid[]))
  and ($5::uuid is null or building_id = $5)
  and (not $6::boolean or building_id is null)
  -- Compared as text[], not integration_provider[] — see UserList's
  -- comment on the roles filter in queries/users.sql for why.
  and (cardinality($7::text[]) = 0
       or provider::text = any($7::text[]))
  and ($8::boolean is null or is_active = $8)
  and ($9::boolean or deleted_at is null)
order by installation_number
limit $11 offset $10
`

type AnalyzerListParams struct {
	CompanyID        uuid.UUID
	AllBuildings     bool
	BuildingIds      []uuid.UUID
	FilterIds        []uuid.UUID
	FilterBuildingID *uuid.UUID
	Unassigned       bool
	Providers        []string
	IsActive         *bool
	IncludeDeleted   bool
	PageOffset       int32
	PageLimit        int32
}

func (q *Queries) AnalyzerList(ctx context.Context, arg AnalyzerListParams) ([]Analyzer, error) {
	rows, err := q.db.Query(ctx, analyzerList,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
		arg.FilterIds,
		arg.FilterBuildingID,
		arg.Unassigned,
		arg.Providers,
		arg.IsActive,
		arg.IncludeDeleted,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Analyzer
	for rows.Next() {
		var i Analyzer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BuildingID,
			&i.Provider,
			&i.ProviderSubtype,
			&i.InstallationNumber,
			&i.CustomerName,
			&i.Address,
			&i.Province,
			&i.District,
			&i.Neighbourhood,
			&i.Street,
			&i.TariffType,
			&i.TariffKind,
			&i.InstallationKind,
			&i.InstalledPowerKw,
			&i.MeterNumber,
			&i.MeterModel,
			&i.MeterMultiplier,
			&i.CounterpartyNo,
			&i.MeteringPointName,
			&i.Latitude,
			&i.Longitude,
			&i.EtsoCode,
			&i.DefinitionType,
			&i.LastReadingAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyzerSoftDelete = `-- name: AnalyzerSoftDelete :execrows
update analyzers
set deleted_at = $1
where id = $2
  and company_id = $3
  and ($4::boolean
       or (building_id is not null and building_id = any($5::uuid[])))
  and deleted_at is null
`

type AnalyzerSoftDeleteParams struct {
	DeletedAt    pgtype.Timestamptz
	ID           uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) AnalyzerSoftDelete(ctx context.Context, arg AnalyzerSoftDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, analyzerSoftDelete,
		arg.DeletedAt,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const analyzerTouchLastReading = `-- name: AnalyzerTouchLastReading :execrows
update analyzers
set last_reading_at = greatest(coalesce(last_reading_at, '-infinity'::timestamptz), $1)
where id = $2
  and company_id = $3
  and ($4::boolean
       or (building_id is not null and building_id = any($5::uuid[])))
  and deleted_at is null
`

type AnalyzerTouchLastReadingParams struct {
	At           pgtype.Timestamptz
	ID           uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) AnalyzerTouchLastReading(ctx context.Context, arg AnalyzerTouchLastReadingParams) (int64, error) {
	result, err := q.db.Exec(ctx, analyzerTouchLastReading,
		arg.At,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const analyzerUpdate = `-- name: AnalyzerUpdate :one
update analyzers
set building_id = $1,
    customer_name = $2,
    address = $3,
    province = $4,
    district = $5,
    neighbourhood = $6,
    street = $7,
    tariff_type = $8,
    tariff_kind = $9,
    installation_kind = $10,
    installed_power_kw = $11,
    meter_number = $12,
    meter_model = $13,
    meter_multiplier = $14,
    counterparty_no = $15,
    metering_point_name = $16,
    latitude = $17,
    longitude = $18,
    etso_code = $19,
    definition_type = $20,
    is_active = $21,
    updated_at = $22
where id = $23
  and company_id = $24
  and ($25::boolean
       or (building_id is not null and building_id = any($26::uuid[])))
  and deleted_at is null
returning id, company_id, building_id, provider, provider_subtype, installation_number, customer_name, address, province, district, neighbourhood, street, tariff_type, tariff_kind, installation_kind, installed_power_kw, meter_number, meter_model, meter_multiplier, counterparty_no, metering_point_name, latitude, longitude, etso_code, definition_type, last_reading_at, is_active, created_at, updated_at, deleted_at
`

type AnalyzerUpdateParams struct {
	BuildingID        *uuid.UUID
	CustomerName      *string
	Address           *string
	Province          *string
	District          *string
	Neighbourhood     *string
	Street            *string
	TariffType        *string
	TariffKind        *string
	InstallationKind  *string
	InstalledPowerKw  pgtype.Numeric
	MeterNumber       *string
	MeterModel        *string
	MeterMultiplier   pgtype.Numeric
	CounterpartyNo    *string
	MeteringPointName *string
	Latitude          pgtype.Numeric
	Longitude         pgtype.Numeric
	EtsoCode          *string
	DefinitionType    *int16
	IsActive          bool
	UpdatedAt         pgtype.Timestamptz
	ID                uuid.UUID
	CompanyID         uuid.UUID
	AllBuildings      bool
	BuildingIds       []uuid.UUID
}

func (q *Queries) AnalyzerUpdate(ctx context.Context, arg AnalyzerUpdateParams) (Analyzer, error) {
	row := q.db.QueryRow(ctx, analyzerUpdate,
		arg.BuildingID,
		arg.CustomerName,
		arg.Address,
		arg.Province,
		arg.District,
		arg.Neighbourhood,
		arg.Street,
		arg.TariffType,
		arg.TariffKind,
		arg.InstallationKind,
		arg.InstalledPowerKw,
		arg.MeterNumber,
		arg.MeterModel,
		arg.MeterMultiplier,
		arg.CounterpartyNo,
		arg.MeteringPointName,
		arg.Latitude,
		arg.Longitude,
		arg.EtsoCode,
		arg.DefinitionType,
		arg.IsActive,
		arg.UpdatedAt,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i Analyzer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.Provider,
		&i.ProviderSubtype,
		&i.InstallationNumber,
		&i.CustomerName,
		&i.Address,
		&i.Province,
		&i.District,
		&i.Neighbourhood,
		&i.Street,
		&i.TariffType,
		&i.TariffKind,
		&i.InstallationKind,
		&i.InstalledPowerKw,
		&i.MeterNumber,
		&i.MeterModel,
		&i.MeterMultiplier,
		&i.CounterpartyNo,
		&i.MeteringPointName,
		&i.Latitude,
		&i.Longitude,
		&i.EtsoCode,
		&i.DefinitionType,
		&i.LastReadingAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
