// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: anomalies.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const anomalyAnalyzerVisible = `-- name: AnomalyAnalyzerVisible :one
select exists (
    select 1 from analyzers
    where id = $1
      and company_id = $2
      and ($3::boolean or building_id = any($4::uuid[]))
      and deleted_at is null
)
`

type AnomalyAnalyzerVisibleParams struct {
	AnalyzerID   uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) AnomalyAnalyzerVisible(ctx context.Context, arg AnomalyAnalyzerVisibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, anomalyAnalyzerVisible,
		arg.AnalyzerID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const anomalyCreate = `-- name: AnomalyCreate :one
insert into consumption_anomalies (analyzer_id, period_start, period_end, reason, detail)
select a.id, $1::timestamptz, $2::timestamptz, $3::text, $4
from analyzers a
where a.id = $5
  and a.company_id = $6
  and ($7::boolean or a.building_id = any($8::uuid[]))
  and a.deleted_at is null
returning id, analyzer_id, period_start, period_end, reason, detail, resolved_at, resolved_by, resolution, override_values, created_at
`

type AnomalyCreateParams struct {
	PeriodStart  pgtype.Timestamptz
	PeriodEnd    pgtype.Timestamptz
	Reason       string
	Detail       []byte
	AnalyzerID   uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) AnomalyCreate(ctx context.Context, arg AnomalyCreateParams) (ConsumptionAnomaly, error) {
	row := q.db.QueryRow(ctx, anomalyCreate,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Reason,
		arg.Detail,
		arg.AnalyzerID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i ConsumptionAnomaly
	err := row.Scan(
		&i.ID,
		&i.AnalyzerID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Reason,
		&i.Detail,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Resolution,
		&i.OverrideValues,
		&i.CreatedAt,
	)
	return i, err
}

const anomalyGet = `-- name: AnomalyGet :one

select an.id, an.analyzer_id, an.period_start, an.period_end, an.reason, an.detail, an.resolved_at, an.resolved_by, an.resolution, an.override_values, an.created_at from consumption_anomalies an
join analyzers a on a.id = an.analyzer_id
where an.id = $1
  and a.company_id = $2
  and ($3::boolean or a.building_id = any($4::uuid[]))
  and a.deleted_at is null
`

type AnomalyGetParams struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// AnomalyRepository's queries. consumption_anomalies has no company_id:
// every method joins through analyzers. Resolve additionally requires the
// resolver to be a user of the scope's company — folded into the UPDATE's
// own WHERE as an `exists(...)`, in the same single statement as the write,
// rather than a separate pre-check that could race a concurrent change to
// resolved_by's own company.
func (q *Queries) AnomalyGet(ctx context.Context, arg AnomalyGetParams) (ConsumptionAnomaly, error) {
	row := q.db.QueryRow(ctx, anomalyGet,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i ConsumptionAnomaly
	err := row.Scan(
		&i.ID,
		&i.AnalyzerID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Reason,
		&i.Detail,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Resolution,
		&i.OverrideValues,
		&i.CreatedAt,
	)
	return i, err
}

const anomalyList = `-- name: AnomalyList :many
select an.id, an.analyzer_id, an.period_start, an.period_end, an.reason, an.detail, an.resolved_at, an.resolved_by, an.resolution, an.override_values, an.created_at from consumption_anomalies an
join analyzers a on a.id = an.analyzer_id
where a.company_id = $1
  and ($2::boolean or a.building_id = any($3::uuid[]))
  and a.deleted_at is null
  and (cardinality(coalesce($4::uuid[], '{}')) = 0 or an.analyzer_id = any(coalesce($4::uuid[], '{}')))
  and (not $5::boolean or an.resolved_at is null)
  and ($6::text is null or an.reason = $6)
  and ($7::timestamptz is null or an.period_start >= $7)
  and ($8::timestamptz is null or an.period_start < $8)
order by an.period_start desc, an.id
limit $10
offset $9
`

type AnomalyListParams struct {
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
	AnalyzerIds  []uuid.UUID
	Unresolved   bool
	Reason       *string
	FromTs       pgtype.Timestamptz
	ToTs         pgtype.Timestamptz
	PageOffset   int32
	PageLimit    int32
}

func (q *Queries) AnomalyList(ctx context.Context, arg AnomalyListParams) ([]ConsumptionAnomaly, error) {
	rows, err := q.db.Query(ctx, anomalyList,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
		arg.AnalyzerIds,
		arg.Unresolved,
		arg.Reason,
		arg.FromTs,
		arg.ToTs,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsumptionAnomaly
	for rows.Next() {
		var i ConsumptionAnomaly
		if err := rows.Scan(
			&i.ID,
			&i.AnalyzerID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Reason,
			&i.Detail,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.Resolution,
			&i.OverrideValues,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const anomalyResolve = `-- name: AnomalyResolve :one
update consumption_anomalies an set
    resolved_at = $1::timestamptz,
    resolved_by = $2,
    resolution = $3::text,
    override_values = $4
where an.id = $5
  and an.analyzer_id in (
      select a.id from analyzers a
      where a.company_id = $6
        and ($7::boolean or a.building_id = any($8::uuid[]))
        and a.deleted_at is null
  )
  and exists (
      select 1 from users u
      where u.id = $2 and u.company_id = $6 and u.deleted_at is null
  )
returning id, analyzer_id, period_start, period_end, reason, detail, resolved_at, resolved_by, resolution, override_values, created_at
`

type AnomalyResolveParams struct {
	At             pgtype.Timestamptz
	ResolvedBy     *uuid.UUID
	Resolution     string
	OverrideValues []byte
	ID             uuid.UUID
	CompanyID      uuid.UUID
	AllBuildings   bool
	BuildingIds    []uuid.UUID
}

func (q *Queries) AnomalyResolve(ctx context.Context, arg AnomalyResolveParams) (ConsumptionAnomaly, error) {
	row := q.db.QueryRow(ctx, anomalyResolve,
		arg.At,
		arg.ResolvedBy,
		arg.Resolution,
		arg.OverrideValues,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i ConsumptionAnomaly
	err := row.Scan(
		&i.ID,
		&i.AnalyzerID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Reason,
		&i.Detail,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.Resolution,
		&i.OverrideValues,
		&i.CreatedAt,
	)
	return i, err
}
