// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing_parameters.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const billingParametersEffective = `-- name: BillingParametersEffective :one

select effective_from, reactive_penalty_basis, reactive_exempt_below_kw,
  reactive_exempt_terms::text[] as reactive_exempt_terms,
  reactive_exempt_user_groups::text[] as reactive_exempt_user_groups,
  reactive_generation_exempt_kwh, reactive_bands, tiering_groups, tiering_mode,
  tiering_voltage_levels::text[] as tiering_voltage_levels,
  tiering_supply_companies::text[] as tiering_supply_companies,
  ptf_missing_hour_tolerance, demand_overrun_multiplier, money_rounding_mode, created_at
from billing_parameters
where effective_from <= $1
order by effective_from desc
limit 1
`

type BillingParametersEffectiveRow struct {
	EffectiveFrom               pgtype.Date
	ReactivePenaltyBasis        ReactivePenaltyBasis
	ReactiveExemptBelowKw       pgtype.Numeric
	ReactiveExemptTerms         []string
	ReactiveExemptUserGroups    []string
	ReactiveGenerationExemptKwh pgtype.Numeric
	ReactiveBands               []byte
	TieringGroups               []byte
	TieringMode                 TieringMode
	TieringVoltageLevels        []string
	TieringSupplyCompanies      []string
	PtfMissingHourTolerance     pgtype.Numeric
	DemandOverrunMultiplier     pgtype.Numeric
	MoneyRoundingMode           MoneyRoundingMode
	CreatedAt                   pgtype.Timestamptz
}

// Billing parameters (migration 00014): platform-wide, dated (R106). Enum
// arrays travel as text[]: pgx has no codec for arrays of custom enums.
func (q *Queries) BillingParametersEffective(ctx context.Context, effectiveOn pgtype.Date) (BillingParametersEffectiveRow, error) {
	row := q.db.QueryRow(ctx, billingParametersEffective, effectiveOn)
	var i BillingParametersEffectiveRow
	err := row.Scan(
		&i.EffectiveFrom,
		&i.ReactivePenaltyBasis,
		&i.ReactiveExemptBelowKw,
		&i.ReactiveExemptTerms,
		&i.ReactiveExemptUserGroups,
		&i.ReactiveGenerationExemptKwh,
		&i.ReactiveBands,
		&i.TieringGroups,
		&i.TieringMode,
		&i.TieringVoltageLevels,
		&i.TieringSupplyCompanies,
		&i.PtfMissingHourTolerance,
		&i.DemandOverrunMultiplier,
		&i.MoneyRoundingMode,
		&i.CreatedAt,
	)
	return i, err
}

const billingParametersList = `-- name: BillingParametersList :many
select effective_from, reactive_penalty_basis, reactive_exempt_below_kw,
  reactive_exempt_terms::text[] as reactive_exempt_terms,
  reactive_exempt_user_groups::text[] as reactive_exempt_user_groups,
  reactive_generation_exempt_kwh, reactive_bands, tiering_groups, tiering_mode,
  tiering_voltage_levels::text[] as tiering_voltage_levels,
  tiering_supply_companies::text[] as tiering_supply_companies,
  ptf_missing_hour_tolerance, demand_overrun_multiplier, money_rounding_mode, created_at
from billing_parameters
order by effective_from
`

type BillingParametersListRow struct {
	EffectiveFrom               pgtype.Date
	ReactivePenaltyBasis        ReactivePenaltyBasis
	ReactiveExemptBelowKw       pgtype.Numeric
	ReactiveExemptTerms         []string
	ReactiveExemptUserGroups    []string
	ReactiveGenerationExemptKwh pgtype.Numeric
	ReactiveBands               []byte
	TieringGroups               []byte
	TieringMode                 TieringMode
	TieringVoltageLevels        []string
	TieringSupplyCompanies      []string
	PtfMissingHourTolerance     pgtype.Numeric
	DemandOverrunMultiplier     pgtype.Numeric
	MoneyRoundingMode           MoneyRoundingMode
	CreatedAt                   pgtype.Timestamptz
}

func (q *Queries) BillingParametersList(ctx context.Context) ([]BillingParametersListRow, error) {
	rows, err := q.db.Query(ctx, billingParametersList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingParametersListRow
	for rows.Next() {
		var i BillingParametersListRow
		if err := rows.Scan(
			&i.EffectiveFrom,
			&i.ReactivePenaltyBasis,
			&i.ReactiveExemptBelowKw,
			&i.ReactiveExemptTerms,
			&i.ReactiveExemptUserGroups,
			&i.ReactiveGenerationExemptKwh,
			&i.ReactiveBands,
			&i.TieringGroups,
			&i.TieringMode,
			&i.TieringVoltageLevels,
			&i.TieringSupplyCompanies,
			&i.PtfMissingHourTolerance,
			&i.DemandOverrunMultiplier,
			&i.MoneyRoundingMode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
