// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bills.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const billCountVisibleAnalyzers = `-- name: BillCountVisibleAnalyzers :one
select count(*) from analyzers
where company_id = $1 and deleted_at is null
  and id = any($2::uuid[])
  and ($3::boolean or building_id = any($4::uuid[]))
`

type BillCountVisibleAnalyzersParams struct {
	CompanyID    uuid.UUID
	AnalyzerIds  []uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// BillCountVisibleAnalyzers checks that every analyzer id in a batch belongs
// to the Scope's company and one of its visible buildings, in one round
// trip: the caller compares the count to the distinct id count and refuses
// the whole write if they differ.
func (q *Queries) BillCountVisibleAnalyzers(ctx context.Context, arg BillCountVisibleAnalyzersParams) (int64, error) {
	row := q.db.QueryRow(ctx, billCountVisibleAnalyzers,
		arg.CompanyID,
		arg.AnalyzerIds,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const billCreate = `-- name: BillCreate :one
insert into bills (
  id, company_id, building_id, analyzer_id, scope, period_key, period_start, period_end,
  days_in_period, tariff_id, tariff_effective_from, active_import, t1_kwh, t2_kwh, t3_kwh,
  inductive_kvarh, capacitive_kvarh, active_export, net_consumption, low_tier_kwh, high_tier_kwh,
  max_demand_kw, tiered_applied, index_start, index_end, effective_energy_price, low_tier_price,
  high_tier_price, energy_cost, distribution_cost, green_energy_cost, power_cost,
  demand_overrun_cost, reactive_penalty, other_taxes_cost, vat_base, vat_cost, generation_credit,
  total_cost, inductive_ratio, capacitive_ratio, inductive_threshold, capacitive_threshold,
  reactive_penalty_applied, reactive_power_price, generation_usage, generation_price_per_kwh,
  ptf_yekdem_used, ptf_hours_matched, ptf_hours_missing, ptf_average, yekdem_used, status,
  flag_reason, pdf_path, computed_at, created_at, updated_at,
  currency, extra_charges_cost, demand_data_available, ptf_hours_expected, consumption_hours_missing
)
select
  gen_random_uuid(), $1, $2, $3,
  $4, $5, $6, $7,
  $8, $9, $10,
  $11, $12, $13, $14,
  $15, $16, $17,
  $18, $19, $20,
  $21, $22, $23, $24,
  $25, $26, $27,
  $28, $29, $30,
  $31, $32, $33,
  $34, $35, $36, $37,
  $38, $39, $40,
  $41, $42, $43,
  $44, $45, $46,
  $47, $48, $49,
  $50, $51, $52, $53,
  $54, $55, $56, $56,
  $57, $58, $59,
  $60, $61
where
  ($2::uuid is null or exists (
    select 1 from buildings b
    where b.id = $2 and b.company_id = $1 and b.deleted_at is null
      and ($62::boolean or b.id = any($63::uuid[]))
  ))
  and ($9::uuid is null or exists (
    select 1 from tariffs t
    where t.id = $9 and t.company_id = $1 and t.deleted_at is null
      and ($62::boolean or t.building_id is null or t.building_id = any($63::uuid[]))
  ))
  and ($3::uuid is null or exists (
    select 1 from analyzers an
    where an.id = $3 and an.company_id = $1 and an.deleted_at is null
      and ($62::boolean or an.building_id = any($63::uuid[]))
  ))
returning id, company_id, building_id, analyzer_id, scope, period_key, period_start, period_end, days_in_period, tariff_id, tariff_effective_from, active_import, t1_kwh, t2_kwh, t3_kwh, inductive_kvarh, capacitive_kvarh, active_export, net_consumption, low_tier_kwh, high_tier_kwh, max_demand_kw, tiered_applied, index_start, index_end, effective_energy_price, low_tier_price, high_tier_price, energy_cost, distribution_cost, green_energy_cost, power_cost, demand_overrun_cost, reactive_penalty, other_taxes_cost, vat_base, vat_cost, generation_credit, total_cost, inductive_ratio, capacitive_ratio, inductive_threshold, capacitive_threshold, reactive_penalty_applied, reactive_power_price, generation_usage, generation_price_per_kwh, ptf_yekdem_used, ptf_hours_matched, ptf_hours_missing, ptf_average, yekdem_used, status, flag_reason, pdf_path, computed_at, created_at, updated_at, currency, extra_charges_cost, demand_data_available, ptf_hours_expected, consumption_hours_missing
`

type BillCreateParams struct {
	CompanyID               uuid.UUID
	BuildingID              *uuid.UUID
	AnalyzerID              *uuid.UUID
	BillScope               BillScope
	PeriodKey               string
	PeriodStart             pgtype.Timestamptz
	PeriodEnd               pgtype.Timestamptz
	DaysInPeriod            int32
	TariffID                *uuid.UUID
	TariffEffectiveFrom     pgtype.Date
	ActiveImport            pgtype.Numeric
	T1Kwh                   pgtype.Numeric
	T2Kwh                   pgtype.Numeric
	T3Kwh                   pgtype.Numeric
	InductiveKvarh          pgtype.Numeric
	CapacitiveKvarh         pgtype.Numeric
	ActiveExport            pgtype.Numeric
	NetConsumption          pgtype.Numeric
	LowTierKwh              pgtype.Numeric
	HighTierKwh             pgtype.Numeric
	MaxDemandKw             pgtype.Numeric
	TieredApplied           bool
	IndexStart              []byte
	IndexEnd                []byte
	EffectiveEnergyPrice    pgtype.Numeric
	LowTierPrice            pgtype.Numeric
	HighTierPrice           pgtype.Numeric
	EnergyCost              pgtype.Numeric
	DistributionCost        pgtype.Numeric
	GreenEnergyCost         pgtype.Numeric
	PowerCost               pgtype.Numeric
	DemandOverrunCost       pgtype.Numeric
	ReactivePenalty         pgtype.Numeric
	OtherTaxesCost          pgtype.Numeric
	VatBase                 pgtype.Numeric
	VatCost                 pgtype.Numeric
	GenerationCredit        pgtype.Numeric
	TotalCost               pgtype.Numeric
	InductiveRatio          pgtype.Numeric
	CapacitiveRatio         pgtype.Numeric
	InductiveThreshold      pgtype.Numeric
	CapacitiveThreshold     pgtype.Numeric
	ReactivePenaltyApplied  bool
	ReactivePowerPrice      pgtype.Numeric
	GenerationUsage         GenerationUsage
	GenerationPricePerKwh   pgtype.Numeric
	PtfYekdemUsed           bool
	PtfHoursMatched         *int32
	PtfHoursMissing         *int32
	PtfAverage              pgtype.Numeric
	YekdemUsed              pgtype.Numeric
	Status                  BillStatus
	FlagReason              *string
	PdfPath                 *string
	ComputedAt              pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	Currency                CurrencyCode
	ExtraChargesCost        pgtype.Numeric
	DemandDataAvailable     bool
	PtfHoursExpected        *int32
	ConsumptionHoursMissing *int32
	AllBuildings            bool
	BuildingIds             []uuid.UUID
}

// Critical Finding 1 (task-11a fix round 1): building_id is a stored foreign
// key and MUST be validated in SQL — Scope.AllowsBuilding cannot know which
// company owns a building, so the Go-side billBuildingWritable pre-check is
// not sufficient on its own. Important Finding 4: tariff_id is a stored
// foreign key too (bills.tariff_id references tariffs), validated the same
// way TariffVisible validates a tariff for this Scope, INCLUDING the
// company-wide (building_id is null) case — a narrow Scope may reference the
// company-wide tariff Effective can already resolve for it.
//
// F1 final review pass A, Important Finding 1 (fix round): bills.analyzer_id
// is a stored foreign key too, and was previously validated ONLY by the
// Go-side requireAnalyzersVisible pre-check, run on r.pool before
// r.pool.Begin — unlocked, outside the transaction, and (per binding ruling
// 2/3) not a sufficient guard on its own. The exists clause below re-checks
// it here, atomically, exactly like building_id and tariff_id above: the
// same company, not soft-deleted, and visible to the Scope's building
// branch. requireAnalyzersVisible stays as a fast pre-check / friendly
// error, now defence in depth rather than the only guard.
func (q *Queries) BillCreate(ctx context.Context, arg BillCreateParams) (Bill, error) {
	row := q.db.QueryRow(ctx, billCreate,
		arg.CompanyID,
		arg.BuildingID,
		arg.AnalyzerID,
		arg.BillScope,
		arg.PeriodKey,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.DaysInPeriod,
		arg.TariffID,
		arg.TariffEffectiveFrom,
		arg.ActiveImport,
		arg.T1Kwh,
		arg.T2Kwh,
		arg.T3Kwh,
		arg.InductiveKvarh,
		arg.CapacitiveKvarh,
		arg.ActiveExport,
		arg.NetConsumption,
		arg.LowTierKwh,
		arg.HighTierKwh,
		arg.MaxDemandKw,
		arg.TieredApplied,
		arg.IndexStart,
		arg.IndexEnd,
		arg.EffectiveEnergyPrice,
		arg.LowTierPrice,
		arg.HighTierPrice,
		arg.EnergyCost,
		arg.DistributionCost,
		arg.GreenEnergyCost,
		arg.PowerCost,
		arg.DemandOverrunCost,
		arg.ReactivePenalty,
		arg.OtherTaxesCost,
		arg.VatBase,
		arg.VatCost,
		arg.GenerationCredit,
		arg.TotalCost,
		arg.InductiveRatio,
		arg.CapacitiveRatio,
		arg.InductiveThreshold,
		arg.CapacitiveThreshold,
		arg.ReactivePenaltyApplied,
		arg.ReactivePowerPrice,
		arg.GenerationUsage,
		arg.GenerationPricePerKwh,
		arg.PtfYekdemUsed,
		arg.PtfHoursMatched,
		arg.PtfHoursMissing,
		arg.PtfAverage,
		arg.YekdemUsed,
		arg.Status,
		arg.FlagReason,
		arg.PdfPath,
		arg.ComputedAt,
		arg.CreatedAt,
		arg.Currency,
		arg.ExtraChargesCost,
		arg.DemandDataAvailable,
		arg.PtfHoursExpected,
		arg.ConsumptionHoursMissing,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.AnalyzerID,
		&i.Scope,
		&i.PeriodKey,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.DaysInPeriod,
		&i.TariffID,
		&i.TariffEffectiveFrom,
		&i.ActiveImport,
		&i.T1Kwh,
		&i.T2Kwh,
		&i.T3Kwh,
		&i.InductiveKvarh,
		&i.CapacitiveKvarh,
		&i.ActiveExport,
		&i.NetConsumption,
		&i.LowTierKwh,
		&i.HighTierKwh,
		&i.MaxDemandKw,
		&i.TieredApplied,
		&i.IndexStart,
		&i.IndexEnd,
		&i.EffectiveEnergyPrice,
		&i.LowTierPrice,
		&i.HighTierPrice,
		&i.EnergyCost,
		&i.DistributionCost,
		&i.GreenEnergyCost,
		&i.PowerCost,
		&i.DemandOverrunCost,
		&i.ReactivePenalty,
		&i.OtherTaxesCost,
		&i.VatBase,
		&i.VatCost,
		&i.GenerationCredit,
		&i.TotalCost,
		&i.InductiveRatio,
		&i.CapacitiveRatio,
		&i.InductiveThreshold,
		&i.CapacitiveThreshold,
		&i.ReactivePenaltyApplied,
		&i.ReactivePowerPrice,
		&i.GenerationUsage,
		&i.GenerationPricePerKwh,
		&i.PtfYekdemUsed,
		&i.PtfHoursMatched,
		&i.PtfHoursMissing,
		&i.PtfAverage,
		&i.YekdemUsed,
		&i.Status,
		&i.FlagReason,
		&i.PdfPath,
		&i.ComputedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Currency,
		&i.ExtraChargesCost,
		&i.DemandDataAvailable,
		&i.PtfHoursExpected,
		&i.ConsumptionHoursMissing,
	)
	return i, err
}

const billCurrent = `-- name: BillCurrent :one
select id, company_id, building_id, analyzer_id, scope, period_key, period_start, period_end, days_in_period, tariff_id, tariff_effective_from, active_import, t1_kwh, t2_kwh, t3_kwh, inductive_kvarh, capacitive_kvarh, active_export, net_consumption, low_tier_kwh, high_tier_kwh, max_demand_kw, tiered_applied, index_start, index_end, effective_energy_price, low_tier_price, high_tier_price, energy_cost, distribution_cost, green_energy_cost, power_cost, demand_overrun_cost, reactive_penalty, other_taxes_cost, vat_base, vat_cost, generation_credit, total_cost, inductive_ratio, capacitive_ratio, inductive_threshold, capacitive_threshold, reactive_penalty_applied, reactive_power_price, generation_usage, generation_price_per_kwh, ptf_yekdem_used, ptf_hours_matched, ptf_hours_missing, ptf_average, yekdem_used, status, flag_reason, pdf_path, computed_at, created_at, updated_at, currency, extra_charges_cost, demand_data_available, ptf_hours_expected, consumption_hours_missing from bills
where bills.company_id = $1
  and ($2::boolean or bills.building_id = any($3::uuid[]))
  and bills.scope = $4
  and coalesce(bills.analyzer_id, bills.building_id, bills.company_id) = $5
  and bills.period_key = $6
  and bills.status <> 'superseded'
  and (bills.building_id is null or exists (select 1 from buildings b where b.id = bills.building_id and b.deleted_at is null))
`

type BillCurrentParams struct {
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
	BillScope    BillScope
	SubjectID    *uuid.UUID
	PeriodKey    string
}

func (q *Queries) BillCurrent(ctx context.Context, arg BillCurrentParams) (Bill, error) {
	row := q.db.QueryRow(ctx, billCurrent,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
		arg.BillScope,
		arg.SubjectID,
		arg.PeriodKey,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.AnalyzerID,
		&i.Scope,
		&i.PeriodKey,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.DaysInPeriod,
		&i.TariffID,
		&i.TariffEffectiveFrom,
		&i.ActiveImport,
		&i.T1Kwh,
		&i.T2Kwh,
		&i.T3Kwh,
		&i.InductiveKvarh,
		&i.CapacitiveKvarh,
		&i.ActiveExport,
		&i.NetConsumption,
		&i.LowTierKwh,
		&i.HighTierKwh,
		&i.MaxDemandKw,
		&i.TieredApplied,
		&i.IndexStart,
		&i.IndexEnd,
		&i.EffectiveEnergyPrice,
		&i.LowTierPrice,
		&i.HighTierPrice,
		&i.EnergyCost,
		&i.DistributionCost,
		&i.GreenEnergyCost,
		&i.PowerCost,
		&i.DemandOverrunCost,
		&i.ReactivePenalty,
		&i.OtherTaxesCost,
		&i.VatBase,
		&i.VatCost,
		&i.GenerationCredit,
		&i.TotalCost,
		&i.InductiveRatio,
		&i.CapacitiveRatio,
		&i.InductiveThreshold,
		&i.CapacitiveThreshold,
		&i.ReactivePenaltyApplied,
		&i.ReactivePowerPrice,
		&i.GenerationUsage,
		&i.GenerationPricePerKwh,
		&i.PtfYekdemUsed,
		&i.PtfHoursMatched,
		&i.PtfHoursMissing,
		&i.PtfAverage,
		&i.YekdemUsed,
		&i.Status,
		&i.FlagReason,
		&i.PdfPath,
		&i.ComputedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Currency,
		&i.ExtraChargesCost,
		&i.DemandDataAvailable,
		&i.PtfHoursExpected,
		&i.ConsumptionHoursMissing,
	)
	return i, err
}

const billGet = `-- name: BillGet :one

select id, company_id, building_id, analyzer_id, scope, period_key, period_start, period_end, days_in_period, tariff_id, tariff_effective_from, active_import, t1_kwh, t2_kwh, t3_kwh, inductive_kvarh, capacitive_kvarh, active_export, net_consumption, low_tier_kwh, high_tier_kwh, max_demand_kw, tiered_applied, index_start, index_end, effective_energy_price, low_tier_price, high_tier_price, energy_cost, distribution_cost, green_energy_cost, power_cost, demand_overrun_cost, reactive_penalty, other_taxes_cost, vat_base, vat_cost, generation_credit, total_cost, inductive_ratio, capacitive_ratio, inductive_threshold, capacitive_threshold, reactive_penalty_applied, reactive_power_price, generation_usage, generation_price_per_kwh, ptf_yekdem_used, ptf_hours_matched, ptf_hours_missing, ptf_average, yekdem_used, status, flag_reason, pdf_path, computed_at, created_at, updated_at, currency, extra_charges_cost, demand_data_available, ptf_hours_expected, consumption_hours_missing from bills
where bills.id = $1 and bills.company_id = $2
  and ($3::boolean or bills.building_id = any($4::uuid[]))
  and (bills.building_id is null or exists (select 1 from buildings b where b.id = bills.building_id and b.deleted_at is null))
`

type BillGetParams struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// Bills, bill lines, bill members and bill hourly detail (migration 00009).
// Query names are prefixed Bill…
// Folded minor (fix round 1): a bill of a soft-deleted building must not
// stay readable through the bill's own row — Get/List both exclude it.
func (q *Queries) BillGet(ctx context.Context, arg BillGetParams) (Bill, error) {
	row := q.db.QueryRow(ctx, billGet,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.AnalyzerID,
		&i.Scope,
		&i.PeriodKey,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.DaysInPeriod,
		&i.TariffID,
		&i.TariffEffectiveFrom,
		&i.ActiveImport,
		&i.T1Kwh,
		&i.T2Kwh,
		&i.T3Kwh,
		&i.InductiveKvarh,
		&i.CapacitiveKvarh,
		&i.ActiveExport,
		&i.NetConsumption,
		&i.LowTierKwh,
		&i.HighTierKwh,
		&i.MaxDemandKw,
		&i.TieredApplied,
		&i.IndexStart,
		&i.IndexEnd,
		&i.EffectiveEnergyPrice,
		&i.LowTierPrice,
		&i.HighTierPrice,
		&i.EnergyCost,
		&i.DistributionCost,
		&i.GreenEnergyCost,
		&i.PowerCost,
		&i.DemandOverrunCost,
		&i.ReactivePenalty,
		&i.OtherTaxesCost,
		&i.VatBase,
		&i.VatCost,
		&i.GenerationCredit,
		&i.TotalCost,
		&i.InductiveRatio,
		&i.CapacitiveRatio,
		&i.InductiveThreshold,
		&i.CapacitiveThreshold,
		&i.ReactivePenaltyApplied,
		&i.ReactivePowerPrice,
		&i.GenerationUsage,
		&i.GenerationPricePerKwh,
		&i.PtfYekdemUsed,
		&i.PtfHoursMatched,
		&i.PtfHoursMissing,
		&i.PtfAverage,
		&i.YekdemUsed,
		&i.Status,
		&i.FlagReason,
		&i.PdfPath,
		&i.ComputedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Currency,
		&i.ExtraChargesCost,
		&i.DemandDataAvailable,
		&i.PtfHoursExpected,
		&i.ConsumptionHoursMissing,
	)
	return i, err
}

const billHourlyDetailDeleteForBill = `-- name: BillHourlyDetailDeleteForBill :exec
delete from bill_hourly_detail
where bill_id = $1
  and exists (
    select 1 from bills b where b.id = $1 and b.company_id = $2
      and ($3::boolean or b.building_id = any($4::uuid[]))
  )
`

type BillHourlyDetailDeleteForBillParams struct {
	BillID       uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) BillHourlyDetailDeleteForBill(ctx context.Context, arg BillHourlyDetailDeleteForBillParams) error {
	_, err := q.db.Exec(ctx, billHourlyDetailDeleteForBill,
		arg.BillID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	return err
}

const billHourlyDetailInsert = `-- name: BillHourlyDetailInsert :one
insert into bill_hourly_detail (bill_id, ts, consumption, ptf, yekdem, kbk, unit_price, cost)
select $1, $2, $3, $4, $5,
       $6, $7, $8
where exists (
  select 1 from bills b where b.id = $1 and b.company_id = $9
    and ($10::boolean or b.building_id = any($11::uuid[]))
)
returning true
`

type BillHourlyDetailInsertParams struct {
	BillID       uuid.UUID
	Ts           pgtype.Timestamptz
	Consumption  pgtype.Numeric
	Ptf          pgtype.Numeric
	Yekdem       pgtype.Numeric
	Kbk          pgtype.Numeric
	UnitPrice    pgtype.Numeric
	Cost         pgtype.Numeric
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// :one RETURNING true, not :exec: see AlarmAnalyzerInsert's comment in
// queries/alarms.sql -- an :exec insert whose WHERE EXISTS excludes every
// row still reports "no error", which a caller checking only err would read
// as success. Task 11a fix round 2: this was the one sibling
// (AlarmAnalyzerInsert/AlarmChannelInsert/BillMemberInsert were already
// converted in fix round 1) left as :exec, so a bill belonging to another
// tenant's company still looked like a successful insert while storing zero
// rows.
func (q *Queries) BillHourlyDetailInsert(ctx context.Context, arg BillHourlyDetailInsertParams) (bool, error) {
	row := q.db.QueryRow(ctx, billHourlyDetailInsert,
		arg.BillID,
		arg.Ts,
		arg.Consumption,
		arg.Ptf,
		arg.Yekdem,
		arg.Kbk,
		arg.UnitPrice,
		arg.Cost,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const billHourlyDetailList = `-- name: BillHourlyDetailList :many
select bhd.bill_id, bhd.ts, bhd.consumption, bhd.ptf, bhd.yekdem, bhd.kbk, bhd.unit_price, bhd.cost from bill_hourly_detail bhd
where bhd.bill_id = $1
  and exists (
    select 1 from bills b where b.id = bhd.bill_id and b.company_id = $2
      and ($3::boolean or b.building_id = any($4::uuid[]))
  )
order by bhd.ts
`

type BillHourlyDetailListParams struct {
	BillID       uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) BillHourlyDetailList(ctx context.Context, arg BillHourlyDetailListParams) ([]BillHourlyDetail, error) {
	rows, err := q.db.Query(ctx, billHourlyDetailList,
		arg.BillID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillHourlyDetail
	for rows.Next() {
		var i BillHourlyDetail
		if err := rows.Scan(
			&i.BillID,
			&i.Ts,
			&i.Consumption,
			&i.Ptf,
			&i.Yekdem,
			&i.Kbk,
			&i.UnitPrice,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billLineInsert = `-- name: BillLineInsert :one
insert into bill_lines (id, bill_id, code, label, quantity, unit, unit_price, rate_pct, amount, sort_order)
select gen_random_uuid(), $1, $2, $3, $4,
       $5, $6, $7, $8, $9
where exists (
  select 1 from bills bl where bl.id = $1 and bl.company_id = $10
    and ($11::boolean or bl.building_id = any($12::uuid[]))
)
returning id, bill_id, code, label, quantity, unit, unit_price, rate_pct, amount, sort_order
`

type BillLineInsertParams struct {
	BillID       uuid.UUID
	Code         string
	Label        string
	Quantity     pgtype.Numeric
	Unit         *string
	UnitPrice    pgtype.Numeric
	RatePct      pgtype.Numeric
	Amount       pgtype.Numeric
	SortOrder    int16
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// Important Finding 1: bill_lines has no company_id of its own — join
// through bills. BillLineInsert re-validates bill_id against the Scope
// itself, so the isolation boundary holds even if the Go-side requireVisible
// pre-check (in BillRepository.requireVisible, run before the transaction
// Create/Supersede/ReplaceHourlyDetail open) were ever skipped.
func (q *Queries) BillLineInsert(ctx context.Context, arg BillLineInsertParams) (BillLine, error) {
	row := q.db.QueryRow(ctx, billLineInsert,
		arg.BillID,
		arg.Code,
		arg.Label,
		arg.Quantity,
		arg.Unit,
		arg.UnitPrice,
		arg.RatePct,
		arg.Amount,
		arg.SortOrder,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i BillLine
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.Code,
		&i.Label,
		&i.Quantity,
		&i.Unit,
		&i.UnitPrice,
		&i.RatePct,
		&i.Amount,
		&i.SortOrder,
	)
	return i, err
}

const billLineList = `-- name: BillLineList :many
select bl.id, bl.bill_id, bl.code, bl.label, bl.quantity, bl.unit, bl.unit_price, bl.rate_pct, bl.amount, bl.sort_order from bill_lines bl
where bl.bill_id = $1
  and exists (
    select 1 from bills b where b.id = bl.bill_id and b.company_id = $2
      and ($3::boolean or b.building_id = any($4::uuid[]))
  )
order by bl.sort_order, bl.id
`

type BillLineListParams struct {
	BillID       uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) BillLineList(ctx context.Context, arg BillLineListParams) ([]BillLine, error) {
	rows, err := q.db.Query(ctx, billLineList,
		arg.BillID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillLine
	for rows.Next() {
		var i BillLine
		if err := rows.Scan(
			&i.ID,
			&i.BillID,
			&i.Code,
			&i.Label,
			&i.Quantity,
			&i.Unit,
			&i.UnitPrice,
			&i.RatePct,
			&i.Amount,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billList = `-- name: BillList :many
select id, company_id, building_id, analyzer_id, scope, period_key, period_start, period_end, days_in_period, tariff_id, tariff_effective_from, active_import, t1_kwh, t2_kwh, t3_kwh, inductive_kvarh, capacitive_kvarh, active_export, net_consumption, low_tier_kwh, high_tier_kwh, max_demand_kw, tiered_applied, index_start, index_end, effective_energy_price, low_tier_price, high_tier_price, energy_cost, distribution_cost, green_energy_cost, power_cost, demand_overrun_cost, reactive_penalty, other_taxes_cost, vat_base, vat_cost, generation_credit, total_cost, inductive_ratio, capacitive_ratio, inductive_threshold, capacitive_threshold, reactive_penalty_applied, reactive_power_price, generation_usage, generation_price_per_kwh, ptf_yekdem_used, ptf_hours_matched, ptf_hours_missing, ptf_average, yekdem_used, status, flag_reason, pdf_path, computed_at, created_at, updated_at, currency, extra_charges_cost, demand_data_available, ptf_hours_expected, consumption_hours_missing from bills
where bills.company_id = $1
  and ($2::boolean or bills.building_id = any($3::uuid[]))
  and (cardinality($4::uuid[]) = 0 or bills.id = any($4::uuid[]))
  and ($5::uuid is null or bills.building_id = $5)
  and ($6::uuid is null or bills.analyzer_id = $6)
  and ($7::bill_scope is null or bills.scope = $7)
  and ($8::text is null or bills.period_key = $8)
  -- Statuses is compared as text[], not bill_status[]: pgx has no codec
  -- for an array of this custom enum, and fails even on an empty slice.
  and (cardinality($9::text[]) = 0 or bills.status::text = any($9::text[]))
  and ($10::boolean or bills.status <> 'superseded')
  and (bills.building_id is null or exists (select 1 from buildings b where b.id = bills.building_id and b.deleted_at is null))
order by bills.period_key desc, bills.id
limit $12 offset $11
`

type BillListParams struct {
	CompanyID         uuid.UUID
	AllBuildings      bool
	BuildingIds       []uuid.UUID
	Ids               []uuid.UUID
	BuildingID        *uuid.UUID
	AnalyzerID        *uuid.UUID
	BillScope         NullBillScope
	PeriodKey         *string
	Statuses          []string
	IncludeSuperseded bool
	OffsetVal         int32
	LimitVal          int32
}

func (q *Queries) BillList(ctx context.Context, arg BillListParams) ([]Bill, error) {
	rows, err := q.db.Query(ctx, billList,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
		arg.Ids,
		arg.BuildingID,
		arg.AnalyzerID,
		arg.BillScope,
		arg.PeriodKey,
		arg.Statuses,
		arg.IncludeSuperseded,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bill
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BuildingID,
			&i.AnalyzerID,
			&i.Scope,
			&i.PeriodKey,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.DaysInPeriod,
			&i.TariffID,
			&i.TariffEffectiveFrom,
			&i.ActiveImport,
			&i.T1Kwh,
			&i.T2Kwh,
			&i.T3Kwh,
			&i.InductiveKvarh,
			&i.CapacitiveKvarh,
			&i.ActiveExport,
			&i.NetConsumption,
			&i.LowTierKwh,
			&i.HighTierKwh,
			&i.MaxDemandKw,
			&i.TieredApplied,
			&i.IndexStart,
			&i.IndexEnd,
			&i.EffectiveEnergyPrice,
			&i.LowTierPrice,
			&i.HighTierPrice,
			&i.EnergyCost,
			&i.DistributionCost,
			&i.GreenEnergyCost,
			&i.PowerCost,
			&i.DemandOverrunCost,
			&i.ReactivePenalty,
			&i.OtherTaxesCost,
			&i.VatBase,
			&i.VatCost,
			&i.GenerationCredit,
			&i.TotalCost,
			&i.InductiveRatio,
			&i.CapacitiveRatio,
			&i.InductiveThreshold,
			&i.CapacitiveThreshold,
			&i.ReactivePenaltyApplied,
			&i.ReactivePowerPrice,
			&i.GenerationUsage,
			&i.GenerationPricePerKwh,
			&i.PtfYekdemUsed,
			&i.PtfHoursMatched,
			&i.PtfHoursMissing,
			&i.PtfAverage,
			&i.YekdemUsed,
			&i.Status,
			&i.FlagReason,
			&i.PdfPath,
			&i.ComputedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Currency,
			&i.ExtraChargesCost,
			&i.DemandDataAvailable,
			&i.PtfHoursExpected,
			&i.ConsumptionHoursMissing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billMarkSuperseded = `-- name: BillMarkSuperseded :one
update bills set status = 'superseded', updated_at = $1
where id = $2 and company_id = $3
  and ($4::boolean or building_id = any($5::uuid[]))
  and status <> 'superseded'
returning scope, coalesce(analyzer_id, building_id, company_id) as subject_id, period_key
`

type BillMarkSupersededParams struct {
	UpdatedAt    pgtype.Timestamptz
	ID           uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

type BillMarkSupersededRow struct {
	Scope     BillScope
	SubjectID uuid.UUID
	PeriodKey string
}

// Supersede's replacement-vs-original check (folded minor, fix round 1):
// returning the marked bill's own scope, subject and period lets the Go
// caller refuse a Supersede whose replacement names a different one, instead
// of silently letting one bill's history point at another's.
func (q *Queries) BillMarkSuperseded(ctx context.Context, arg BillMarkSupersededParams) (BillMarkSupersededRow, error) {
	row := q.db.QueryRow(ctx, billMarkSuperseded,
		arg.UpdatedAt,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i BillMarkSupersededRow
	err := row.Scan(&i.Scope, &i.SubjectID, &i.PeriodKey)
	return i, err
}

const billMemberInsert = `-- name: BillMemberInsert :one
insert into bill_members (bill_id, analyzer_id)
select $1, $2
where exists (
  select 1 from bills bl where bl.id = $1 and bl.company_id = $3
    and ($4::boolean or bl.building_id = any($5::uuid[]))
)
and exists (
  select 1 from analyzers an
  where an.id = $2 and an.company_id = $3 and an.deleted_at is null
    and ($4::boolean or an.building_id = any($5::uuid[]))
)
returning true
`

type BillMemberInsertParams struct {
	BillID       uuid.UUID
	AnalyzerID   uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// :one RETURNING true, not :exec: see AlarmAnalyzerInsert's comment in
// queries/alarms.sql -- an :exec insert whose WHERE EXISTS excludes every
// row still reports "no error", which a caller checking only err would read
// as success.
//
// F1 final review pass A, Important Finding 1 (fix round): the member's OWN
// analyzer_id is a stored foreign key (bill_members.analyzer_id references
// analyzers) and was previously validated only by the bill-level Go
// pre-check; this exists clause re-checks it here, atomically, the same way
// BillCreate's analyzer_id clause does.
func (q *Queries) BillMemberInsert(ctx context.Context, arg BillMemberInsertParams) (bool, error) {
	row := q.db.QueryRow(ctx, billMemberInsert,
		arg.BillID,
		arg.AnalyzerID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const billMemberList = `-- name: BillMemberList :many
select bm.bill_id, bm.analyzer_id from bill_members bm
where bm.bill_id = $1
  and exists (
    select 1 from bills b where b.id = bm.bill_id and b.company_id = $2
      and ($3::boolean or b.building_id = any($4::uuid[]))
  )
order by bm.analyzer_id
`

type BillMemberListParams struct {
	BillID       uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) BillMemberList(ctx context.Context, arg BillMemberListParams) ([]BillMember, error) {
	rows, err := q.db.Query(ctx, billMemberList,
		arg.BillID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillMember
	for rows.Next() {
		var i BillMember
		if err := rows.Scan(&i.BillID, &i.AnalyzerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billSetPDFPath = `-- name: BillSetPDFPath :execrows
update bills set pdf_path = $1, updated_at = now()
where id = $2 and company_id = $3
  and ($4::boolean or building_id = any($5::uuid[]))
`

type BillSetPDFPathParams struct {
	PdfPath      *string
	ID           uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) BillSetPDFPath(ctx context.Context, arg BillSetPDFPathParams) (int64, error) {
	result, err := q.db.Exec(ctx, billSetPDFPath,
		arg.PdfPath,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const billUpdateStatus = `-- name: BillUpdateStatus :one
update bills set status = $1, flag_reason = $2, updated_at = $3
where id = $4 and company_id = $5
  and ($6::boolean or building_id = any($7::uuid[]))
  and status <> 'superseded'
returning id, company_id, building_id, analyzer_id, scope, period_key, period_start, period_end, days_in_period, tariff_id, tariff_effective_from, active_import, t1_kwh, t2_kwh, t3_kwh, inductive_kvarh, capacitive_kvarh, active_export, net_consumption, low_tier_kwh, high_tier_kwh, max_demand_kw, tiered_applied, index_start, index_end, effective_energy_price, low_tier_price, high_tier_price, energy_cost, distribution_cost, green_energy_cost, power_cost, demand_overrun_cost, reactive_penalty, other_taxes_cost, vat_base, vat_cost, generation_credit, total_cost, inductive_ratio, capacitive_ratio, inductive_threshold, capacitive_threshold, reactive_penalty_applied, reactive_power_price, generation_usage, generation_price_per_kwh, ptf_yekdem_used, ptf_hours_matched, ptf_hours_missing, ptf_average, yekdem_used, status, flag_reason, pdf_path, computed_at, created_at, updated_at, currency, extra_charges_cost, demand_data_available, ptf_hours_expected, consumption_hours_missing
`

type BillUpdateStatusParams struct {
	Status       BillStatus
	FlagReason   *string
	UpdatedAt    pgtype.Timestamptz
	ID           uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// Folded minor: a superseded bill is a closed record — UpdateStatus must not
// be able to move it to draft/issued/flagged after the fact, only Supersede
// may act on it again (by inserting a new replacement).
func (q *Queries) BillUpdateStatus(ctx context.Context, arg BillUpdateStatusParams) (Bill, error) {
	row := q.db.QueryRow(ctx, billUpdateStatus,
		arg.Status,
		arg.FlagReason,
		arg.UpdatedAt,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.AnalyzerID,
		&i.Scope,
		&i.PeriodKey,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.DaysInPeriod,
		&i.TariffID,
		&i.TariffEffectiveFrom,
		&i.ActiveImport,
		&i.T1Kwh,
		&i.T2Kwh,
		&i.T3Kwh,
		&i.InductiveKvarh,
		&i.CapacitiveKvarh,
		&i.ActiveExport,
		&i.NetConsumption,
		&i.LowTierKwh,
		&i.HighTierKwh,
		&i.MaxDemandKw,
		&i.TieredApplied,
		&i.IndexStart,
		&i.IndexEnd,
		&i.EffectiveEnergyPrice,
		&i.LowTierPrice,
		&i.HighTierPrice,
		&i.EnergyCost,
		&i.DistributionCost,
		&i.GreenEnergyCost,
		&i.PowerCost,
		&i.DemandOverrunCost,
		&i.ReactivePenalty,
		&i.OtherTaxesCost,
		&i.VatBase,
		&i.VatCost,
		&i.GenerationCredit,
		&i.TotalCost,
		&i.InductiveRatio,
		&i.CapacitiveRatio,
		&i.InductiveThreshold,
		&i.CapacitiveThreshold,
		&i.ReactivePenaltyApplied,
		&i.ReactivePowerPrice,
		&i.GenerationUsage,
		&i.GenerationPricePerKwh,
		&i.PtfYekdemUsed,
		&i.PtfHoursMatched,
		&i.PtfHoursMissing,
		&i.PtfAverage,
		&i.YekdemUsed,
		&i.Status,
		&i.FlagReason,
		&i.PdfPath,
		&i.ComputedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Currency,
		&i.ExtraChargesCost,
		&i.DemandDataAvailable,
		&i.PtfHoursExpected,
		&i.ConsumptionHoursMissing,
	)
	return i, err
}

const billVisible = `-- name: BillVisible :one
select exists (
  select 1 from bills
  where id = $1 and company_id = $2
    and ($3::boolean or building_id = any($4::uuid[]))
) as visible
`

type BillVisibleParams struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) BillVisible(ctx context.Context, arg BillVisibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, billVisible,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var visible bool
	err := row.Scan(&visible)
	return visible, err
}
