// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buildings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBuilding = `-- name: GetBuilding :one
select id, company_id, name, address, latitude, longitude, floors, personnel_count, total_area_m2, sector, responsible_user_id, bill_cutoff_day, created_at, updated_at, deleted_at from buildings
where id = $1 and company_id = $2 and deleted_at is null
`

type GetBuildingParams struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
}

func (q *Queries) GetBuilding(ctx context.Context, arg GetBuildingParams) (Building, error) {
	row := q.db.QueryRow(ctx, getBuilding, arg.ID, arg.CompanyID)
	var i Building
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Floors,
		&i.PersonnelCount,
		&i.TotalAreaM2,
		&i.Sector,
		&i.ResponsibleUserID,
		&i.BillCutoffDay,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBuildingsForScope = `-- name: ListBuildingsForScope :many
select id, company_id, name, address, latitude, longitude, floors, personnel_count, total_area_m2, sector, responsible_user_id, bill_cutoff_day, created_at, updated_at, deleted_at from buildings
where company_id = $1
  and ($2::boolean or id = any($3::uuid[]))
  and deleted_at is null
order by name
`

type ListBuildingsForScopeParams struct {
	CompanyID    pgtype.UUID
	AllBuildings bool
	BuildingIds  []pgtype.UUID
}

func (q *Queries) ListBuildingsForScope(ctx context.Context, arg ListBuildingsForScopeParams) ([]Building, error) {
	rows, err := q.db.Query(ctx, listBuildingsForScope, arg.CompanyID, arg.AllBuildings, arg.BuildingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Building
	for rows.Next() {
		var i Building
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Floors,
			&i.PersonnelCount,
			&i.TotalAreaM2,
			&i.Sector,
			&i.ResponsibleUserID,
			&i.BillCutoffDay,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
