// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const calendarCreateEvent = `-- name: CalendarCreateEvent :one
insert into calendar_events (id, company_id, title, starts_at, ends_at, all_day, colour, created_by)
select
    coalesce(nullif($1::uuid, '00000000-0000-0000-0000-000000000000'::uuid),
             gen_random_uuid()),
    $2::uuid, $3, $4::timestamptz,
    $5::timestamptz, $6::boolean, $7::text,
    $8::uuid
where (
    $8::uuid is null
    or exists (
        select 1 from users u
        where u.id = $8::uuid
          and u.company_id = $2::uuid
          and u.deleted_at is null
    )
)
returning id, company_id, title, starts_at, ends_at, all_day, colour, created_by, created_at
`

type CalendarCreateEventParams struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
	Title     string
	StartsAt  pgtype.Timestamptz
	EndsAt    pgtype.Timestamptz
	AllDay    bool
	Colour    *string
	CreatedBy *uuid.UUID
}

// created_by, when set, must name a user of company_id: the `is null or
// exists (...)` clause makes that atomic with the insert, rather than a
// separate check-then-insert (R1: stored foreign keys are validated in SQL,
// never via Scope.AllowsBuilding or a Go-side pre-check).
func (q *Queries) CalendarCreateEvent(ctx context.Context, arg CalendarCreateEventParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, calendarCreateEvent,
		arg.ID,
		arg.CompanyID,
		arg.Title,
		arg.StartsAt,
		arg.EndsAt,
		arg.AllDay,
		arg.Colour,
		arg.CreatedBy,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.Colour,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const calendarCreateVacation = `-- name: CalendarCreateVacation :one
insert into company_vacations (id, company_id, start_date, end_date, description)
values (
    coalesce(nullif($1::uuid, '00000000-0000-0000-0000-000000000000'::uuid),
             gen_random_uuid()),
    $2::uuid, $3::date, $4::date,
    $5::text
)
returning id, company_id, start_date, end_date, description
`

type CalendarCreateVacationParams struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Description *string
}

func (q *Queries) CalendarCreateVacation(ctx context.Context, arg CalendarCreateVacationParams) (CompanyVacation, error) {
	row := q.db.QueryRow(ctx, calendarCreateVacation,
		arg.ID,
		arg.CompanyID,
		arg.StartDate,
		arg.EndDate,
		arg.Description,
	)
	var i CompanyVacation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.StartDate,
		&i.EndDate,
		&i.Description,
	)
	return i, err
}

const calendarDeleteEvent = `-- name: CalendarDeleteEvent :execrows
delete from calendar_events where id = $1 and company_id = $2
`

type CalendarDeleteEventParams struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) CalendarDeleteEvent(ctx context.Context, arg CalendarDeleteEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, calendarDeleteEvent, arg.ID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const calendarDeleteVacation = `-- name: CalendarDeleteVacation :execrows
delete from company_vacations where id = $1 and company_id = $2
`

type CalendarDeleteVacationParams struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) CalendarDeleteVacation(ctx context.Context, arg CalendarDeleteVacationParams) (int64, error) {
	result, err := q.db.Exec(ctx, calendarDeleteVacation, arg.ID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const calendarDeleteWeekendDays = `-- name: CalendarDeleteWeekendDays :exec
delete from company_weekend_days where company_id = $1
`

func (q *Queries) CalendarDeleteWeekendDays(ctx context.Context, companyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, calendarDeleteWeekendDays, companyID)
	return err
}

const calendarGetEvent = `-- name: CalendarGetEvent :one

select id, company_id, title, starts_at, ends_at, all_day, colour, created_by, created_at from calendar_events where id = $1 and company_id = $2
`

type CalendarGetEventParams struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
}

// Calendar, weekend-day and vacation repository queries (migration 00008).
// Owned by Task 11c.
//
// calendar_events, company_weekend_days and company_vacations all carry
// company_id directly and have no building_id at all (like stored_files), so
// every query below scopes to company_id alone -- there is no building set to
// intersect against.
func (q *Queries) CalendarGetEvent(ctx context.Context, arg CalendarGetEventParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, calendarGetEvent, arg.ID, arg.CompanyID)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.Colour,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const calendarInsertWeekendDays = `-- name: CalendarInsertWeekendDays :exec
insert into company_weekend_days (company_id, day_of_week)
select $1::uuid, d
from unnest($2::smallint[]) as d
on conflict (company_id, day_of_week) do nothing
`

type CalendarInsertWeekendDaysParams struct {
	CompanyID uuid.UUID
	Days      []int16
}

// CalendarInsertWeekendDays is ReplaceWeekendDays' insert half, always run in
// the same transaction right after CalendarDeleteWeekendDays clears the
// company's current set (CalendarRepository.inTx). `on conflict do nothing`
// absorbs a caller-supplied duplicate day rather than rejecting it: the
// method replaces a SET of weekend days, and two copies of the same day are
// not meaningfully different from that day named once.
func (q *Queries) CalendarInsertWeekendDays(ctx context.Context, arg CalendarInsertWeekendDaysParams) error {
	_, err := q.db.Exec(ctx, calendarInsertWeekendDays, arg.CompanyID, arg.Days)
	return err
}

const calendarListEvents = `-- name: CalendarListEvents :many
select id, company_id, title, starts_at, ends_at, all_day, colour, created_by, created_at from calendar_events
where company_id = $1::uuid
  and ($2::timestamptz is null or starts_at >= $2::timestamptz)
  and ($3::timestamptz is null or starts_at < $3::timestamptz)
order by starts_at, id
limit $5::int offset $4::int
`

type CalendarListEventsParams struct {
	CompanyID uuid.UUID
	RangeFrom pgtype.Timestamptz
	RangeTo   pgtype.Timestamptz
	OffsetVal int32
	LimitVal  int32
}

// ListEvents narrows by starts_at, the same single-column range convention
// OpsRepository.ListRuns/ListMessages use (and the column calendar_events'
// own index is built on): an event whose window merely overlaps [from, to)
// without STARTING inside it is not returned.
func (q *Queries) CalendarListEvents(ctx context.Context, arg CalendarListEventsParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, calendarListEvents,
		arg.CompanyID,
		arg.RangeFrom,
		arg.RangeTo,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalendarEvent
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Colour,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const calendarListVacations = `-- name: CalendarListVacations :many
select id, company_id, start_date, end_date, description from company_vacations
where company_id = $1::uuid
  and ($2::date is null or end_date >= $2::date)
  and ($3::date is null or start_date < $3::date)
order by start_date, id
`

type CalendarListVacationsParams struct {
	CompanyID uuid.UUID
	FromDate  pgtype.Date
	ToDate    pgtype.Date
}

// Vacations returns every vacation when from_date/to_date are both null.
// When set they narrow to vacations OVERLAPPING [from_date, to_date):
// end_date >= from_date and start_date < to_date, half-open the same way
// store.TimeRange itself is, applied to the vacation's own inclusive
// [start_date, end_date] span.
func (q *Queries) CalendarListVacations(ctx context.Context, arg CalendarListVacationsParams) ([]CompanyVacation, error) {
	rows, err := q.db.Query(ctx, calendarListVacations, arg.CompanyID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyVacation
	for rows.Next() {
		var i CompanyVacation
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.StartDate,
			&i.EndDate,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const calendarListWeekendDays = `-- name: CalendarListWeekendDays :many
select company_id, day_of_week from company_weekend_days where company_id = $1 order by day_of_week
`

func (q *Queries) CalendarListWeekendDays(ctx context.Context, companyID uuid.UUID) ([]CompanyWeekendDay, error) {
	rows, err := q.db.Query(ctx, calendarListWeekendDays, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyWeekendDay
	for rows.Next() {
		var i CompanyWeekendDay
		if err := rows.Scan(&i.CompanyID, &i.DayOfWeek); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const calendarUpdateEvent = `-- name: CalendarUpdateEvent :one
update calendar_events set
    title = $1,
    starts_at = $2::timestamptz,
    ends_at = $3::timestamptz,
    all_day = $4::boolean,
    colour = $5::text,
    created_by = $6::uuid
where id = $7::uuid and company_id = $8::uuid
  and (
    $6::uuid is null
    or exists (
        select 1 from users u
        where u.id = $6::uuid
          and u.company_id = $8::uuid
          and u.deleted_at is null
    )
  )
returning id, company_id, title, starts_at, ends_at, all_day, colour, created_by, created_at
`

type CalendarUpdateEventParams struct {
	Title     string
	StartsAt  pgtype.Timestamptz
	EndsAt    pgtype.Timestamptz
	AllDay    bool
	Colour    *string
	CreatedBy *uuid.UUID
	ID        uuid.UUID
	CompanyID uuid.UUID
}

// UpdateEvent replaces the event's mutable content -- title, starts_at,
// ends_at, all_day, colour and created_by. id, company_id and created_at
// never change. created_by is re-validated exactly as CalendarCreateEvent
// validates it, so a caller cannot smuggle in another company's user through
// an update that a create would have refused.
func (q *Queries) CalendarUpdateEvent(ctx context.Context, arg CalendarUpdateEventParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, calendarUpdateEvent,
		arg.Title,
		arg.StartsAt,
		arg.EndsAt,
		arg.AllDay,
		arg.Colour,
		arg.CreatedBy,
		arg.ID,
		arg.CompanyID,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.Colour,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
