// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: carbon.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const carbonBuildingVisibleForShare = `-- name: CarbonBuildingVisibleForShare :one
select id from buildings
where id = $1::uuid
  and company_id = $2::uuid
  and deleted_at is null
  and ($3::boolean or id = any($4::uuid[]))
for share
`

type CarbonBuildingVisibleForShareParams struct {
	BuildingID   uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// CarbonBuildingVisibleForShare is CarbonFactorOwnerForShare's counterpart
// for ReplaceSelectedActivities: it locks the building row so the visibility
// check and the delete+insert that follows are atomic together.
func (q *Queries) CarbonBuildingVisibleForShare(ctx context.Context, arg CarbonBuildingVisibleForShareParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, carbonBuildingVisibleForShare,
		arg.BuildingID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const carbonCreateActivity = `-- name: CarbonCreateActivity :one
insert into carbon_activities
    (id, company_id, building_id, main_category, sub_category, activity_type,
     period_start, period_end, quantity, unit, factor_id, factor_key, factor_value,
     conversion_multiplier, emission_kgco2e, scope, iso_category, description,
     details, status, is_automated, created_by)
select
    coalesce(nullif($1::uuid, '00000000-0000-0000-0000-000000000000'::uuid),
             gen_random_uuid()),
    $2::uuid, $3::uuid, $4,
    $5, $6, $7::date,
    $8::date, $9::numeric, $10,
    $11::uuid, $12::text, $13::numeric,
    $14::numeric, $15::numeric,
    $16::carbon_scope, $17, $18::text,
    $19::jsonb, $20::carbon_status, false, $21::uuid
where exists (
    select 1 from buildings b
    where b.id = $3::uuid
      and b.company_id = $2::uuid
      and b.deleted_at is null
      and ($22::boolean or b.id = any($23::uuid[]))
)
and (
    $21::uuid is null
    or exists (
        select 1 from users u
        where u.id = $21::uuid
          and u.company_id = $2::uuid
          and u.deleted_at is null
    )
)
returning id, company_id, building_id, main_category, sub_category, activity_type, period_start, period_end, quantity, unit, factor_id, factor_key, factor_value, conversion_multiplier, emission_kgco2e, scope, iso_category, description, details, status, is_automated, created_by, created_at, updated_at
`

type CarbonCreateActivityParams struct {
	ID                   uuid.UUID
	CompanyID            uuid.UUID
	BuildingID           uuid.UUID
	MainCategory         string
	SubCategory          string
	ActivityType         string
	PeriodStart          pgtype.Date
	PeriodEnd            pgtype.Date
	Quantity             pgtype.Numeric
	Unit                 string
	FactorID             *uuid.UUID
	FactorKey            *string
	FactorValue          pgtype.Numeric
	ConversionMultiplier pgtype.Numeric
	EmissionKgco2e       pgtype.Numeric
	Scope                CarbonScope
	IsoCategory          string
	Description          *string
	Details              []byte
	Status               CarbonStatus
	CreatedBy            *uuid.UUID
	AllBuildings         bool
	BuildingIds          []uuid.UUID
}

func (q *Queries) CarbonCreateActivity(ctx context.Context, arg CarbonCreateActivityParams) (CarbonActivity, error) {
	row := q.db.QueryRow(ctx, carbonCreateActivity,
		arg.ID,
		arg.CompanyID,
		arg.BuildingID,
		arg.MainCategory,
		arg.SubCategory,
		arg.ActivityType,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Quantity,
		arg.Unit,
		arg.FactorID,
		arg.FactorKey,
		arg.FactorValue,
		arg.ConversionMultiplier,
		arg.EmissionKgco2e,
		arg.Scope,
		arg.IsoCategory,
		arg.Description,
		arg.Details,
		arg.Status,
		arg.CreatedBy,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i CarbonActivity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.MainCategory,
		&i.SubCategory,
		&i.ActivityType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Quantity,
		&i.Unit,
		&i.FactorID,
		&i.FactorKey,
		&i.FactorValue,
		&i.ConversionMultiplier,
		&i.EmissionKgco2e,
		&i.Scope,
		&i.IsoCategory,
		&i.Description,
		&i.Details,
		&i.Status,
		&i.IsAutomated,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const carbonCreateReport = `-- name: CarbonCreateReport :one
insert into carbon_reports (id, company_id, building_id, name, report_type, period, payload, pdf_path)
select
    coalesce(nullif($1::uuid, '00000000-0000-0000-0000-000000000000'::uuid),
             gen_random_uuid()),
    $2::uuid, $3::uuid, $4,
    $5, $6, $7::jsonb, $8::text
where exists (
    select 1 from buildings b
    where b.id = $3::uuid
      and b.company_id = $2::uuid
      and b.deleted_at is null
      and ($9::boolean or b.id = any($10::uuid[]))
)
returning id, company_id, building_id, name, report_type, period, payload, pdf_path, created_at
`

type CarbonCreateReportParams struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	BuildingID   uuid.UUID
	Name         string
	ReportType   string
	Period       string
	Payload      []byte
	PdfPath      *string
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) CarbonCreateReport(ctx context.Context, arg CarbonCreateReportParams) (CarbonReport, error) {
	row := q.db.QueryRow(ctx, carbonCreateReport,
		arg.ID,
		arg.CompanyID,
		arg.BuildingID,
		arg.Name,
		arg.ReportType,
		arg.Period,
		arg.Payload,
		arg.PdfPath,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i CarbonReport
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.Name,
		&i.ReportType,
		&i.Period,
		&i.Payload,
		&i.PdfPath,
		&i.CreatedAt,
	)
	return i, err
}

const carbonDeleteActivity = `-- name: CarbonDeleteActivity :execrows
delete from carbon_activities
where id = $1::uuid
  and company_id = $2::uuid
  and exists (
      select 1 from buildings b
      where b.id = carbon_activities.building_id
        and b.deleted_at is null
        and ($3::boolean or b.id = any($4::uuid[]))
  )
`

type CarbonDeleteActivityParams struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) CarbonDeleteActivity(ctx context.Context, arg CarbonDeleteActivityParams) (int64, error) {
	result, err := q.db.Exec(ctx, carbonDeleteActivity,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const carbonDeleteConversions = `-- name: CarbonDeleteConversions :exec
delete from emission_factor_conversions where factor_id = $1
`

func (q *Queries) CarbonDeleteConversions(ctx context.Context, factorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, carbonDeleteConversions, factorID)
	return err
}

const carbonDeleteSelectedActivities = `-- name: CarbonDeleteSelectedActivities :exec
delete from carbon_selected_activities where company_id = $1 and building_id = $2
`

type CarbonDeleteSelectedActivitiesParams struct {
	CompanyID  uuid.UUID
	BuildingID uuid.UUID
}

func (q *Queries) CarbonDeleteSelectedActivities(ctx context.Context, arg CarbonDeleteSelectedActivitiesParams) error {
	_, err := q.db.Exec(ctx, carbonDeleteSelectedActivities, arg.CompanyID, arg.BuildingID)
	return err
}

const carbonFactorOwnerForShare = `-- name: CarbonFactorOwnerForShare :one
select company_id from emission_factors where id = $1 for share
`

// CarbonFactorOwnerForShare locks the parent row INSIDE the caller's
// transaction for ReplaceConversions, so the ownership check and the
// delete+insert that follows it see a consistent row and cannot race a
// concurrent write to the same factor.
func (q *Queries) CarbonFactorOwnerForShare(ctx context.Context, id uuid.UUID) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, carbonFactorOwnerForShare, id)
	var company_id *uuid.UUID
	err := row.Scan(&company_id)
	return company_id, err
}

const carbonGetActivity = `-- name: CarbonGetActivity :one
select ca.id, ca.company_id, ca.building_id, ca.main_category, ca.sub_category, ca.activity_type, ca.period_start, ca.period_end, ca.quantity, ca.unit, ca.factor_id, ca.factor_key, ca.factor_value, ca.conversion_multiplier, ca.emission_kgco2e, ca.scope, ca.iso_category, ca.description, ca.details, ca.status, ca.is_automated, ca.created_by, ca.created_at, ca.updated_at from carbon_activities ca
join buildings b on b.id = ca.building_id
where ca.id = $1
  and ca.company_id = $2
  and b.deleted_at is null
  and ($3::boolean or ca.building_id = any($4::uuid[]))
`

type CarbonGetActivityParams struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) CarbonGetActivity(ctx context.Context, arg CarbonGetActivityParams) (CarbonActivity, error) {
	row := q.db.QueryRow(ctx, carbonGetActivity,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i CarbonActivity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.MainCategory,
		&i.SubCategory,
		&i.ActivityType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Quantity,
		&i.Unit,
		&i.FactorID,
		&i.FactorKey,
		&i.FactorValue,
		&i.ConversionMultiplier,
		&i.EmissionKgco2e,
		&i.Scope,
		&i.IsoCategory,
		&i.Description,
		&i.Details,
		&i.Status,
		&i.IsAutomated,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const carbonGetFactor = `-- name: CarbonGetFactor :one

select id, company_id, key, label, main_category, sub_categories, category_path, base_factor, base_unit, fuel_type, vehicle_type, scope, iso_category, status, source, source_year, source_url, created_at, updated_at from emission_factors
where id = $1
  and (company_id is null or company_id = $2)
`

type CarbonGetFactorParams struct {
	ID        uuid.UUID
	CompanyID *uuid.UUID
}

// Carbon repository queries (migration 00007). Owned by Task 11b.
//
// emission_factors' natural key is (coalesce(company_id, zero uuid), key) --
// the unique index from migration 00007. CarbonUpsertFactor and, in
// admin/catalogue.go, AdminUpsertPlatformFactor both target it with a single
// atomic INSERT ... ON CONFLICT ... DO UPDATE, never a separate
// check-then-insert.
//
// CarbonUpsertFactor additionally guards against a caller-supplied id
// belonging to another company's (or the platform's) factor: the
// "where target.ok" clause makes the INSERT select zero rows in that case,
// so the query returns no rows and the repository translates that into
// ErrNotFound, atomically with the write itself.
func (q *Queries) CarbonGetFactor(ctx context.Context, arg CarbonGetFactorParams) (EmissionFactor, error) {
	row := q.db.QueryRow(ctx, carbonGetFactor, arg.ID, arg.CompanyID)
	var i EmissionFactor
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Key,
		&i.Label,
		&i.MainCategory,
		&i.SubCategories,
		&i.CategoryPath,
		&i.BaseFactor,
		&i.BaseUnit,
		&i.FuelType,
		&i.VehicleType,
		&i.Scope,
		&i.IsoCategory,
		&i.Status,
		&i.Source,
		&i.SourceYear,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const carbonInsertConversions = `-- name: CarbonInsertConversions :exec
insert into emission_factor_conversions (factor_id, unit, multiplier, label)
select $1, elem->>'unit', (elem->>'multiplier')::numeric, elem->>'label'
from jsonb_array_elements($2::jsonb) as elem
`

type CarbonInsertConversionsParams struct {
	FactorID    uuid.UUID
	Conversions []byte
}

// CarbonInsertConversions takes the whole batch as one jsonb array: sqlc's
// (deliberately minimal) built-in catalogue has no multi-array unnest
// overload, so a single jsonb parameter unpacked with jsonb_array_elements
// and read back with `elem->>'field'` plus a per-column cast is this
// codebase's bulk-insert idiom for a parallel-column child collection (see
// timescale-shims.sql's jsonb_array_elements declaration for why this shape,
// and not jsonb_to_recordset's `AS t(col type, ...)`).
func (q *Queries) CarbonInsertConversions(ctx context.Context, arg CarbonInsertConversionsParams) error {
	_, err := q.db.Exec(ctx, carbonInsertConversions, arg.FactorID, arg.Conversions)
	return err
}

const carbonInsertSelectedActivities = `-- name: CarbonInsertSelectedActivities :exec
insert into carbon_selected_activities (company_id, building_id, activity_key)
select $1, $2, activity_key from unnest($3::text[]) as activity_key
`

type CarbonInsertSelectedActivitiesParams struct {
	CompanyID  uuid.UUID
	BuildingID uuid.UUID
	Keys       []string
}

// The alias is a bare name, not a parenthesised column list: unnest's
// single-array-argument form returns exactly one column, and aliasing it as
// `as activity_key` (rather than `as t(activity_key)`) means the alias
// itself is never followed by "(" — see timescale-shims.sql's
// jsonb_array_elements declaration for why that distinction matters here.
func (q *Queries) CarbonInsertSelectedActivities(ctx context.Context, arg CarbonInsertSelectedActivitiesParams) error {
	_, err := q.db.Exec(ctx, carbonInsertSelectedActivities, arg.CompanyID, arg.BuildingID, arg.Keys)
	return err
}

const carbonListActivities = `-- name: CarbonListActivities :many
select ca.id, ca.company_id, ca.building_id, ca.main_category, ca.sub_category, ca.activity_type, ca.period_start, ca.period_end, ca.quantity, ca.unit, ca.factor_id, ca.factor_key, ca.factor_value, ca.conversion_multiplier, ca.emission_kgco2e, ca.scope, ca.iso_category, ca.description, ca.details, ca.status, ca.is_automated, ca.created_by, ca.created_at, ca.updated_at from carbon_activities ca
join buildings b on b.id = ca.building_id
where ca.company_id = $1::uuid
  and b.deleted_at is null
  and ($2::boolean or ca.building_id = any($3::uuid[]))
  and ($4::uuid[] is null or cardinality($4::uuid[]) = 0
       or ca.building_id = any($4::uuid[]))
  -- scopes/statuses are text[], not carbon_scope[]/carbon_status[]: pgx has
  -- no array codec for a custom enum type without explicit registration, so
  -- the comparison casts the column to text instead of typing the parameter
  -- array as the enum.
  and ($5::text[] is null or cardinality($5::text[]) = 0
       or ca.scope::text = any($5::text[]))
  and ($6::text[] is null or cardinality($6::text[]) = 0
       or ca.status::text = any($6::text[]))
  and ($7::text is null or ca.activity_type = $7::text)
  and ($8::date is null or ca.period_start >= $8::date)
  and ($9::date is null or ca.period_end <= $9::date)
  and ($10::boolean is null or ca.is_automated = $10::boolean)
order by ca.period_start desc, ca.id
limit $12::int offset $11::int
`

type CarbonListActivitiesParams struct {
	CompanyID         uuid.UUID
	AllBuildings      bool
	BuildingIds       []uuid.UUID
	FilterBuildingIds []uuid.UUID
	Scopes            []string
	Statuses          []string
	ActivityType      *string
	PeriodFrom        pgtype.Date
	PeriodTo          pgtype.Date
	IsAutomated       *bool
	OffsetVal         int32
	LimitVal          int32
}

func (q *Queries) CarbonListActivities(ctx context.Context, arg CarbonListActivitiesParams) ([]CarbonActivity, error) {
	rows, err := q.db.Query(ctx, carbonListActivities,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
		arg.FilterBuildingIds,
		arg.Scopes,
		arg.Statuses,
		arg.ActivityType,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.IsAutomated,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CarbonActivity
	for rows.Next() {
		var i CarbonActivity
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BuildingID,
			&i.MainCategory,
			&i.SubCategory,
			&i.ActivityType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Quantity,
			&i.Unit,
			&i.FactorID,
			&i.FactorKey,
			&i.FactorValue,
			&i.ConversionMultiplier,
			&i.EmissionKgco2e,
			&i.Scope,
			&i.IsoCategory,
			&i.Description,
			&i.Details,
			&i.Status,
			&i.IsAutomated,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const carbonListConversions = `-- name: CarbonListConversions :many
select c.factor_id, c.unit, c.multiplier, c.label from emission_factor_conversions c
join emission_factors f on f.id = c.factor_id
where c.factor_id = $1
  and (f.company_id is null or f.company_id = $2)
order by c.unit
`

type CarbonListConversionsParams struct {
	FactorID  uuid.UUID
	CompanyID *uuid.UUID
}

func (q *Queries) CarbonListConversions(ctx context.Context, arg CarbonListConversionsParams) ([]EmissionFactorConversion, error) {
	rows, err := q.db.Query(ctx, carbonListConversions, arg.FactorID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmissionFactorConversion
	for rows.Next() {
		var i EmissionFactorConversion
		if err := rows.Scan(
			&i.FactorID,
			&i.Unit,
			&i.Multiplier,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const carbonListFactors = `-- name: CarbonListFactors :many
select id, company_id, key, label, main_category, sub_categories, category_path, base_factor, base_unit, fuel_type, vehicle_type, scope, iso_category, status, source, source_year, source_url, created_at, updated_at from emission_factors
where (company_id = $1::uuid
       or ($2::boolean and company_id is null))
  and ($3::text[] is null or cardinality($3::text[]) = 0
       or key = any($3::text[]))
  and ($4::text is null or main_category = $4::text)
  and ($5::carbon_scope is null or scope = $5::carbon_scope)
order by company_id nulls first, key
limit $7::int offset $6::int
`

type CarbonListFactorsParams struct {
	CompanyID       uuid.UUID
	IncludePlatform bool
	Keys            []string
	MainCategory    *string
	Scope           NullCarbonScope
	OffsetVal       int32
	LimitVal        int32
}

func (q *Queries) CarbonListFactors(ctx context.Context, arg CarbonListFactorsParams) ([]EmissionFactor, error) {
	rows, err := q.db.Query(ctx, carbonListFactors,
		arg.CompanyID,
		arg.IncludePlatform,
		arg.Keys,
		arg.MainCategory,
		arg.Scope,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmissionFactor
	for rows.Next() {
		var i EmissionFactor
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Key,
			&i.Label,
			&i.MainCategory,
			&i.SubCategories,
			&i.CategoryPath,
			&i.BaseFactor,
			&i.BaseUnit,
			&i.FuelType,
			&i.VehicleType,
			&i.Scope,
			&i.IsoCategory,
			&i.Status,
			&i.Source,
			&i.SourceYear,
			&i.SourceUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const carbonListReports = `-- name: CarbonListReports :many
select cr.id, cr.company_id, cr.building_id, cr.name, cr.report_type, cr.period, cr.payload, cr.pdf_path, cr.created_at from carbon_reports cr
join buildings b on b.id = cr.building_id
where cr.company_id = $1::uuid
  and b.deleted_at is null
  and ($2::boolean or cr.building_id = any($3::uuid[]))
  and ($4::uuid is null or cr.building_id = $4::uuid)
order by cr.created_at desc, cr.id
limit $6::int offset $5::int
`

type CarbonListReportsParams struct {
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
	BuildingID   *uuid.UUID
	OffsetVal    int32
	LimitVal     int32
}

func (q *Queries) CarbonListReports(ctx context.Context, arg CarbonListReportsParams) ([]CarbonReport, error) {
	rows, err := q.db.Query(ctx, carbonListReports,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
		arg.BuildingID,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CarbonReport
	for rows.Next() {
		var i CarbonReport
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BuildingID,
			&i.Name,
			&i.ReportType,
			&i.Period,
			&i.Payload,
			&i.PdfPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const carbonListSelectedActivities = `-- name: CarbonListSelectedActivities :many
select csa.company_id, csa.building_id, csa.activity_key from carbon_selected_activities csa
join buildings b on b.id = csa.building_id
where csa.company_id = $1::uuid
  and csa.building_id = $2::uuid
  and b.deleted_at is null
  and ($3::boolean or csa.building_id = any($4::uuid[]))
order by csa.activity_key
`

type CarbonListSelectedActivitiesParams struct {
	CompanyID    uuid.UUID
	BuildingID   uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// The scope's building narrowing is embedded here rather than checked with
// Scope.AllowsBuilding in Go: AllowsBuilding returns true for ANY id under
// AllBuildings, including another tenant's, so it must never be the thing
// standing between a caller and a row — only a predicate inside the query
// itself does that reliably.
func (q *Queries) CarbonListSelectedActivities(ctx context.Context, arg CarbonListSelectedActivitiesParams) ([]CarbonSelectedActivity, error) {
	rows, err := q.db.Query(ctx, carbonListSelectedActivities,
		arg.CompanyID,
		arg.BuildingID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CarbonSelectedActivity
	for rows.Next() {
		var i CarbonSelectedActivity
		if err := rows.Scan(&i.CompanyID, &i.BuildingID, &i.ActivityKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const carbonSetActivityStatus = `-- name: CarbonSetActivityStatus :one
update carbon_activities set status = $1::carbon_status, updated_at = $2::timestamptz
where id = $3::uuid
  and company_id = $4::uuid
  and exists (
      select 1 from buildings b
      where b.id = carbon_activities.building_id
        and b.deleted_at is null
        and ($5::boolean or b.id = any($6::uuid[]))
  )
returning id, company_id, building_id, main_category, sub_category, activity_type, period_start, period_end, quantity, unit, factor_id, factor_key, factor_value, conversion_multiplier, emission_kgco2e, scope, iso_category, description, details, status, is_automated, created_by, created_at, updated_at
`

type CarbonSetActivityStatusParams struct {
	Status       CarbonStatus
	At           pgtype.Timestamptz
	ID           uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) CarbonSetActivityStatus(ctx context.Context, arg CarbonSetActivityStatusParams) (CarbonActivity, error) {
	row := q.db.QueryRow(ctx, carbonSetActivityStatus,
		arg.Status,
		arg.At,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i CarbonActivity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.MainCategory,
		&i.SubCategory,
		&i.ActivityType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Quantity,
		&i.Unit,
		&i.FactorID,
		&i.FactorKey,
		&i.FactorValue,
		&i.ConversionMultiplier,
		&i.EmissionKgco2e,
		&i.Scope,
		&i.IsoCategory,
		&i.Description,
		&i.Details,
		&i.Status,
		&i.IsAutomated,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const carbonUpdateActivity = `-- name: CarbonUpdateActivity :one
update carbon_activities set
    main_category = $1,
    sub_category = $2,
    activity_type = $3,
    period_start = $4::date,
    period_end = $5::date,
    quantity = $6::numeric,
    unit = $7,
    factor_id = $8::uuid,
    factor_key = $9::text,
    factor_value = $10::numeric,
    conversion_multiplier = $11::numeric,
    emission_kgco2e = $12::numeric,
    scope = $13::carbon_scope,
    iso_category = $14,
    description = $15::text,
    details = $16::jsonb,
    status = $17::carbon_status,
    updated_at = now()
where carbon_activities.id = $18::uuid
  and carbon_activities.company_id = $19::uuid
  and exists (
      select 1 from buildings b
      where b.id = carbon_activities.building_id
        and b.deleted_at is null
        and ($20::boolean or b.id = any($21::uuid[]))
  )
returning id, company_id, building_id, main_category, sub_category, activity_type, period_start, period_end, quantity, unit, factor_id, factor_key, factor_value, conversion_multiplier, emission_kgco2e, scope, iso_category, description, details, status, is_automated, created_by, created_at, updated_at
`

type CarbonUpdateActivityParams struct {
	MainCategory         string
	SubCategory          string
	ActivityType         string
	PeriodStart          pgtype.Date
	PeriodEnd            pgtype.Date
	Quantity             pgtype.Numeric
	Unit                 string
	FactorID             *uuid.UUID
	FactorKey            *string
	FactorValue          pgtype.Numeric
	ConversionMultiplier pgtype.Numeric
	EmissionKgco2e       pgtype.Numeric
	Scope                CarbonScope
	IsoCategory          string
	Description          *string
	Details              []byte
	Status               CarbonStatus
	ID                   uuid.UUID
	CompanyID            uuid.UUID
	AllBuildings         bool
	BuildingIds          []uuid.UUID
}

// building_id is deliberately not in the SET list: as with
// ISO50001Repository.UpdateNote's project_id, an activity stays under the
// building it was created in, so an update cannot move it into a building
// outside the caller's scope.
func (q *Queries) CarbonUpdateActivity(ctx context.Context, arg CarbonUpdateActivityParams) (CarbonActivity, error) {
	row := q.db.QueryRow(ctx, carbonUpdateActivity,
		arg.MainCategory,
		arg.SubCategory,
		arg.ActivityType,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Quantity,
		arg.Unit,
		arg.FactorID,
		arg.FactorKey,
		arg.FactorValue,
		arg.ConversionMultiplier,
		arg.EmissionKgco2e,
		arg.Scope,
		arg.IsoCategory,
		arg.Description,
		arg.Details,
		arg.Status,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i CarbonActivity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.MainCategory,
		&i.SubCategory,
		&i.ActivityType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Quantity,
		&i.Unit,
		&i.FactorID,
		&i.FactorKey,
		&i.FactorValue,
		&i.ConversionMultiplier,
		&i.EmissionKgco2e,
		&i.Scope,
		&i.IsoCategory,
		&i.Description,
		&i.Details,
		&i.Status,
		&i.IsAutomated,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const carbonUpsertAutomatedActivity = `-- name: CarbonUpsertAutomatedActivity :one
insert into carbon_activities
    (id, company_id, building_id, main_category, sub_category, activity_type,
     period_start, period_end, quantity, unit, factor_id, factor_key, factor_value,
     conversion_multiplier, emission_kgco2e, scope, iso_category, description,
     details, status, is_automated, created_by)
select
    gen_random_uuid(),
    $1::uuid, $2::uuid, $3,
    $4, $5, $6::date,
    $7::date, $8::numeric, $9,
    $10::uuid, $11::text, $12::numeric,
    $13::numeric, $14::numeric,
    $15::carbon_scope, $16, $17::text,
    $18::jsonb, $19::carbon_status, true, $20::uuid
where exists (
    select 1 from buildings b
    where b.id = $2::uuid
      and b.company_id = $1::uuid
      and b.deleted_at is null
      and ($21::boolean or b.id = any($22::uuid[]))
)
and (
    $20::uuid is null
    or exists (
        select 1 from users u
        where u.id = $20::uuid
          and u.company_id = $1::uuid
          and u.deleted_at is null
    )
)
on conflict (building_id, activity_type, period_start) where is_automated
do update set
    main_category = excluded.main_category,
    sub_category = excluded.sub_category,
    quantity = excluded.quantity,
    unit = excluded.unit,
    factor_id = excluded.factor_id,
    factor_key = excluded.factor_key,
    factor_value = excluded.factor_value,
    conversion_multiplier = excluded.conversion_multiplier,
    emission_kgco2e = excluded.emission_kgco2e,
    scope = excluded.scope,
    iso_category = excluded.iso_category,
    description = excluded.description,
    details = excluded.details,
    status = excluded.status,
    updated_at = now()
returning id, company_id, building_id, main_category, sub_category, activity_type, period_start, period_end, quantity, unit, factor_id, factor_key, factor_value, conversion_multiplier, emission_kgco2e, scope, iso_category, description, details, status, is_automated, created_by, created_at, updated_at
`

type CarbonUpsertAutomatedActivityParams struct {
	CompanyID            uuid.UUID
	BuildingID           uuid.UUID
	MainCategory         string
	SubCategory          string
	ActivityType         string
	PeriodStart          pgtype.Date
	PeriodEnd            pgtype.Date
	Quantity             pgtype.Numeric
	Unit                 string
	FactorID             *uuid.UUID
	FactorKey            *string
	FactorValue          pgtype.Numeric
	ConversionMultiplier pgtype.Numeric
	EmissionKgco2e       pgtype.Numeric
	Scope                CarbonScope
	IsoCategory          string
	Description          *string
	Details              []byte
	Status               CarbonStatus
	CreatedBy            *uuid.UUID
	AllBuildings         bool
	BuildingIds          []uuid.UUID
}

// Keyed on the partial unique index (building_id, activity_type,
// period_start) where is_automated. is_automated is hard-coded true: this
// path exists only for the derived-from-meter-data recomputation.
func (q *Queries) CarbonUpsertAutomatedActivity(ctx context.Context, arg CarbonUpsertAutomatedActivityParams) (CarbonActivity, error) {
	row := q.db.QueryRow(ctx, carbonUpsertAutomatedActivity,
		arg.CompanyID,
		arg.BuildingID,
		arg.MainCategory,
		arg.SubCategory,
		arg.ActivityType,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Quantity,
		arg.Unit,
		arg.FactorID,
		arg.FactorKey,
		arg.FactorValue,
		arg.ConversionMultiplier,
		arg.EmissionKgco2e,
		arg.Scope,
		arg.IsoCategory,
		arg.Description,
		arg.Details,
		arg.Status,
		arg.CreatedBy,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i CarbonActivity
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.MainCategory,
		&i.SubCategory,
		&i.ActivityType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Quantity,
		&i.Unit,
		&i.FactorID,
		&i.FactorKey,
		&i.FactorValue,
		&i.ConversionMultiplier,
		&i.EmissionKgco2e,
		&i.Scope,
		&i.IsoCategory,
		&i.Description,
		&i.Details,
		&i.Status,
		&i.IsAutomated,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const carbonUpsertFactor = `-- name: CarbonUpsertFactor :one
with target as (
    select
        coalesce(nullif($17::uuid, '00000000-0000-0000-0000-000000000000'::uuid),
                 gen_random_uuid()) as id,
        not exists (
            select 1 from emission_factors ef
            where ef.id = $17::uuid
              and ef.company_id is distinct from $1::uuid
        ) as ok
)
insert into emission_factors
    (id, company_id, key, label, main_category, sub_categories, category_path,
     base_factor, base_unit, fuel_type, vehicle_type, scope, iso_category,
     status, source, source_year, source_url)
select
    target.id, $1::uuid, $2, $3,
    $4, $5::text[], $6::text[],
    $7::numeric, $8, $9::text,
    $10::text, $11::carbon_scope, $12::text,
    $13::text, $14::text, $15::smallint,
    $16::text
from target
where target.ok
on conflict (coalesce(company_id, '00000000-0000-0000-0000-000000000000'::uuid), key)
do update set
    label = excluded.label,
    main_category = excluded.main_category,
    sub_categories = excluded.sub_categories,
    category_path = excluded.category_path,
    base_factor = excluded.base_factor,
    base_unit = excluded.base_unit,
    fuel_type = excluded.fuel_type,
    vehicle_type = excluded.vehicle_type,
    scope = excluded.scope,
    iso_category = excluded.iso_category,
    status = excluded.status,
    source = excluded.source,
    source_year = excluded.source_year,
    source_url = excluded.source_url,
    updated_at = now()
returning id, company_id, key, label, main_category, sub_categories, category_path, base_factor, base_unit, fuel_type, vehicle_type, scope, iso_category, status, source, source_year, source_url, created_at, updated_at
`

type CarbonUpsertFactorParams struct {
	CompanyID     uuid.UUID
	Key           string
	Label         string
	MainCategory  string
	SubCategories []string
	CategoryPath  []string
	BaseFactor    pgtype.Numeric
	BaseUnit      string
	FuelType      *string
	VehicleType   *string
	Scope         NullCarbonScope
	IsoCategory   *string
	Status        *string
	Source        *string
	SourceYear    *int16
	SourceUrl     *string
	ID            uuid.UUID
}

func (q *Queries) CarbonUpsertFactor(ctx context.Context, arg CarbonUpsertFactorParams) (EmissionFactor, error) {
	row := q.db.QueryRow(ctx, carbonUpsertFactor,
		arg.CompanyID,
		arg.Key,
		arg.Label,
		arg.MainCategory,
		arg.SubCategories,
		arg.CategoryPath,
		arg.BaseFactor,
		arg.BaseUnit,
		arg.FuelType,
		arg.VehicleType,
		arg.Scope,
		arg.IsoCategory,
		arg.Status,
		arg.Source,
		arg.SourceYear,
		arg.SourceUrl,
		arg.ID,
	)
	var i EmissionFactor
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Key,
		&i.Label,
		&i.MainCategory,
		&i.SubCategories,
		&i.CategoryPath,
		&i.BaseFactor,
		&i.BaseUnit,
		&i.FuelType,
		&i.VehicleType,
		&i.Scope,
		&i.IsoCategory,
		&i.Status,
		&i.Source,
		&i.SourceYear,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
