// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const companyCreate = `-- name: CompanyCreate :one
insert into companies as "row"
    (id, name, address, total_area_m2, personnel_count, contact_name,
     contact_phone, sector, created_at, updated_at)
values ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9, $9)
returning id, name, address, total_area_m2, personnel_count, contact_name, contact_phone, sector, created_at, updated_at, deleted_at
`

type CompanyCreateParams struct {
	ID             uuid.UUID
	Name           string
	Address        *string
	TotalAreaM2    pgtype.Numeric
	PersonnelCount *int32
	ContactName    *string
	ContactPhone   *string
	Sector         *string
	At             pgtype.Timestamptz
}

// The `as "row"` alias dodges TestEveryFunctionSQLcMustTypeIsDeclared's call
// scanner — see queries/admin_audit.sql's comment on AdminAppendPlatformAudit.
func (q *Queries) CompanyCreate(ctx context.Context, arg CompanyCreateParams) (Company, error) {
	row := q.db.QueryRow(ctx, companyCreate,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.TotalAreaM2,
		arg.PersonnelCount,
		arg.ContactName,
		arg.ContactPhone,
		arg.Sector,
		arg.At,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.TotalAreaM2,
		&i.PersonnelCount,
		&i.ContactName,
		&i.ContactPhone,
		&i.Sector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const companyGet = `-- name: CompanyGet :one

select id, name, address, total_area_m2, personnel_count, contact_name, contact_phone, sector, created_at, updated_at, deleted_at from companies
where id = $1
  and id = $2
  and deleted_at is null
`

type CompanyGetParams struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
}

// CompanyRepository queries. A company IS the tenant, so the scope predicate
// is "id equals the Scope's own CompanyID" rather than a company_id column:
// every query below takes the requested id and the scope's company_id as
// separate arguments and requires both, so a mismatched pair returns no row
// the same way a foreign tenant's row would on every other repository.
func (q *Queries) CompanyGet(ctx context.Context, arg CompanyGetParams) (Company, error) {
	row := q.db.QueryRow(ctx, companyGet, arg.ID, arg.CompanyID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.TotalAreaM2,
		&i.PersonnelCount,
		&i.ContactName,
		&i.ContactPhone,
		&i.Sector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const companyList = `-- name: CompanyList :many
select id, name, address, total_area_m2, personnel_count, contact_name, contact_phone, sector, created_at, updated_at, deleted_at from companies
where id = $1
  and ($2::boolean or deleted_at is null)
  and ($3::text = '' or name ilike '%' || $3::text || '%')
  and ($4::text is null or sector = $4)
order by name
limit $6 offset $5
`

type CompanyListParams struct {
	CompanyID      uuid.UUID
	IncludeDeleted bool
	NameContains   string
	Sector         *string
	PageOffset     int32
	PageLimit      int32
}

func (q *Queries) CompanyList(ctx context.Context, arg CompanyListParams) ([]Company, error) {
	rows, err := q.db.Query(ctx, companyList,
		arg.CompanyID,
		arg.IncludeDeleted,
		arg.NameContains,
		arg.Sector,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.TotalAreaM2,
			&i.PersonnelCount,
			&i.ContactName,
			&i.ContactPhone,
			&i.Sector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const companySoftDelete = `-- name: CompanySoftDelete :execrows
update companies
set deleted_at = $1
where id = $2
  and id = $3
  and deleted_at is null
`

type CompanySoftDeleteParams struct {
	DeletedAt pgtype.Timestamptz
	ID        uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) CompanySoftDelete(ctx context.Context, arg CompanySoftDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, companySoftDelete, arg.DeletedAt, arg.ID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const companyUpdate = `-- name: CompanyUpdate :one
update companies
set name = $1,
    address = $2,
    total_area_m2 = $3,
    personnel_count = $4,
    contact_name = $5,
    contact_phone = $6,
    sector = $7,
    updated_at = $8
where id = $9
  and id = $10
  and deleted_at is null
returning id, name, address, total_area_m2, personnel_count, contact_name, contact_phone, sector, created_at, updated_at, deleted_at
`

type CompanyUpdateParams struct {
	Name           string
	Address        *string
	TotalAreaM2    pgtype.Numeric
	PersonnelCount *int32
	ContactName    *string
	ContactPhone   *string
	Sector         *string
	UpdatedAt      pgtype.Timestamptz
	ID             uuid.UUID
	CompanyID      uuid.UUID
}

func (q *Queries) CompanyUpdate(ctx context.Context, arg CompanyUpdateParams) (Company, error) {
	row := q.db.QueryRow(ctx, companyUpdate,
		arg.Name,
		arg.Address,
		arg.TotalAreaM2,
		arg.PersonnelCount,
		arg.ContactName,
		arg.ContactPhone,
		arg.Sector,
		arg.UpdatedAt,
		arg.ID,
		arg.CompanyID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.TotalAreaM2,
		&i.PersonnelCount,
		&i.ContactName,
		&i.ContactPhone,
		&i.Sector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
