// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cursors.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cursorGet = `-- name: CursorGet :one

select c.analyzer_id, c.kind, c.last_ts, c.last_success_at, c.last_error, c.last_error_at, c.consecutive_failures from ingestion_cursors c
join analyzers a on a.id = c.analyzer_id
where c.analyzer_id = $1
  and c.kind = $2::reading_kind
  and a.company_id = $3
  and ($4::boolean or a.building_id = any($5::uuid[]))
  and a.deleted_at is null
`

type CursorGetParams struct {
	AnalyzerID   uuid.UUID
	Kind         ReadingKind
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// CursorRepository's queries. ingestion_cursors has no company_id: every
// method joins through analyzers.
// A single query covers BOTH "analyzer not visible" and "no cursor yet": both
// yield zero rows, and repository.go's doc says both return ErrNotFound.
func (q *Queries) CursorGet(ctx context.Context, arg CursorGetParams) (IngestionCursor, error) {
	row := q.db.QueryRow(ctx, cursorGet,
		arg.AnalyzerID,
		arg.Kind,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i IngestionCursor
	err := row.Scan(
		&i.AnalyzerID,
		&i.Kind,
		&i.LastTs,
		&i.LastSuccessAt,
		&i.LastError,
		&i.LastErrorAt,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const cursorList = `-- name: CursorList :many
select c.analyzer_id, c.kind, c.last_ts, c.last_success_at, c.last_error, c.last_error_at, c.consecutive_failures from ingestion_cursors c
join analyzers a on a.id = c.analyzer_id
where a.company_id = $1
  and ($2::boolean or a.building_id = any($3::uuid[]))
  and a.deleted_at is null
  and c.analyzer_id = any($4::uuid[])
order by c.analyzer_id, c.kind
`

type CursorListParams struct {
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
	AnalyzerIds  []uuid.UUID
}

// analyzer_ids is a REQUIRED POSITIONAL parameter (repository.go's
// CursorRepository.List doc): EMPTY or nil means NO ROWS, fail-closed,
// identical to Scope.BuildingIDs — never "every analyzer visible to the
// scope". `c.analyzer_id = any(sqlc.arg(analyzer_ids)::uuid[])` already gets
// this for free: a nil slice encodes to NULL::uuid[], and `x = any(NULL)` is
// NULL, which the WHERE clause reads as false, matching zero rows. A
// non-empty list narrows further; ids outside the scope contribute no rows.
func (q *Queries) CursorList(ctx context.Context, arg CursorListParams) ([]IngestionCursor, error) {
	rows, err := q.db.Query(ctx, cursorList,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
		arg.AnalyzerIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestionCursor
	for rows.Next() {
		var i IngestionCursor
		if err := rows.Scan(
			&i.AnalyzerID,
			&i.Kind,
			&i.LastTs,
			&i.LastSuccessAt,
			&i.LastError,
			&i.LastErrorAt,
			&i.ConsecutiveFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cursorRecordFailure = `-- name: CursorRecordFailure :execrows
insert into ingestion_cursors (analyzer_id, kind, last_error, last_error_at, consecutive_failures)
select a.id, $1::reading_kind, $2::text, $3::timestamptz, 1
from analyzers a
where a.id = $4
  and a.company_id = $5
  and ($6::boolean or a.building_id = any($7::uuid[]))
  and a.deleted_at is null
on conflict (analyzer_id, kind) do update set
    last_error = excluded.last_error,
    last_error_at = excluded.last_error_at,
    consecutive_failures = ingestion_cursors.consecutive_failures + 1
`

type CursorRecordFailureParams struct {
	Kind         ReadingKind
	Message      string
	At           pgtype.Timestamptz
	AnalyzerID   uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) CursorRecordFailure(ctx context.Context, arg CursorRecordFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, cursorRecordFailure,
		arg.Kind,
		arg.Message,
		arg.At,
		arg.AnalyzerID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cursorRecordSuccess = `-- name: CursorRecordSuccess :execrows
insert into ingestion_cursors (analyzer_id, kind, last_ts, last_success_at, consecutive_failures)
select a.id, $1::reading_kind, $2::timestamptz, $3::timestamptz, 0
from analyzers a
where a.id = $4
  and a.company_id = $5
  and ($6::boolean or a.building_id = any($7::uuid[]))
  and a.deleted_at is null
on conflict (analyzer_id, kind) do update set
    last_ts = greatest(ingestion_cursors.last_ts, excluded.last_ts),
    last_success_at = excluded.last_success_at,
    consecutive_failures = 0
`

type CursorRecordSuccessParams struct {
	Kind         ReadingKind
	LastTs       pgtype.Timestamptz
	At           pgtype.Timestamptz
	AnalyzerID   uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// The select-from-analyzers source is the visibility check: an invisible
// analyzer_id makes the source empty, so nothing is inserted or updated and
// execrows reports 0, which the repository reads as ErrNotFound.
//
// last_ts is a HIGH-WATER MARK: `greatest(...)` on conflict means an
// out-of-order success (one whose lastTs is behind what is already stored)
// can never move it backwards. last_success_at and consecutive_failures are
// NOT max'd — they record when this call happened and reset the streak,
// which is correct regardless of arrival order.
func (q *Queries) CursorRecordSuccess(ctx context.Context, arg CursorRecordSuccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, cursorRecordSuccess,
		arg.Kind,
		arg.LastTs,
		arg.At,
		arg.AnalyzerID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
