// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const fileCreate = `-- name: FileCreate :one
insert into stored_files
    (id, company_id, owner_type, owner_id, clause_id, original_name, stored_path,
     content_type, size_bytes, checksum, uploaded_by)
select
    coalesce(nullif($1::uuid, '00000000-0000-0000-0000-000000000000'::uuid),
             gen_random_uuid()),
    $2::uuid, $3, $4::uuid,
    $5::text, $6, $7,
    $8, $9::bigint, $10,
    $11::uuid
where (
    $11::uuid is null
    or exists (
        select 1 from users u
        where u.id = $11::uuid
          and u.company_id = $2::uuid
          and u.deleted_at is null
    )
)
returning id, company_id, owner_type, owner_id, clause_id, original_name, stored_path, content_type, size_bytes, checksum, uploaded_by, created_at, deleted_at
`

type FileCreateParams struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	OwnerType    string
	OwnerID      *uuid.UUID
	ClauseID     *string
	OriginalName string
	StoredPath   string
	ContentType  string
	SizeBytes    int64
	Checksum     string
	UploadedBy   *uuid.UUID
}

// uploaded_by, when set, must be a user of company_id: the `and (... is null
// or exists (...))` clause makes that atomic with the insert.
func (q *Queries) FileCreate(ctx context.Context, arg FileCreateParams) (StoredFile, error) {
	row := q.db.QueryRow(ctx, fileCreate,
		arg.ID,
		arg.CompanyID,
		arg.OwnerType,
		arg.OwnerID,
		arg.ClauseID,
		arg.OriginalName,
		arg.StoredPath,
		arg.ContentType,
		arg.SizeBytes,
		arg.Checksum,
		arg.UploadedBy,
	)
	var i StoredFile
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.OwnerType,
		&i.OwnerID,
		&i.ClauseID,
		&i.OriginalName,
		&i.StoredPath,
		&i.ContentType,
		&i.SizeBytes,
		&i.Checksum,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const fileGet = `-- name: FileGet :one

select id, company_id, owner_type, owner_id, clause_id, original_name, stored_path, content_type, size_bytes, checksum, uploaded_by, created_at, deleted_at from stored_files where id = $1 and company_id = $2 and deleted_at is null
`

type FileGetParams struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
}

// File metadata repository queries (migration 00008). Owned by Task 11b.
//
// stored_files carries company_id directly and has no building_id at all
// (like power_plants), so Scope narrows it to company_id only — there is no
// building set to intersect against.
func (q *Queries) FileGet(ctx context.Context, arg FileGetParams) (StoredFile, error) {
	row := q.db.QueryRow(ctx, fileGet, arg.ID, arg.CompanyID)
	var i StoredFile
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.OwnerType,
		&i.OwnerID,
		&i.ClauseID,
		&i.OriginalName,
		&i.StoredPath,
		&i.ContentType,
		&i.SizeBytes,
		&i.Checksum,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const fileList = `-- name: FileList :many
select id, company_id, owner_type, owner_id, clause_id, original_name, stored_path, content_type, size_bytes, checksum, uploaded_by, created_at, deleted_at from stored_files
where company_id = $1::uuid
  and ($2::boolean or deleted_at is null)
  and ($3::text is null or owner_type = $3::text)
  and ($4::uuid is null or owner_id = $4::uuid)
  and ($5::text is null or clause_id = $5::text)
order by created_at desc, id
limit $7::int offset $6::int
`

type FileListParams struct {
	CompanyID      uuid.UUID
	IncludeDeleted bool
	OwnerType      *string
	OwnerID        *uuid.UUID
	ClauseID       *string
	OffsetVal      int32
	LimitVal       int32
}

func (q *Queries) FileList(ctx context.Context, arg FileListParams) ([]StoredFile, error) {
	rows, err := q.db.Query(ctx, fileList,
		arg.CompanyID,
		arg.IncludeDeleted,
		arg.OwnerType,
		arg.OwnerID,
		arg.ClauseID,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoredFile
	for rows.Next() {
		var i StoredFile
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.OwnerType,
			&i.OwnerID,
			&i.ClauseID,
			&i.OriginalName,
			&i.StoredPath,
			&i.ContentType,
			&i.SizeBytes,
			&i.Checksum,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fileSoftDelete = `-- name: FileSoftDelete :execrows
update stored_files set deleted_at = $1::timestamptz
where id = $2::uuid and company_id = $3::uuid and deleted_at is null
`

type FileSoftDeleteParams struct {
	At        pgtype.Timestamptz
	ID        uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) FileSoftDelete(ctx context.Context, arg FileSoftDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, fileSoftDelete, arg.At, arg.ID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
