// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forecasts.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const forecastAnalyzerVisible = `-- name: ForecastAnalyzerVisible :one
select exists (
    select 1 from analyzers
    where id = $1
      and company_id = $2
      and ($3::boolean or building_id = any($4::uuid[]))
      and deleted_at is null
)
`

type ForecastAnalyzerVisibleParams struct {
	AnalyzerID   uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) ForecastAnalyzerVisible(ctx context.Context, arg ForecastAnalyzerVisibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, forecastAnalyzerVisible,
		arg.AnalyzerID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const forecastGapsByRun = `-- name: ForecastGapsByRun :many
select id, analyzer_id, generated_at, gap_start, gap_end, missing_hours from forecast_gaps
where analyzer_id = $1 and generated_at = $2
order by gap_start
`

type ForecastGapsByRunParams struct {
	AnalyzerID  uuid.UUID
	GeneratedAt pgtype.Timestamptz
}

func (q *Queries) ForecastGapsByRun(ctx context.Context, arg ForecastGapsByRunParams) ([]ForecastGap, error) {
	rows, err := q.db.Query(ctx, forecastGapsByRun, arg.AnalyzerID, arg.GeneratedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForecastGap
	for rows.Next() {
		var i ForecastGap
		if err := rows.Scan(
			&i.ID,
			&i.AnalyzerID,
			&i.GeneratedAt,
			&i.GapStart,
			&i.GapEnd,
			&i.MissingHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forecastInsertGaps = `-- name: ForecastInsertGaps :exec
insert into forecast_gaps (id, analyzer_id, generated_at, gap_start, gap_end, missing_hours)
select unnest($1::uuid[]),
       unnest($2::uuid[]),
       unnest($3::timestamptz[]),
       unnest($4::timestamptz[]),
       unnest($5::timestamptz[]),
       unnest($6::int[])
`

type ForecastInsertGapsParams struct {
	Ids          []uuid.UUID
	AnalyzerIds  []uuid.UUID
	GeneratedAts []pgtype.Timestamptz
	GapStarts    []pgtype.Timestamptz
	GapEnds      []pgtype.Timestamptz
	MissingHours []int32
}

// NOTE: TestEveryFunctionSQLcMustTypeIsDeclared currently flags the
// "forecast_gaps (" below as a call to an undeclared function — a known
// false positive being fixed in parallel on f1/task-8c; see the task report.
func (q *Queries) ForecastInsertGaps(ctx context.Context, arg ForecastInsertGapsParams) error {
	_, err := q.db.Exec(ctx, forecastInsertGaps,
		arg.Ids,
		arg.AnalyzerIds,
		arg.GeneratedAts,
		arg.GapStarts,
		arg.GapEnds,
		arg.MissingHours,
	)
	return err
}

const forecastLatestRun = `-- name: ForecastLatestRun :many
with latest as (
    select max(generated_at) as generated_at
    from forecasts
    where analyzer_id = $1
      and ts >= $2::timestamptz
      and ts < $3::timestamptz
)
select f.analyzer_id, f.ts, f.generated_at, f.horizon_hours, f.median, f.p10, f.p90, f.model_id, f.model_version from forecasts f, latest
where f.analyzer_id = $1
  and f.generated_at = latest.generated_at
  and f.ts >= $2::timestamptz
  and f.ts < $3::timestamptz
order by f.ts
`

type ForecastLatestRunParams struct {
	AnalyzerID uuid.UUID
	FromTs     pgtype.Timestamptz
	ToTs       pgtype.Timestamptz
}

// The most recent run (max generated_at) among the rows already inside the
// window, per repository.go's LatestRun doc. When there is no row in the
// window, latest.generated_at is null and the join below matches nothing —
// an empty slice, not an error.
func (q *Queries) ForecastLatestRun(ctx context.Context, arg ForecastLatestRunParams) ([]Forecast, error) {
	rows, err := q.db.Query(ctx, forecastLatestRun, arg.AnalyzerID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Forecast
	for rows.Next() {
		var i Forecast
		if err := rows.Scan(
			&i.AnalyzerID,
			&i.Ts,
			&i.GeneratedAt,
			&i.HorizonHours,
			&i.Median,
			&i.P10,
			&i.P90,
			&i.ModelID,
			&i.ModelVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forecastRange = `-- name: ForecastRange :many
select analyzer_id, ts, generated_at, horizon_hours, median, p10, p90, model_id, model_version from forecasts
where analyzer_id = $1
  and ts >= $2::timestamptz
  and ts < $3::timestamptz
order by ts, generated_at
`

type ForecastRangeParams struct {
	AnalyzerID uuid.UUID
	FromTs     pgtype.Timestamptz
	ToTs       pgtype.Timestamptz
}

func (q *Queries) ForecastRange(ctx context.Context, arg ForecastRangeParams) ([]Forecast, error) {
	rows, err := q.db.Query(ctx, forecastRange, arg.AnalyzerID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Forecast
	for rows.Next() {
		var i Forecast
		if err := rows.Scan(
			&i.AnalyzerID,
			&i.Ts,
			&i.GeneratedAt,
			&i.HorizonHours,
			&i.Median,
			&i.P10,
			&i.P90,
			&i.ModelID,
			&i.ModelVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forecastVisibleAnalyzerCount = `-- name: ForecastVisibleAnalyzerCount :one

select count(*) from analyzers
where id = any($1::uuid[])
  and company_id = $2
  and ($3::boolean or building_id = any($4::uuid[]))
  and deleted_at is null
`

type ForecastVisibleAnalyzerCountParams struct {
	AnalyzerIds  []uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// ForecastRepository's queries. forecasts and forecast_gaps have no
// company_id: every method joins through analyzers. BulkInsert's
// COPY-into-staging-then-upsert is plain SQL in forecasts.go, for the same
// reason ReadingRepository.BulkInsert's is.
func (q *Queries) ForecastVisibleAnalyzerCount(ctx context.Context, arg ForecastVisibleAnalyzerCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, forecastVisibleAnalyzerCount,
		arg.AnalyzerIds,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}
