// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forecasts.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const forecastAnalyzerVisible = `-- name: ForecastAnalyzerVisible :one
select exists (
    select 1 from analyzers
    where id = $1
      and company_id = $2
      and ($3::boolean or building_id = any($4::uuid[]))
      and deleted_at is null
)
`

type ForecastAnalyzerVisibleParams struct {
	AnalyzerID   uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// Used ONLY to choose an error, never to gate a data read — see
// ReadingAnalyzerVisible's comment in readings.sql for the same reasoning.
func (q *Queries) ForecastAnalyzerVisible(ctx context.Context, arg ForecastAnalyzerVisibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, forecastAnalyzerVisible,
		arg.AnalyzerID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const forecastGapsByRun = `-- name: ForecastGapsByRun :many
select fg.id, fg.analyzer_id, fg.generated_at, fg.gap_start, fg.gap_end, fg.missing_hours from forecast_gaps fg
join analyzers a on a.id = fg.analyzer_id
where fg.analyzer_id = $1
  and fg.generated_at = $2
  and a.company_id = $3
  and ($4::boolean or a.building_id = any($5::uuid[]))
  and a.deleted_at is null
order by fg.gap_start
`

type ForecastGapsByRunParams struct {
	AnalyzerID   uuid.UUID
	GeneratedAt  pgtype.Timestamptz
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) ForecastGapsByRun(ctx context.Context, arg ForecastGapsByRunParams) ([]ForecastGap, error) {
	rows, err := q.db.Query(ctx, forecastGapsByRun,
		arg.AnalyzerID,
		arg.GeneratedAt,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForecastGap
	for rows.Next() {
		var i ForecastGap
		if err := rows.Scan(
			&i.ID,
			&i.AnalyzerID,
			&i.GeneratedAt,
			&i.GapStart,
			&i.GapEnd,
			&i.MissingHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forecastInsertGaps = `-- name: ForecastInsertGaps :exec
insert into forecast_gaps (id, analyzer_id, generated_at, gap_start, gap_end, missing_hours)
select unnest($1::uuid[]),
       unnest($2::uuid[]),
       unnest($3::timestamptz[]),
       unnest($4::timestamptz[]),
       unnest($5::timestamptz[]),
       unnest($6::int[])
`

type ForecastInsertGapsParams struct {
	Ids          []uuid.UUID
	AnalyzerIds  []uuid.UUID
	GeneratedAts []pgtype.Timestamptz
	GapStarts    []pgtype.Timestamptz
	GapEnds      []pgtype.Timestamptz
	MissingHours []int32
}

// The batch-visibility check is ForecastVisibleAnalyzerIDs, run with `for
// share` inside the SAME transaction as this insert (forecasts.go) — this
// statement itself carries no further scope predicate because every
// analyzer_id it writes has already been locked-and-verified visible in that
// same transaction.
func (q *Queries) ForecastInsertGaps(ctx context.Context, arg ForecastInsertGapsParams) error {
	_, err := q.db.Exec(ctx, forecastInsertGaps,
		arg.Ids,
		arg.AnalyzerIds,
		arg.GeneratedAts,
		arg.GapStarts,
		arg.GapEnds,
		arg.MissingHours,
	)
	return err
}

const forecastLatestRun = `-- name: ForecastLatestRun :many
with latest as (
    select max(f.generated_at) as generated_at
    from forecasts f
    join analyzers a on a.id = f.analyzer_id
    where f.analyzer_id = $1
      and f.ts >= $2::timestamptz
      and f.ts < $3::timestamptz
      and a.company_id = $4
      and ($5::boolean or a.building_id = any($6::uuid[]))
      and a.deleted_at is null
)
select f.analyzer_id, f.ts, f.generated_at, f.horizon_hours, f.median, f.p10, f.p90, f.model_id, f.model_version from forecasts f
join analyzers a on a.id = f.analyzer_id
cross join latest
where f.analyzer_id = $1
  and f.generated_at = latest.generated_at
  and f.ts >= $2::timestamptz
  and f.ts < $3::timestamptz
  and a.company_id = $4
  and ($5::boolean or a.building_id = any($6::uuid[]))
  and a.deleted_at is null
order by f.ts
`

type ForecastLatestRunParams struct {
	AnalyzerID   uuid.UUID
	FromTs       pgtype.Timestamptz
	ToTs         pgtype.Timestamptz
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// The most recent run (max generated_at) among the rows already inside the
// window AND visible to the scope, per repository.go's LatestRun doc. When
// there is no such row, latest.generated_at is null and the final select's
// equality join matches nothing — an empty slice, not an error. Both the CTE
// and the final select carry the scope join independently.
func (q *Queries) ForecastLatestRun(ctx context.Context, arg ForecastLatestRunParams) ([]Forecast, error) {
	rows, err := q.db.Query(ctx, forecastLatestRun,
		arg.AnalyzerID,
		arg.FromTs,
		arg.ToTs,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Forecast
	for rows.Next() {
		var i Forecast
		if err := rows.Scan(
			&i.AnalyzerID,
			&i.Ts,
			&i.GeneratedAt,
			&i.HorizonHours,
			&i.Median,
			&i.P10,
			&i.P90,
			&i.ModelID,
			&i.ModelVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forecastRange = `-- name: ForecastRange :many
select f.analyzer_id, f.ts, f.generated_at, f.horizon_hours, f.median, f.p10, f.p90, f.model_id, f.model_version from forecasts f
join analyzers a on a.id = f.analyzer_id
where f.analyzer_id = $1
  and f.ts >= $2::timestamptz
  and f.ts < $3::timestamptz
  and a.company_id = $4
  and ($5::boolean or a.building_id = any($6::uuid[]))
  and a.deleted_at is null
order by f.ts, f.generated_at
`

type ForecastRangeParams struct {
	AnalyzerID   uuid.UUID
	FromTs       pgtype.Timestamptz
	ToTs         pgtype.Timestamptz
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// The join through analyzers carries the scope IN THIS QUERY.
func (q *Queries) ForecastRange(ctx context.Context, arg ForecastRangeParams) ([]Forecast, error) {
	rows, err := q.db.Query(ctx, forecastRange,
		arg.AnalyzerID,
		arg.FromTs,
		arg.ToTs,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Forecast
	for rows.Next() {
		var i Forecast
		if err := rows.Scan(
			&i.AnalyzerID,
			&i.Ts,
			&i.GeneratedAt,
			&i.HorizonHours,
			&i.Median,
			&i.P10,
			&i.P90,
			&i.ModelID,
			&i.ModelVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const forecastVisibleAnalyzerIDs = `-- name: ForecastVisibleAnalyzerIDs :many

select id from analyzers
where id = any($1::uuid[])
  and company_id = $2
  and ($3::boolean or building_id = any($4::uuid[]))
  and deleted_at is null
order by id
for share
`

type ForecastVisibleAnalyzerIDsParams struct {
	AnalyzerIds  []uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// ForecastRepository's queries. forecasts and forecast_gaps have no
// company_id: every method's DATA READ carries the scope in its own join
// through analyzers, never a bare read guarded only by a separate Go-side
// check. BulkInsert's COPY-into-staging-then-upsert is plain SQL in
// forecasts.go, for the same reason ReadingRepository.BulkInsert's is.
// Returns the subset of analyzer_ids visible to the scope, AND LOCKS them
// (`for share`) for the rest of the caller's transaction — see
// ReadingVisibleAnalyzerIDs in readings.sql. BulkInsert and RecordGaps both
// run this inside their transaction, never on the bare pool before one
// begins, and both compare the result's length against the batch's DISTINCT
// analyzer ids before writing anything.
func (q *Queries) ForecastVisibleAnalyzerIDs(ctx context.Context, arg ForecastVisibleAnalyzerIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, forecastVisibleAnalyzerIDs,
		arg.AnalyzerIds,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
