// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: generation.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const generationAnchorGet = `-- name: GenerationAnchorGet :one

select ga.analyzer_id, ga.anchor_ts, ga.active_export, ga.source, ga.updated_at from generation_anchors ga
join analyzers a on a.id = ga.analyzer_id
where ga.analyzer_id = $1
  and a.company_id = $2
  and ($3::boolean or a.building_id = any($4::uuid[]))
  and a.deleted_at is null
`

type GenerationAnchorGetParams struct {
	AnalyzerID   uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// GenerationRepository's queries. generation_anchors has no company_id (see
// repository.go's "ROWS WITHOUT company_id" header): every method joins
// through analyzers, or — for the write — validates the analyzer's
// visibility IN the write statement itself.
// A single query covers BOTH "analyzer not visible" and "no anchor yet":
// both yield zero rows, and repository.go's GenerationRepository.Anchor doc
// says both return ErrNotFound.
func (q *Queries) GenerationAnchorGet(ctx context.Context, arg GenerationAnchorGetParams) (GenerationAnchor, error) {
	row := q.db.QueryRow(ctx, generationAnchorGet,
		arg.AnalyzerID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i GenerationAnchor
	err := row.Scan(
		&i.AnalyzerID,
		&i.AnchorTs,
		&i.ActiveExport,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}

const generationAnchorUpsert = `-- name: GenerationAnchorUpsert :execrows
insert into generation_anchors (analyzer_id, anchor_ts, active_export, source)
select a.id, $1::timestamptz, $2::numeric, $3::text
from analyzers a
where a.id = $4
  and a.company_id = $5
  and a.deleted_at is null
  and ($6::boolean or a.building_id = any($7::uuid[]))
on conflict (analyzer_id) do update set
    anchor_ts     = excluded.anchor_ts,
    active_export = excluded.active_export,
    source        = excluded.source,
    updated_at    = now()
`

type GenerationAnchorUpsertParams struct {
	AnchorTs     pgtype.Timestamptz
	ActiveExport pgtype.Numeric
	Source       string
	AnalyzerID   uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// The select-from-analyzers source IS the visibility check (F1 ba2fb97
// pattern, repeated from CursorRecordSuccess): an invisible analyzer_id
// makes the source empty, so nothing is inserted or updated and execrows
// reports 0, which the repository reads as ErrNotFound. This is the tenant
// predicate for this write, embedded in the write statement itself — never a
// Scope.AllowsBuilding pre-check against the stored analyzer_id, which would
// be using AllowsBuilding to validate a stored foreign key (Scope.
// AllowsBuilding's own doc explains why that is unsafe).
//
// One atomic statement upserts on analyzer_id: a fresh reconciliation always
// replaces the prior anchor rather than accumulating history.
//
// updated_at is owned by SQL, never the caller: the insert list omits it
// entirely (the column default `now()` stamps a fresh row) and the conflict
// branch stamps it explicitly with `now()` — never `excluded.updated_at`,
// which would let a caller backdate or forward-date the bookkeeping
// timestamp with its own wall clock.
func (q *Queries) GenerationAnchorUpsert(ctx context.Context, arg GenerationAnchorUpsertParams) (int64, error) {
	result, err := q.db.Exec(ctx, generationAnchorUpsert,
		arg.AnchorTs,
		arg.ActiveExport,
		arg.Source,
		arg.AnalyzerID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
