// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AlarmType string

const (
	AlarmTypeReactiveLimit       AlarmType = "reactive_limit"
	AlarmTypeDataCommunication   AlarmType = "data_communication"
	AlarmTypeCurrentVoltagePower AlarmType = "current_voltage_power"
	AlarmTypeInvoiceIncrease     AlarmType = "invoice_increase"
)

func (e *AlarmType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlarmType(s)
	case string:
		*e = AlarmType(s)
	default:
		return fmt.Errorf("unsupported scan type for AlarmType: %T", src)
	}
	return nil
}

type NullAlarmType struct {
	AlarmType AlarmType
	Valid     bool // Valid is true if AlarmType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlarmType) Scan(value interface{}) error {
	if value == nil {
		ns.AlarmType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlarmType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlarmType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlarmType), nil
}

type BillScope string

const (
	BillScopeAnalyzer BillScope = "analyzer"
	BillScopeBuilding BillScope = "building"
	BillScopeCompany  BillScope = "company"
)

func (e *BillScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillScope(s)
	case string:
		*e = BillScope(s)
	default:
		return fmt.Errorf("unsupported scan type for BillScope: %T", src)
	}
	return nil
}

type NullBillScope struct {
	BillScope BillScope
	Valid     bool // Valid is true if BillScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillScope) Scan(value interface{}) error {
	if value == nil {
		ns.BillScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillScope), nil
}

type BillStatus string

const (
	BillStatusDraft      BillStatus = "draft"
	BillStatusIssued     BillStatus = "issued"
	BillStatusFlagged    BillStatus = "flagged"
	BillStatusSuperseded BillStatus = "superseded"
)

func (e *BillStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillStatus(s)
	case string:
		*e = BillStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BillStatus: %T", src)
	}
	return nil
}

type NullBillStatus struct {
	BillStatus BillStatus
	Valid      bool // Valid is true if BillStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BillStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillStatus), nil
}

type CarbonScope string

const (
	CarbonScopeScope1 CarbonScope = "scope_1"
	CarbonScopeScope2 CarbonScope = "scope_2"
	CarbonScopeScope3 CarbonScope = "scope_3"
)

func (e *CarbonScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CarbonScope(s)
	case string:
		*e = CarbonScope(s)
	default:
		return fmt.Errorf("unsupported scan type for CarbonScope: %T", src)
	}
	return nil
}

type NullCarbonScope struct {
	CarbonScope CarbonScope
	Valid       bool // Valid is true if CarbonScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCarbonScope) Scan(value interface{}) error {
	if value == nil {
		ns.CarbonScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CarbonScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCarbonScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CarbonScope), nil
}

type CarbonStatus string

const (
	CarbonStatusPending  CarbonStatus = "pending"
	CarbonStatusApproved CarbonStatus = "approved"
	CarbonStatusRejected CarbonStatus = "rejected"
)

func (e *CarbonStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CarbonStatus(s)
	case string:
		*e = CarbonStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CarbonStatus: %T", src)
	}
	return nil
}

type NullCarbonStatus struct {
	CarbonStatus CarbonStatus
	Valid        bool // Valid is true if CarbonStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCarbonStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CarbonStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CarbonStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCarbonStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CarbonStatus), nil
}

type CurrencyCode string

const (
	CurrencyCodeTRY CurrencyCode = "TRY"
	CurrencyCodeUSD CurrencyCode = "USD"
	CurrencyCodeEUR CurrencyCode = "EUR"
)

func (e *CurrencyCode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CurrencyCode(s)
	case string:
		*e = CurrencyCode(s)
	default:
		return fmt.Errorf("unsupported scan type for CurrencyCode: %T", src)
	}
	return nil
}

type NullCurrencyCode struct {
	CurrencyCode CurrencyCode
	Valid        bool // Valid is true if CurrencyCode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrencyCode) Scan(value interface{}) error {
	if value == nil {
		ns.CurrencyCode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CurrencyCode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrencyCode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CurrencyCode), nil
}

type DistributionUserGroup string

const (
	DistributionUserGroupResidential     DistributionUserGroup = "residential"
	DistributionUserGroupResidentialPlus DistributionUserGroup = "residential_plus"
	DistributionUserGroupCommercial      DistributionUserGroup = "commercial"
	DistributionUserGroupCommercialPlus  DistributionUserGroup = "commercial_plus"
	DistributionUserGroupIndustrial      DistributionUserGroup = "industrial"
	DistributionUserGroupAgricultural    DistributionUserGroup = "agricultural"
	DistributionUserGroupLighting        DistributionUserGroup = "lighting"
	DistributionUserGroupMartyrsFamilies DistributionUserGroup = "martyrs_families"
	DistributionUserGroupPublicLighting  DistributionUserGroup = "public_lighting"
)

func (e *DistributionUserGroup) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DistributionUserGroup(s)
	case string:
		*e = DistributionUserGroup(s)
	default:
		return fmt.Errorf("unsupported scan type for DistributionUserGroup: %T", src)
	}
	return nil
}

type NullDistributionUserGroup struct {
	DistributionUserGroup DistributionUserGroup
	Valid                 bool // Valid is true if DistributionUserGroup is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDistributionUserGroup) Scan(value interface{}) error {
	if value == nil {
		ns.DistributionUserGroup, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DistributionUserGroup.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDistributionUserGroup) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DistributionUserGroup), nil
}

type EnergyType string

const (
	EnergyTypeGridEnergy  EnergyType = "grid_energy"
	EnergyTypeGreenEnergy EnergyType = "green_energy"
)

func (e *EnergyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnergyType(s)
	case string:
		*e = EnergyType(s)
	default:
		return fmt.Errorf("unsupported scan type for EnergyType: %T", src)
	}
	return nil
}

type NullEnergyType struct {
	EnergyType EnergyType
	Valid      bool // Valid is true if EnergyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnergyType) Scan(value interface{}) error {
	if value == nil {
		ns.EnergyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnergyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnergyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnergyType), nil
}

type ExtraChargeBasis string

const (
	ExtraChargeBasisPerKwh          ExtraChargeBasis = "per_kwh"
	ExtraChargeBasisPerContractedKw ExtraChargeBasis = "per_contracted_kw"
	ExtraChargeBasisPerMaxDemandKw  ExtraChargeBasis = "per_max_demand_kw"
	ExtraChargeBasisFixedPerPeriod  ExtraChargeBasis = "fixed_per_period"
	ExtraChargeBasisPctOfEnergy     ExtraChargeBasis = "pct_of_energy"
)

func (e *ExtraChargeBasis) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExtraChargeBasis(s)
	case string:
		*e = ExtraChargeBasis(s)
	default:
		return fmt.Errorf("unsupported scan type for ExtraChargeBasis: %T", src)
	}
	return nil
}

type NullExtraChargeBasis struct {
	ExtraChargeBasis ExtraChargeBasis
	Valid            bool // Valid is true if ExtraChargeBasis is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExtraChargeBasis) Scan(value interface{}) error {
	if value == nil {
		ns.ExtraChargeBasis, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExtraChargeBasis.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExtraChargeBasis) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExtraChargeBasis), nil
}

type GenerationUsage string

const (
	GenerationUsageNone                    GenerationUsage = "none"
	GenerationUsageSubtractFromConsumption GenerationUsage = "subtract_from_consumption"
	GenerationUsageSubtractFromTotal       GenerationUsage = "subtract_from_total"
)

func (e *GenerationUsage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenerationUsage(s)
	case string:
		*e = GenerationUsage(s)
	default:
		return fmt.Errorf("unsupported scan type for GenerationUsage: %T", src)
	}
	return nil
}

type NullGenerationUsage struct {
	GenerationUsage GenerationUsage
	Valid           bool // Valid is true if GenerationUsage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenerationUsage) Scan(value interface{}) error {
	if value == nil {
		ns.GenerationUsage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenerationUsage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenerationUsage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenerationUsage), nil
}

type IntegrationProvider string

const (
	IntegrationProviderOsos    IntegrationProvider = "osos"
	IntegrationProviderGridbox IntegrationProvider = "gridbox"
	IntegrationProviderAril    IntegrationProvider = "aril"
	IntegrationProviderPm5340  IntegrationProvider = "pm5340"
	IntegrationProviderIsolar  IntegrationProvider = "isolar"
)

func (e *IntegrationProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IntegrationProvider(s)
	case string:
		*e = IntegrationProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for IntegrationProvider: %T", src)
	}
	return nil
}

type NullIntegrationProvider struct {
	IntegrationProvider IntegrationProvider
	Valid               bool // Valid is true if IntegrationProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIntegrationProvider) Scan(value interface{}) error {
	if value == nil {
		ns.IntegrationProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IntegrationProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIntegrationProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IntegrationProvider), nil
}

type MoneyRoundingMode string

const (
	MoneyRoundingModeHalfUp   MoneyRoundingMode = "half_up"
	MoneyRoundingModeHalfEven MoneyRoundingMode = "half_even"
)

func (e *MoneyRoundingMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MoneyRoundingMode(s)
	case string:
		*e = MoneyRoundingMode(s)
	default:
		return fmt.Errorf("unsupported scan type for MoneyRoundingMode: %T", src)
	}
	return nil
}

type NullMoneyRoundingMode struct {
	MoneyRoundingMode MoneyRoundingMode
	Valid             bool // Valid is true if MoneyRoundingMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMoneyRoundingMode) Scan(value interface{}) error {
	if value == nil {
		ns.MoneyRoundingMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MoneyRoundingMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMoneyRoundingMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MoneyRoundingMode), nil
}

type NotifyChannel string

const (
	NotifyChannelEmail NotifyChannel = "email"
	NotifyChannelSms   NotifyChannel = "sms"
)

func (e *NotifyChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotifyChannel(s)
	case string:
		*e = NotifyChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for NotifyChannel: %T", src)
	}
	return nil
}

type NullNotifyChannel struct {
	NotifyChannel NotifyChannel
	Valid         bool // Valid is true if NotifyChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotifyChannel) Scan(value interface{}) error {
	if value == nil {
		ns.NotifyChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotifyChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotifyChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotifyChannel), nil
}

type PanelOrientation string

const (
	PanelOrientationN  PanelOrientation = "n"
	PanelOrientationS  PanelOrientation = "s"
	PanelOrientationE  PanelOrientation = "e"
	PanelOrientationW  PanelOrientation = "w"
	PanelOrientationNe PanelOrientation = "ne"
	PanelOrientationSe PanelOrientation = "se"
	PanelOrientationNw PanelOrientation = "nw"
	PanelOrientationSw PanelOrientation = "sw"
)

func (e *PanelOrientation) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PanelOrientation(s)
	case string:
		*e = PanelOrientation(s)
	default:
		return fmt.Errorf("unsupported scan type for PanelOrientation: %T", src)
	}
	return nil
}

type NullPanelOrientation struct {
	PanelOrientation PanelOrientation
	Valid            bool // Valid is true if PanelOrientation is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPanelOrientation) Scan(value interface{}) error {
	if value == nil {
		ns.PanelOrientation, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PanelOrientation.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPanelOrientation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PanelOrientation), nil
}

type PeriodUnit string

const (
	PeriodUnitHours PeriodUnit = "hours"
	PeriodUnitDays  PeriodUnit = "days"
)

func (e *PeriodUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PeriodUnit(s)
	case string:
		*e = PeriodUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for PeriodUnit: %T", src)
	}
	return nil
}

type NullPeriodUnit struct {
	PeriodUnit PeriodUnit
	Valid      bool // Valid is true if PeriodUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPeriodUnit) Scan(value interface{}) error {
	if value == nil {
		ns.PeriodUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PeriodUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPeriodUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PeriodUnit), nil
}

type PlantSelection string

const (
	PlantSelectionAll     PlantSelection = "all"
	PlantSelectionGrid    PlantSelection = "grid"
	PlantSelectionRooftop PlantSelection = "rooftop"
)

func (e *PlantSelection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlantSelection(s)
	case string:
		*e = PlantSelection(s)
	default:
		return fmt.Errorf("unsupported scan type for PlantSelection: %T", src)
	}
	return nil
}

type NullPlantSelection struct {
	PlantSelection PlantSelection
	Valid          bool // Valid is true if PlantSelection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlantSelection) Scan(value interface{}) error {
	if value == nil {
		ns.PlantSelection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlantSelection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlantSelection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlantSelection), nil
}

type PriceSource string

const (
	PriceSourceKbk   PriceSource = "kbk"
	PriceSourceFixed PriceSource = "fixed"
)

func (e *PriceSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PriceSource(s)
	case string:
		*e = PriceSource(s)
	default:
		return fmt.Errorf("unsupported scan type for PriceSource: %T", src)
	}
	return nil
}

type NullPriceSource struct {
	PriceSource PriceSource
	Valid       bool // Valid is true if PriceSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriceSource) Scan(value interface{}) error {
	if value == nil {
		ns.PriceSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PriceSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriceSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PriceSource), nil
}

type PriceType string

const (
	PriceTypeSingleTime PriceType = "single_time"
	PriceTypeMultiTime  PriceType = "multi_time"
)

func (e *PriceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PriceType(s)
	case string:
		*e = PriceType(s)
	default:
		return fmt.Errorf("unsupported scan type for PriceType: %T", src)
	}
	return nil
}

type NullPriceType struct {
	PriceType PriceType
	Valid     bool // Valid is true if PriceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriceType) Scan(value interface{}) error {
	if value == nil {
		ns.PriceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PriceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PriceType), nil
}

type ReactivePenaltyBasis string

const (
	ReactivePenaltyBasisWholeQuantity   ReactivePenaltyBasis = "whole_quantity"
	ReactivePenaltyBasisExcessOverLimit ReactivePenaltyBasis = "excess_over_limit"
)

func (e *ReactivePenaltyBasis) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReactivePenaltyBasis(s)
	case string:
		*e = ReactivePenaltyBasis(s)
	default:
		return fmt.Errorf("unsupported scan type for ReactivePenaltyBasis: %T", src)
	}
	return nil
}

type NullReactivePenaltyBasis struct {
	ReactivePenaltyBasis ReactivePenaltyBasis
	Valid                bool // Valid is true if ReactivePenaltyBasis is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReactivePenaltyBasis) Scan(value interface{}) error {
	if value == nil {
		ns.ReactivePenaltyBasis, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReactivePenaltyBasis.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReactivePenaltyBasis) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReactivePenaltyBasis), nil
}

type ReadingKind string

const (
	ReadingKindLoadProfile  ReadingKind = "load_profile"
	ReadingKindDaily        ReadingKind = "daily"
	ReadingKindBilling      ReadingKind = "billing"
	ReadingKindReset        ReadingKind = "reset"
	ReadingKindCurrentIndex ReadingKind = "current_index"
)

func (e *ReadingKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReadingKind(s)
	case string:
		*e = ReadingKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ReadingKind: %T", src)
	}
	return nil
}

type NullReadingKind struct {
	ReadingKind ReadingKind
	Valid       bool // Valid is true if ReadingKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReadingKind) Scan(value interface{}) error {
	if value == nil {
		ns.ReadingKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReadingKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReadingKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReadingKind), nil
}

type ReportStatus string

const (
	ReportStatusPending   ReportStatus = "pending"
	ReportStatusCompleted ReportStatus = "completed"
	ReportStatusError     ReportStatus = "error"
)

func (e *ReportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportStatus(s)
	case string:
		*e = ReportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportStatus: %T", src)
	}
	return nil
}

type NullReportStatus struct {
	ReportStatus ReportStatus
	Valid        bool // Valid is true if ReportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportStatus), nil
}

type ReportType string

const (
	ReportTypeMonthly ReportType = "monthly"
	ReportTypeYearly  ReportType = "yearly"
)

func (e *ReportType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportType(s)
	case string:
		*e = ReportType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportType: %T", src)
	}
	return nil
}

type NullReportType struct {
	ReportType ReportType
	Valid      bool // Valid is true if ReportType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportType) Scan(value interface{}) error {
	if value == nil {
		ns.ReportType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportType), nil
}

type SupplyCompany string

const (
	SupplyCompanyIncumbent SupplyCompany = "incumbent"
	SupplyCompanyPrivate   SupplyCompany = "private"
)

func (e *SupplyCompany) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SupplyCompany(s)
	case string:
		*e = SupplyCompany(s)
	default:
		return fmt.Errorf("unsupported scan type for SupplyCompany: %T", src)
	}
	return nil
}

type NullSupplyCompany struct {
	SupplyCompany SupplyCompany
	Valid         bool // Valid is true if SupplyCompany is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSupplyCompany) Scan(value interface{}) error {
	if value == nil {
		ns.SupplyCompany, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SupplyCompany.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSupplyCompany) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SupplyCompany), nil
}

type TariffTerm string

const (
	TariffTermMonomial TariffTerm = "monomial"
	TariffTermBinomial TariffTerm = "binomial"
)

func (e *TariffTerm) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TariffTerm(s)
	case string:
		*e = TariffTerm(s)
	default:
		return fmt.Errorf("unsupported scan type for TariffTerm: %T", src)
	}
	return nil
}

type NullTariffTerm struct {
	TariffTerm TariffTerm
	Valid      bool // Valid is true if TariffTerm is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTariffTerm) Scan(value interface{}) error {
	if value == nil {
		ns.TariffTerm, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TariffTerm.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTariffTerm) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TariffTerm), nil
}

type TieringMode string

const (
	TieringModeSplitAtThreshold       TieringMode = "split_at_threshold"
	TieringModeWholeConsumptionSwitch TieringMode = "whole_consumption_switch"
)

func (e *TieringMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TieringMode(s)
	case string:
		*e = TieringMode(s)
	default:
		return fmt.Errorf("unsupported scan type for TieringMode: %T", src)
	}
	return nil
}

type NullTieringMode struct {
	TieringMode TieringMode
	Valid       bool // Valid is true if TieringMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTieringMode) Scan(value interface{}) error {
	if value == nil {
		ns.TieringMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TieringMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTieringMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TieringMode), nil
}

type UserRole string

const (
	UserRoleAdmin                 UserRole = "admin"
	UserRoleCompanyAdmin          UserRole = "company_admin"
	UserRoleCompanyReadonlyAdmin  UserRole = "company_readonly_admin"
	UserRoleBuildingAdmin         UserRole = "building_admin"
	UserRoleBuildingReadonlyAdmin UserRole = "building_readonly_admin"
	UserRoleDemo                  UserRole = "demo"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VoltageLevel string

const (
	VoltageLevelLv VoltageLevel = "lv"
	VoltageLevelMv VoltageLevel = "mv"
)

func (e *VoltageLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VoltageLevel(s)
	case string:
		*e = VoltageLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for VoltageLevel: %T", src)
	}
	return nil
}

type NullVoltageLevel struct {
	VoltageLevel VoltageLevel
	Valid        bool // Valid is true if VoltageLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVoltageLevel) Scan(value interface{}) error {
	if value == nil {
		ns.VoltageLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VoltageLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVoltageLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VoltageLevel), nil
}

type Alarm struct {
	ID                              uuid.UUID
	CompanyID                       uuid.UUID
	Name                            string
	Type                            AlarmType
	IsEnabled                       bool
	InductiveRatioThreshold         pgtype.Numeric
	InductivePeriodValue            *int32
	InductivePeriodUnit             NullPeriodUnit
	CapacitiveRatioThreshold        pgtype.Numeric
	CapacitivePeriodValue           *int32
	CapacitivePeriodUnit            NullPeriodUnit
	ActiveConsumptionMax            pgtype.Numeric
	ActiveConsumptionMaxPeriodValue *int32
	ActiveConsumptionMaxPeriodUnit  NullPeriodUnit
	ActiveConsumptionMin            pgtype.Numeric
	ActiveConsumptionMinPeriodValue *int32
	ActiveConsumptionMinPeriodUnit  NullPeriodUnit
	CommunicationThresholdHours     *int32
	VoltageMax                      pgtype.Numeric
	VoltageMin                      pgtype.Numeric
	PowerMax                        pgtype.Numeric
	PowerMin                        pgtype.Numeric
	InvoiceThresholdPct             pgtype.Numeric
	NotificationFrequencyValue      *int32
	NotificationFrequencyUnit       NullPeriodUnit
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
	DeletedAt                       pgtype.Timestamptz
}

type AlarmAnalyzer struct {
	AlarmID    uuid.UUID
	AnalyzerID uuid.UUID
}

type AlarmChannel struct {
	AlarmID uuid.UUID
	Channel NotifyChannel
	Target  string
}

type AlarmEvent struct {
	ID                uuid.UUID
	AlarmID           uuid.UUID
	AnalyzerID        *uuid.UUID
	TriggeredAt       pgtype.Timestamptz
	Message           string
	Detail            []byte
	NotifiedAt        pgtype.Timestamptz
	NotificationError *string
}

type AlarmFiredBill struct {
	AlarmID uuid.UUID
	BillID  uuid.UUID
}

type Analyzer struct {
	ID                 uuid.UUID
	CompanyID          uuid.UUID
	BuildingID         *uuid.UUID
	Provider           IntegrationProvider
	ProviderSubtype    string
	InstallationNumber string
	CustomerName       *string
	Address            *string
	Province           *string
	District           *string
	Neighbourhood      *string
	Street             *string
	TariffType         *string
	TariffKind         *string
	InstallationKind   *string
	InstalledPowerKw   pgtype.Numeric
	MeterNumber        *string
	MeterModel         *string
	MeterMultiplier    pgtype.Numeric
	CounterpartyNo     *string
	MeteringPointName  *string
	Latitude           pgtype.Numeric
	Longitude          pgtype.Numeric
	EtsoCode           *string
	DefinitionType     *int16
	LastReadingAt      pgtype.Timestamptz
	IsActive           bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type AuditLog struct {
	ID         int64
	CompanyID  *uuid.UUID
	UserID     *uuid.UUID
	Action     string
	EntityType string
	EntityID   *uuid.UUID
	Before     []byte
	After      []byte
	Ip         *netip.Addr
	CreatedAt  pgtype.Timestamptz
}

type Bill struct {
	ID                      uuid.UUID
	CompanyID               uuid.UUID
	BuildingID              *uuid.UUID
	AnalyzerID              *uuid.UUID
	Scope                   BillScope
	PeriodKey               string
	PeriodStart             pgtype.Timestamptz
	PeriodEnd               pgtype.Timestamptz
	DaysInPeriod            int32
	TariffID                *uuid.UUID
	TariffEffectiveFrom     pgtype.Date
	ActiveImport            pgtype.Numeric
	T1Kwh                   pgtype.Numeric
	T2Kwh                   pgtype.Numeric
	T3Kwh                   pgtype.Numeric
	InductiveKvarh          pgtype.Numeric
	CapacitiveKvarh         pgtype.Numeric
	ActiveExport            pgtype.Numeric
	NetConsumption          pgtype.Numeric
	LowTierKwh              pgtype.Numeric
	HighTierKwh             pgtype.Numeric
	MaxDemandKw             pgtype.Numeric
	TieredApplied           bool
	IndexStart              []byte
	IndexEnd                []byte
	EffectiveEnergyPrice    pgtype.Numeric
	LowTierPrice            pgtype.Numeric
	HighTierPrice           pgtype.Numeric
	EnergyCost              pgtype.Numeric
	DistributionCost        pgtype.Numeric
	GreenEnergyCost         pgtype.Numeric
	PowerCost               pgtype.Numeric
	DemandOverrunCost       pgtype.Numeric
	ReactivePenalty         pgtype.Numeric
	OtherTaxesCost          pgtype.Numeric
	VatBase                 pgtype.Numeric
	VatCost                 pgtype.Numeric
	GenerationCredit        pgtype.Numeric
	TotalCost               pgtype.Numeric
	InductiveRatio          pgtype.Numeric
	CapacitiveRatio         pgtype.Numeric
	InductiveThreshold      pgtype.Numeric
	CapacitiveThreshold     pgtype.Numeric
	ReactivePenaltyApplied  bool
	ReactivePowerPrice      pgtype.Numeric
	GenerationUsage         GenerationUsage
	GenerationPricePerKwh   pgtype.Numeric
	PtfYekdemUsed           bool
	PtfHoursMatched         *int32
	PtfHoursMissing         *int32
	PtfAverage              pgtype.Numeric
	YekdemUsed              pgtype.Numeric
	Status                  BillStatus
	FlagReason              *string
	PdfPath                 *string
	ComputedAt              pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	Currency                CurrencyCode
	ExtraChargesCost        pgtype.Numeric
	DemandDataAvailable     bool
	PtfHoursExpected        *int32
	ConsumptionHoursMissing *int32
}

type BillHourlyDetail struct {
	BillID      uuid.UUID
	Ts          pgtype.Timestamptz
	Consumption pgtype.Numeric
	Ptf         pgtype.Numeric
	Yekdem      pgtype.Numeric
	Kbk         pgtype.Numeric
	UnitPrice   pgtype.Numeric
	Cost        pgtype.Numeric
}

type BillLine struct {
	ID        uuid.UUID
	BillID    uuid.UUID
	Code      string
	Label     string
	Quantity  pgtype.Numeric
	Unit      *string
	UnitPrice pgtype.Numeric
	RatePct   pgtype.Numeric
	Amount    pgtype.Numeric
	SortOrder int16
}

type BillMember struct {
	BillID     uuid.UUID
	AnalyzerID uuid.UUID
}

type BillingParameter struct {
	EffectiveFrom               pgtype.Date
	ReactivePenaltyBasis        ReactivePenaltyBasis
	ReactiveExemptBelowKw       pgtype.Numeric
	ReactiveExemptTerms         []TariffTerm
	ReactiveExemptUserGroups    []DistributionUserGroup
	ReactiveGenerationExemptKwh pgtype.Numeric
	ReactiveBands               []byte
	TieringGroups               []byte
	TieringMode                 TieringMode
	TieringVoltageLevels        []VoltageLevel
	TieringSupplyCompanies      []SupplyCompany
	PtfMissingHourTolerance     pgtype.Numeric
	DemandOverrunMultiplier     pgtype.Numeric
	MoneyRoundingMode           MoneyRoundingMode
	CreatedAt                   pgtype.Timestamptz
}

type Building struct {
	ID                uuid.UUID
	CompanyID         uuid.UUID
	Name              string
	Address           *string
	Latitude          pgtype.Numeric
	Longitude         pgtype.Numeric
	Floors            *int32
	PersonnelCount    *int32
	TotalAreaM2       pgtype.Numeric
	Sector            *string
	ResponsibleUserID *uuid.UUID
	BillCutoffDay     int16
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type BuildingContact struct {
	ID         uuid.UUID
	BuildingID uuid.UUID
	Name       *string
	Phone      *string
	SortOrder  int16
}

type CalendarEvent struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
	Title     string
	StartsAt  pgtype.Timestamptz
	EndsAt    pgtype.Timestamptz
	AllDay    bool
	Colour    *string
	CreatedBy *uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type CarbonActivity struct {
	ID                   uuid.UUID
	CompanyID            uuid.UUID
	BuildingID           uuid.UUID
	MainCategory         string
	SubCategory          string
	ActivityType         string
	PeriodStart          pgtype.Date
	PeriodEnd            pgtype.Date
	Quantity             pgtype.Numeric
	Unit                 string
	FactorID             *uuid.UUID
	FactorKey            *string
	FactorValue          pgtype.Numeric
	ConversionMultiplier pgtype.Numeric
	EmissionKgco2e       pgtype.Numeric
	Scope                CarbonScope
	IsoCategory          string
	Description          *string
	Details              []byte
	Status               CarbonStatus
	IsAutomated          bool
	CreatedBy            *uuid.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type CarbonReport struct {
	ID         uuid.UUID
	CompanyID  uuid.UUID
	BuildingID uuid.UUID
	Name       string
	ReportType string
	Period     string
	Payload    []byte
	PdfPath    *string
	CreatedAt  pgtype.Timestamptz
}

type CarbonSelectedActivity struct {
	CompanyID   uuid.UUID
	BuildingID  uuid.UUID
	ActivityKey string
}

type Company struct {
	ID             uuid.UUID
	Name           string
	Address        *string
	TotalAreaM2    pgtype.Numeric
	PersonnelCount *int32
	ContactName    *string
	ContactPhone   *string
	Sector         *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type CompanyVacation struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Description *string
}

type CompanyWeekendDay struct {
	CompanyID uuid.UUID
	DayOfWeek int16
}

type ConsumptionAnomaly struct {
	ID             uuid.UUID
	AnalyzerID     uuid.UUID
	PeriodStart    pgtype.Timestamptz
	PeriodEnd      pgtype.Timestamptz
	Reason         string
	Detail         []byte
	ResolvedAt     pgtype.Timestamptz
	ResolvedBy     *uuid.UUID
	Resolution     *string
	OverrideValues []byte
	CreatedAt      pgtype.Timestamptz
}

type ConsumptionDaily struct {
	AnalyzerID            uuid.UUID
	Bucket                pgtype.Timestamptz
	ActiveImportStart     pgtype.Numeric
	ActiveImportEnd       pgtype.Numeric
	ActiveConsumption     pgtype.Numeric
	InductiveConsumption  pgtype.Numeric
	CapacitiveConsumption pgtype.Numeric
	T1Consumption         pgtype.Numeric
	T2Consumption         pgtype.Numeric
	T3Consumption         pgtype.Numeric
	ActiveGeneration      pgtype.Numeric
	InductiveGeneration   pgtype.Numeric
	CapacitiveGeneration  pgtype.Numeric
	T1Generation          pgtype.Numeric
	T2Generation          pgtype.Numeric
	T3Generation          pgtype.Numeric
	MaxDemandKw           pgtype.Numeric
	ActiveIndex           pgtype.Numeric
	InductiveIndex        pgtype.Numeric
	CapacitiveIndex       pgtype.Numeric
	T1Index               pgtype.Numeric
	T2Index               pgtype.Numeric
	T3Index               pgtype.Numeric
	ActiveGenerationIndex pgtype.Numeric
	ReadingCount          int64
}

type ConsumptionHourly struct {
	AnalyzerID            uuid.UUID
	Bucket                pgtype.Timestamptz
	ActiveImportStart     pgtype.Numeric
	ActiveImportEnd       pgtype.Numeric
	ActiveConsumption     pgtype.Numeric
	InductiveConsumption  pgtype.Numeric
	CapacitiveConsumption pgtype.Numeric
	T1Consumption         pgtype.Numeric
	T2Consumption         pgtype.Numeric
	T3Consumption         pgtype.Numeric
	ActiveGeneration      pgtype.Numeric
	InductiveGeneration   pgtype.Numeric
	CapacitiveGeneration  pgtype.Numeric
	T1Generation          pgtype.Numeric
	T2Generation          pgtype.Numeric
	T3Generation          pgtype.Numeric
	MaxDemandKw           pgtype.Numeric
	ActiveIndex           pgtype.Numeric
	InductiveIndex        pgtype.Numeric
	CapacitiveIndex       pgtype.Numeric
	T1Index               pgtype.Numeric
	T2Index               pgtype.Numeric
	T3Index               pgtype.Numeric
	ActiveGenerationIndex pgtype.Numeric
	ReadingCount          int64
}

type ConsumptionMonthly struct {
	AnalyzerID            uuid.UUID
	Bucket                pgtype.Timestamptz
	ActiveImportStart     pgtype.Numeric
	ActiveImportEnd       pgtype.Numeric
	ActiveConsumption     pgtype.Numeric
	InductiveConsumption  pgtype.Numeric
	CapacitiveConsumption pgtype.Numeric
	T1Consumption         pgtype.Numeric
	T2Consumption         pgtype.Numeric
	T3Consumption         pgtype.Numeric
	ActiveGeneration      pgtype.Numeric
	InductiveGeneration   pgtype.Numeric
	CapacitiveGeneration  pgtype.Numeric
	T1Generation          pgtype.Numeric
	T2Generation          pgtype.Numeric
	T3Generation          pgtype.Numeric
	MaxDemandKw           pgtype.Numeric
	ActiveIndex           pgtype.Numeric
	InductiveIndex        pgtype.Numeric
	CapacitiveIndex       pgtype.Numeric
	T1Index               pgtype.Numeric
	T2Index               pgtype.Numeric
	T3Index               pgtype.Numeric
	ActiveGenerationIndex pgtype.Numeric
	ReadingCount          int64
}

type ConsumptionYearly struct {
	AnalyzerID            uuid.UUID
	Bucket                pgtype.Timestamptz
	ActiveImportStart     pgtype.Numeric
	ActiveImportEnd       pgtype.Numeric
	ActiveConsumption     pgtype.Numeric
	InductiveConsumption  pgtype.Numeric
	CapacitiveConsumption pgtype.Numeric
	T1Consumption         pgtype.Numeric
	T2Consumption         pgtype.Numeric
	T3Consumption         pgtype.Numeric
	ActiveGeneration      pgtype.Numeric
	InductiveGeneration   pgtype.Numeric
	CapacitiveGeneration  pgtype.Numeric
	T1Generation          pgtype.Numeric
	T2Generation          pgtype.Numeric
	T3Generation          pgtype.Numeric
	MaxDemandKw           pgtype.Numeric
	ActiveIndex           pgtype.Numeric
	InductiveIndex        pgtype.Numeric
	CapacitiveIndex       pgtype.Numeric
	T1Index               pgtype.Numeric
	T2Index               pgtype.Numeric
	T3Index               pgtype.Numeric
	ActiveGenerationIndex pgtype.Numeric
	ReadingCount          int64
}

type EmissionFactor struct {
	ID            uuid.UUID
	CompanyID     *uuid.UUID
	Key           string
	Label         string
	MainCategory  string
	SubCategories []string
	CategoryPath  []string
	BaseFactor    pgtype.Numeric
	BaseUnit      string
	FuelType      *string
	VehicleType   *string
	Scope         NullCarbonScope
	IsoCategory   *string
	Status        *string
	Source        *string
	SourceYear    *int16
	SourceUrl     *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type EmissionFactorConversion struct {
	FactorID   uuid.UUID
	Unit       string
	Multiplier pgtype.Numeric
	Label      string
}

type Forecast struct {
	AnalyzerID   uuid.UUID
	Ts           pgtype.Timestamptz
	GeneratedAt  pgtype.Timestamptz
	HorizonHours int32
	Median       pgtype.Numeric
	P10          pgtype.Numeric
	P90          pgtype.Numeric
	ModelID      string
	ModelVersion *string
}

type ForecastGap struct {
	ID           uuid.UUID
	AnalyzerID   uuid.UUID
	GeneratedAt  pgtype.Timestamptz
	GapStart     pgtype.Timestamptz
	GapEnd       pgtype.Timestamptz
	MissingHours int32
}

type GenerationAnchor struct {
	AnalyzerID   uuid.UUID
	AnchorTs     pgtype.Timestamptz
	ActiveExport pgtype.Numeric
	Source       string
	UpdatedAt    pgtype.Timestamptz
}

type IcmalImport struct {
	ID         uuid.UUID
	CompanyID  uuid.UUID
	UploadedBy *uuid.UUID
	FileName   string
	RowCount   int32
	Status     string
	Result     []byte
	CreatedAt  pgtype.Timestamptz
}

type IcmalRow struct {
	ID                 uuid.UUID
	ImportID           uuid.UUID
	BuildingID         *uuid.UUID
	Period             string
	EtsoCode           *string
	TotalKwh           pgtype.Numeric
	T0Kwh              pgtype.Numeric
	T1Kwh              pgtype.Numeric
	T2Kwh              pgtype.Numeric
	T3Kwh              pgtype.Numeric
	EnergyCharge       pgtype.Numeric
	DistributionCharge pgtype.Numeric
	ReactiveCharge     pgtype.Numeric
	PowerCharge        pgtype.Numeric
	OveruseCharge      pgtype.Numeric
	InductiveKvarh     pgtype.Numeric
	CapacitiveKvarh    pgtype.Numeric
	DemandKw           pgtype.Numeric
	VatBase            pgtype.Numeric
	Vat                pgtype.Numeric
	Btv                pgtype.Numeric
	EnergyFund         pgtype.Numeric
	Trt                pgtype.Numeric
	PriceDifference    pgtype.Numeric
	CorrectionAmount   pgtype.Numeric
	IsCancelled        bool
	Term               *string
	VoltageLevel       *string
	IsMultiTime        *bool
	Raw                []byte
}

type IngestionCursor struct {
	AnalyzerID          uuid.UUID
	Kind                ReadingKind
	LastTs              pgtype.Timestamptz
	LastSuccessAt       pgtype.Timestamptz
	LastError           *string
	LastErrorAt         pgtype.Timestamptz
	ConsecutiveFailures int32
}

type IntegrationCredential struct {
	ID             uuid.UUID
	CompanyID      uuid.UUID
	DefinitionID   uuid.UUID
	Username       *string
	SecretEnc      []byte
	ExtraEnc       []byte
	Settings       []byte
	Pm5340Url      *string
	IsolarRegion   *string
	TokenExpiresAt pgtype.Timestamptz
	LastVerifiedAt pgtype.Timestamptz
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type IntegrationDefinition struct {
	ID        uuid.UUID
	Provider  IntegrationProvider
	Subtype   string
	Endpoints []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Iso50001ClauseDate struct {
	ProjectID uuid.UUID
	ClauseID  string
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

type Iso50001Note struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	ClauseID  string
	Title     *string
	Body      string
	CreatedBy *uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Iso50001Project struct {
	ID         uuid.UUID
	CompanyID  uuid.UUID
	BuildingID uuid.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type IsolarForwardedAlarm struct {
	PlantID  uuid.UUID
	AlarmRef string
	SentAt   pgtype.Timestamptz
}

type JobRun struct {
	ID         uuid.UUID
	CompanyID  *uuid.UUID
	JobType    string
	Scope      []byte
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	Status     string
	Processed  int32
	Skipped    int32
	Failed     int32
	Error      *string
	Detail     []byte
	TaskID     *string
}

type LegacyBill struct {
	ID                     uuid.UUID
	CompanyID              uuid.UUID
	BuildingID             uuid.UUID
	AnalyzerID             *uuid.UUID
	Scope                  string
	Period                 string
	StartDate              pgtype.Date
	EndDate                pgtype.Date
	TotalActiveKwh         pgtype.Numeric
	T1Kwh                  pgtype.Numeric
	T2Kwh                  pgtype.Numeric
	T3Kwh                  pgtype.Numeric
	InductiveKvarh         pgtype.Numeric
	CapacitiveKvarh        pgtype.Numeric
	EnergyCost             pgtype.Numeric
	DistributionCost       pgtype.Numeric
	CapacityCost           pgtype.Numeric
	PowerCost              pgtype.Numeric
	GreenEnergyCost        pgtype.Numeric
	ReactivePenalty        pgtype.Numeric
	ReactivePenaltyApplied *bool
	VatCost                pgtype.Numeric
	OtherTaxesCost         pgtype.Numeric
	TotalCost              pgtype.Numeric
	PdfPath                *string
	Payload                []byte
}

type LegacyID struct {
	Collection string
	LegacyID   string
	TableName  string
	NewID      uuid.UUID
}

type LegacyReport struct {
	ID         uuid.UUID
	CompanyID  uuid.UUID
	BuildingID *uuid.UUID
	ReportType string
	Period     string
	Payload    []byte
	PdfPath    *string
	ExcelPath  *string
	CreatedAt  pgtype.Timestamptz
}

type MarketPricesHourly struct {
	Ts        pgtype.Timestamptz
	Ptf       pgtype.Numeric
	FetchedAt pgtype.Timestamptz
}

type MeterReading struct {
	AnalyzerID               uuid.UUID
	Ts                       pgtype.Timestamptz
	Kind                     ReadingKind
	ActiveImport             pgtype.Numeric
	ReactiveInductiveImport  pgtype.Numeric
	ReactiveCapacitiveImport pgtype.Numeric
	T1Import                 pgtype.Numeric
	T2Import                 pgtype.Numeric
	T3Import                 pgtype.Numeric
	ActiveExport             pgtype.Numeric
	ReactiveInductiveExport  pgtype.Numeric
	ReactiveCapacitiveExport pgtype.Numeric
	T1Export                 pgtype.Numeric
	T2Export                 pgtype.Numeric
	T3Export                 pgtype.Numeric
	MaxDemandKw              pgtype.Numeric
	MeterSerial              *string
	MultiplierApplied        pgtype.Numeric
	SourceProvider           IntegrationProvider
	IngestedAt               pgtype.Timestamptz
	Raw                      []byte
	IntervalGenerationKwh    pgtype.Numeric
}

type NationalTariffSchedule struct {
	ID                uuid.UUID
	EffectiveFrom     pgtype.Date
	UserGroup         DistributionUserGroup
	VoltageLevel      VoltageLevel
	Term              TariffTerm
	EnergyPrice       pgtype.Numeric
	T1Price           pgtype.Numeric
	T2Price           pgtype.Numeric
	T3Price           pgtype.Numeric
	DistributionPrice pgtype.Numeric
	PowerPrice        pgtype.Numeric
	OverusePrice      pgtype.Numeric
	DailyThresholdKwh pgtype.Numeric
	VatRate           pgtype.Numeric
	Source            *string
	CreatedAt         pgtype.Timestamptz
}

type OperationalMessage struct {
	ID          int64
	CompanyID   *uuid.UUID
	Kind        string
	Category    string
	Status      string
	Message     string
	Detail      *string
	RelatedType *string
	RelatedID   *uuid.UUID
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type PlantFault struct {
	PlantID     uuid.UUID
	Ref         string
	Code        string
	Name        string
	Level       *int32
	Type        *int32
	DeviceName  *string
	OccurredAt  pgtype.Timestamptz
	ClosedAt    pgtype.Timestamptz
	FirstSeenAt pgtype.Timestamptz
}

type PlantProduction struct {
	PlantID       uuid.UUID
	Ts            pgtype.Timestamptz
	DeviceID      uuid.UUID
	ProductionKwh pgtype.Numeric
	ActivePowerKw pgtype.Numeric
	EfficiencyPct pgtype.Numeric
	IrradianceWm2 pgtype.Numeric
	ModuleTempC   pgtype.Numeric
	AmbientTempC  pgtype.Numeric
	Source        string
}

type PlantProductionDaily struct {
	PlantID          uuid.UUID
	Bucket           pgtype.Timestamptz
	ProductionKwh    pgtype.Numeric
	MaxActivePowerKw pgtype.Numeric
}

type PlantProductionMonthly struct {
	PlantID          uuid.UUID
	Bucket           pgtype.Timestamptz
	ProductionKwh    pgtype.Numeric
	MaxActivePowerKw pgtype.Numeric
}

type PlantProductionTotal struct {
	PlantID       uuid.UUID
	Ts            pgtype.Timestamptz
	ProductionKwh pgtype.Numeric
	ActivePowerKw pgtype.Numeric
	Basis         string
	UpdatedAt     pgtype.Timestamptz
}

type PowerPlant struct {
	ID                  uuid.UUID
	CompanyID           uuid.UUID
	Name                string
	InstallationNumber  *string
	PlantKind           string
	PvBrandModel        *string
	PanelPowerW         pgtype.Numeric
	PanelEfficiencyPct  pgtype.Numeric
	PanelCount          *int32
	StringCount         *int32
	Orientation         NullPanelOrientation
	TiltAngleDeg        pgtype.Numeric
	TotalCapacityKw     pgtype.Numeric
	YearlyTargetKwh     pgtype.Numeric
	InstallationDate    pgtype.Date
	Address             *string
	Latitude            pgtype.Numeric
	Longitude           pgtype.Numeric
	IsolarPsID          *string
	IsolarPsKey         *string
	IsolarPsName        *string
	IsolarInstalledKw   pgtype.Numeric
	IsolarLinkedAt      pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	IsolarCredentialID  *uuid.UUID
	NettingAnalyzerID   *uuid.UUID
	IsolarLastSyncAt    pgtype.Timestamptz
	IsolarLastSyncError *string
}

type PowerPlantAlarmRecipient struct {
	PlantID uuid.UUID
	Email   string
}

type PowerPlantDevice struct {
	ID             uuid.UUID
	PlantID        uuid.UUID
	DeviceSn       string
	DeviceName     *string
	DeviceType     *int32
	DeviceTypeName *string
	ProviderKey    *string
	Brand          *string
	Model          *string
	RatedPowerKw   pgtype.Numeric
	Status         *string
	EfficiencyPct  pgtype.Numeric
	LastSeenAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	SnapshotAt     pgtype.Timestamptz
	FaultStatus    *int32
	ActivePowerKw  pgtype.Numeric
	YieldTodayKwh  pgtype.Numeric
	YieldMonthKwh  pgtype.Numeric
	YieldYearKwh   pgtype.Numeric
	YieldTotalKwh  pgtype.Numeric
}

type PowerPlantMonthlyTarget struct {
	PlantID   uuid.UUID
	Month     int16
	TargetKwh pgtype.Numeric
}

type ProviderHourlyValue struct {
	AnalyzerID        uuid.UUID
	Ts                pgtype.Timestamptz
	ActiveConsumption pgtype.Numeric
	ActiveGeneration  pgtype.Numeric
	SourceProvider    IntegrationProvider
	IngestedAt        pgtype.Timestamptz
}

type Report struct {
	ID             uuid.UUID
	CompanyID      uuid.UUID
	BuildingID     uuid.UUID
	Type           ReportType
	Period         string
	PlantSelection PlantSelection
	Payload        []byte
	PdfPath        *string
	ExcelPath      *string
	EmailSubject   *string
	EmailBody      *string
	Status         ReportStatus
	ErrorMessage   *string
	ProcessedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Session struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	RefreshTokenHash  string
	DeviceFingerprint *string
	UserAgent         *string
	Ip                *netip.Addr
	ExpiresAt         pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	Client            string
	Remember          bool
	LastUsedAt        pgtype.Timestamptz
	RevokedReason     *string
	RotatedFrom       *uuid.UUID
}

type SmtpSetting struct {
	CompanyID   uuid.UUID
	Host        string
	Port        int32
	Secure      bool
	Username    string
	PasswordEnc []byte
	FromAddress string
	UpdatedAt   pgtype.Timestamptz
}

type SolarTariff struct {
	ID            uuid.UUID
	CompanyID     uuid.UUID
	PlantID       uuid.UUID
	EffectiveFrom pgtype.Date
	FeedInTariff  pgtype.Numeric
	PurchasePrice pgtype.Numeric
	Currency      CurrencyCode
	Notes         *string
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type StoredFile struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	OwnerType    string
	OwnerID      *uuid.UUID
	ClauseID     *string
	OriginalName string
	StoredPath   string
	ContentType  string
	SizeBytes    int64
	Checksum     string
	UploadedBy   *uuid.UUID
	CreatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type Tariff struct {
	ID                          uuid.UUID
	CompanyID                   uuid.UUID
	BuildingID                  *uuid.UUID
	Name                        *string
	EffectiveFrom               pgtype.Date
	Currency                    CurrencyCode
	EnergyType                  EnergyType
	VoltageLevel                VoltageLevel
	UserGroup                   DistributionUserGroup
	PriceType                   PriceType
	Term                        TariffTerm
	SupplyCompany               SupplyCompany
	SingleTimePrice             pgtype.Numeric
	T1Price                     pgtype.Numeric
	T2Price                     pgtype.Numeric
	T3Price                     pgtype.Numeric
	OverusePrice                pgtype.Numeric
	OveruseThresholdKwhPerDay   pgtype.Numeric
	DistributionCost            pgtype.Numeric
	ReactivePowerPrice          pgtype.Numeric
	GreenEnergyPrice            pgtype.Numeric
	GreenEnergyDistributionCost pgtype.Numeric
	ContractedPowerKw           pgtype.Numeric
	PowerUnitPrice              pgtype.Numeric
	GenerationUsage             GenerationUsage
	GenerationPricePerKwh       pgtype.Numeric
	VatRate                     pgtype.Numeric
	UsePtfYekdem                bool
	KbkEnergy                   pgtype.Numeric
	KbkT1                       pgtype.Numeric
	KbkT2                       pgtype.Numeric
	KbkT3                       pgtype.Numeric
	KbkPowerPrice               pgtype.Numeric
	KbkOverusePrice             pgtype.Numeric
	KbkReactivePower            pgtype.Numeric
	KbkDistributionCostTlPerKwh pgtype.Numeric
	UseManualYekdem             bool
	CreatedBy                   *uuid.UUID
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	DeletedAt                   pgtype.Timestamptz
	PowerPriceSource            PriceSource
	ReactivePriceSource         PriceSource
	DistributionPriceSource     PriceSource
}

type TariffBulkAssignment struct {
	ID            uuid.UUID
	CompanyID     uuid.UUID
	TemplateID    *uuid.UUID
	TariffName    *string
	EffectiveFrom pgtype.Date
	BuildingIds   []uuid.UUID
	CreatedBy     *uuid.UUID
	CreatedAt     pgtype.Timestamptz
}

type TariffExtraCharge struct {
	ID        uuid.UUID
	TariffID  uuid.UUID
	Name      string
	Basis     ExtraChargeBasis
	Amount    pgtype.Numeric
	SortOrder int16
}

type TariffManualYekdem struct {
	TariffID uuid.UUID
	Year     int16
	Month    int16
	Value    pgtype.Numeric
}

type TariffTax struct {
	ID        uuid.UUID
	TariffID  uuid.UUID
	Name      string
	Rate      pgtype.Numeric
	SortOrder int16
}

type TariffTemplate struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	Name        string
	Description *string
	IsDefault   bool
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID                uuid.UUID
	CompanyID         uuid.UUID
	Name              string
	Email             string
	Phone             *string
	PasswordHash      string
	PasswordChangedAt pgtype.Timestamptz
	Role              UserRole
	IsActive          bool
	LastLoginAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	UiPreferences     *string
	Locale            string
}

type UserPasswordHistory struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type YekdemMonthly struct {
	Year      int16
	Month     int16
	Value     pgtype.Numeric
	FetchedAt pgtype.Timestamptz
}
