// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_resets.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const passwordResetCreate = `-- name: PasswordResetCreate :one
insert into password_reset_tokens (id, user_id, token_hash, expires_at, created_at)
select $1, $2, $3, $4, coalesce($5::timestamptz, now())
where exists (
    select 1 from users
    where id = $2 and company_id = $6 and deleted_at is null
)
returning id, user_id, token_hash, expires_at, used_at, created_at
`

type PasswordResetCreateParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	At        pgtype.Timestamptz
	CompanyID uuid.UUID
}

func (q *Queries) PasswordResetCreate(ctx context.Context, arg PasswordResetCreateParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, passwordResetCreate,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.At,
		arg.CompanyID,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const passwordResetInvalidateUnused = `-- name: PasswordResetInvalidateUnused :exec

update password_reset_tokens
set used_at = $1
where password_reset_tokens.user_id = $2
  and password_reset_tokens.used_at is null
  and password_reset_tokens.user_id in (select users.id from users where users.company_id = $3 and users.deleted_at is null)
`

type PasswordResetInvalidateUnusedParams struct {
	At        pgtype.Timestamptz
	UserID    uuid.UUID
	CompanyID uuid.UUID
}

// PasswordResetRepository queries. password_reset_tokens has no company_id —
// every query joins through users.
func (q *Queries) PasswordResetInvalidateUnused(ctx context.Context, arg PasswordResetInvalidateUnusedParams) error {
	_, err := q.db.Exec(ctx, passwordResetInvalidateUnused, arg.At, arg.UserID, arg.CompanyID)
	return err
}

const passwordResetMarkUsed = `-- name: PasswordResetMarkUsed :execrows
update password_reset_tokens
set used_at = $1
where password_reset_tokens.id = $2
  and password_reset_tokens.used_at is null
  and password_reset_tokens.user_id in (select users.id from users where users.company_id = $3 and users.deleted_at is null)
`

type PasswordResetMarkUsedParams struct {
	At        pgtype.Timestamptz
	ID        uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) PasswordResetMarkUsed(ctx context.Context, arg PasswordResetMarkUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, passwordResetMarkUsed, arg.At, arg.ID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const passwordResetVisible = `-- name: PasswordResetVisible :one
select exists(
    select 1 from password_reset_tokens p join users u on u.id = p.user_id
    where p.id = $1 and u.company_id = $2 and u.deleted_at is null
)
`

type PasswordResetVisibleParams struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) PasswordResetVisible(ctx context.Context, arg PasswordResetVisibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, passwordResetVisible, arg.ID, arg.CompanyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
