// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prices.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const priceHourlyRange = `-- name: PriceHourlyRange :many

select ts, ptf, fetched_at from market_prices_hourly
where ts >= $1::timestamptz
  and ts < $2::timestamptz
order by ts
`

type PriceHourlyRangeParams struct {
	FromTs pgtype.Timestamptz
	ToTs   pgtype.Timestamptz
}

// PriceRepository's queries, over the two PLATFORM-WIDE tables
// market_prices_hourly and yekdem_monthly. Neither carries a company_id, so
// the Scope narrows nothing here; it is still validated by the repository
// before either query runs (repository.go's PriceRepository doc).
func (q *Queries) PriceHourlyRange(ctx context.Context, arg PriceHourlyRangeParams) ([]MarketPricesHourly, error) {
	rows, err := q.db.Query(ctx, priceHourlyRange, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketPricesHourly
	for rows.Next() {
		var i MarketPricesHourly
		if err := rows.Scan(&i.Ts, &i.Ptf, &i.FetchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const priceYekdem = `-- name: PriceYekdem :one
select year, month, value, fetched_at from yekdem_monthly
where year = $1 and month = $2
`

type PriceYekdemParams struct {
	Year  int16
	Month int16
}

func (q *Queries) PriceYekdem(ctx context.Context, arg PriceYekdemParams) (YekdemMonthly, error) {
	row := q.db.QueryRow(ctx, priceYekdem, arg.Year, arg.Month)
	var i YekdemMonthly
	err := row.Scan(
		&i.Year,
		&i.Month,
		&i.Value,
		&i.FetchedAt,
	)
	return i, err
}
