// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: production.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const productionLatest = `-- name: ProductionLatest :one
select plant_id, ts, device_id, production_kwh, active_power_kw, efficiency_pct, irradiance_wm2, module_temp_c, ambient_temp_c, source from plant_production
where plant_id = $1
  and ts >= $2::timestamptz
  and ts < $3::timestamptz
order by ts desc
limit 1
`

type ProductionLatestParams struct {
	PlantID uuid.UUID
	FromTs  pgtype.Timestamptz
	ToTs    pgtype.Timestamptz
}

func (q *Queries) ProductionLatest(ctx context.Context, arg ProductionLatestParams) (PlantProduction, error) {
	row := q.db.QueryRow(ctx, productionLatest, arg.PlantID, arg.FromTs, arg.ToTs)
	var i PlantProduction
	err := row.Scan(
		&i.PlantID,
		&i.Ts,
		&i.DeviceID,
		&i.ProductionKwh,
		&i.ActivePowerKw,
		&i.EfficiencyPct,
		&i.IrradianceWm2,
		&i.ModuleTempC,
		&i.AmbientTempC,
		&i.Source,
	)
	return i, err
}

const productionPlantVisible = `-- name: ProductionPlantVisible :one
select exists (
    select 1 from power_plants
    where id = $1 and company_id = $2 and deleted_at is null
)
`

type ProductionPlantVisibleParams struct {
	PlantID   uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) ProductionPlantVisible(ctx context.Context, arg ProductionPlantVisibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, productionPlantVisible, arg.PlantID, arg.CompanyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const productionRange = `-- name: ProductionRange :many
select plant_id, ts, device_id, production_kwh, active_power_kw, efficiency_pct, irradiance_wm2, module_temp_c, ambient_temp_c, source from plant_production
where plant_id = $1
  and ts >= $2::timestamptz
  and ts < $3::timestamptz
order by ts
`

type ProductionRangeParams struct {
	PlantID uuid.UUID
	FromTs  pgtype.Timestamptz
	ToTs    pgtype.Timestamptz
}

func (q *Queries) ProductionRange(ctx context.Context, arg ProductionRangeParams) ([]PlantProduction, error) {
	rows, err := q.db.Query(ctx, productionRange, arg.PlantID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlantProduction
	for rows.Next() {
		var i PlantProduction
		if err := rows.Scan(
			&i.PlantID,
			&i.Ts,
			&i.DeviceID,
			&i.ProductionKwh,
			&i.ActivePowerKw,
			&i.EfficiencyPct,
			&i.IrradianceWm2,
			&i.ModuleTempC,
			&i.AmbientTempC,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productionValidDevicePairCount = `-- name: ProductionValidDevicePairCount :one
select count(*) from (
    select unnest($1::uuid[]) as plant_id,
           unnest($2::uuid[]) as device_id
) pairs
join power_plant_devices d on d.plant_id = pairs.plant_id and d.id = pairs.device_id
`

type ProductionValidDevicePairCountParams struct {
	PlantIds  []uuid.UUID
	DeviceIds []uuid.UUID
}

// Counts how many of the (plant_id, device_id) pairs in the batch are a real
// device of that same plant. BulkInsert compares this against the number of
// DISTINCT pairs in the batch: a mismatch means at least one row's device_id
// does not belong to that row's plant_id.
func (q *Queries) ProductionValidDevicePairCount(ctx context.Context, arg ProductionValidDevicePairCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, productionValidDevicePairCount, arg.PlantIds, arg.DeviceIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const productionVisiblePlantCount = `-- name: ProductionVisiblePlantCount :one

select count(*) from power_plants
where id = any($1::uuid[])
  and company_id = $2
  and deleted_at is null
`

type ProductionVisiblePlantCountParams struct {
	PlantIds  []uuid.UUID
	CompanyID uuid.UUID
}

// ProductionRepository's queries. plant_production has no company_id: every
// method joins through power_plants, which itself has no building_id — a
// Scope narrows a plant to the company and no further (repository.go's
// PlantRepository doc). BulkInsert's COPY-into-staging-then-upsert is plain
// SQL in production.go, for the same reason ReadingRepository.BulkInsert's is
// not here.
func (q *Queries) ProductionVisiblePlantCount(ctx context.Context, arg ProductionVisiblePlantCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, productionVisiblePlantCount, arg.PlantIds, arg.CompanyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
