// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: readings.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const readingAnalyzerVisible = `-- name: ReadingAnalyzerVisible :one
select exists (
    select 1 from analyzers
    where id = $1
      and company_id = $2
      and ($3::boolean or building_id = any($4::uuid[]))
      and deleted_at is null
)
`

type ReadingAnalyzerVisibleParams struct {
	AnalyzerID   uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) ReadingAnalyzerVisible(ctx context.Context, arg ReadingAnalyzerVisibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, readingAnalyzerVisible,
		arg.AnalyzerID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const readingBoundaryAtOrBefore = `-- name: ReadingBoundaryAtOrBefore :one
select analyzer_id, ts, kind, active_import, reactive_inductive_import, reactive_capacitive_import, t1_import, t2_import, t3_import, active_export, reactive_inductive_export, reactive_capacitive_export, t1_export, t2_export, t3_export, max_demand_kw, meter_serial, multiplier_applied, source_provider, ingested_at, raw from meter_readings
where analyzer_id = $1
  and kind = $2::reading_kind
  and ts <= $3::timestamptz
order by ts desc
limit 1
`

type ReadingBoundaryAtOrBeforeParams struct {
	AnalyzerID uuid.UUID
	Kind       ReadingKind
	At         pgtype.Timestamptz
}

// The one hypertable read bounded on one side only, per repository.go's
// BoundaryReadings doc: the last reading at or before `at`, however long ago.
func (q *Queries) ReadingBoundaryAtOrBefore(ctx context.Context, arg ReadingBoundaryAtOrBeforeParams) (MeterReading, error) {
	row := q.db.QueryRow(ctx, readingBoundaryAtOrBefore, arg.AnalyzerID, arg.Kind, arg.At)
	var i MeterReading
	err := row.Scan(
		&i.AnalyzerID,
		&i.Ts,
		&i.Kind,
		&i.ActiveImport,
		&i.ReactiveInductiveImport,
		&i.ReactiveCapacitiveImport,
		&i.T1Import,
		&i.T2Import,
		&i.T3Import,
		&i.ActiveExport,
		&i.ReactiveInductiveExport,
		&i.ReactiveCapacitiveExport,
		&i.T1Export,
		&i.T2Export,
		&i.T3Export,
		&i.MaxDemandKw,
		&i.MeterSerial,
		&i.MultiplierApplied,
		&i.SourceProvider,
		&i.IngestedAt,
		&i.Raw,
	)
	return i, err
}

const readingLatest = `-- name: ReadingLatest :one
select analyzer_id, ts, kind, active_import, reactive_inductive_import, reactive_capacitive_import, t1_import, t2_import, t3_import, active_export, reactive_inductive_export, reactive_capacitive_export, t1_export, t2_export, t3_export, max_demand_kw, meter_serial, multiplier_applied, source_provider, ingested_at, raw from meter_readings
where analyzer_id = $1
  and kind = $2::reading_kind
  and ts >= $3::timestamptz
  and ts < $4::timestamptz
order by ts desc
limit 1
`

type ReadingLatestParams struct {
	AnalyzerID uuid.UUID
	Kind       ReadingKind
	FromTs     pgtype.Timestamptz
	ToTs       pgtype.Timestamptz
}

func (q *Queries) ReadingLatest(ctx context.Context, arg ReadingLatestParams) (MeterReading, error) {
	row := q.db.QueryRow(ctx, readingLatest,
		arg.AnalyzerID,
		arg.Kind,
		arg.FromTs,
		arg.ToTs,
	)
	var i MeterReading
	err := row.Scan(
		&i.AnalyzerID,
		&i.Ts,
		&i.Kind,
		&i.ActiveImport,
		&i.ReactiveInductiveImport,
		&i.ReactiveCapacitiveImport,
		&i.T1Import,
		&i.T2Import,
		&i.T3Import,
		&i.ActiveExport,
		&i.ReactiveInductiveExport,
		&i.ReactiveCapacitiveExport,
		&i.T1Export,
		&i.T2Export,
		&i.T3Export,
		&i.MaxDemandKw,
		&i.MeterSerial,
		&i.MultiplierApplied,
		&i.SourceProvider,
		&i.IngestedAt,
		&i.Raw,
	)
	return i, err
}

const readingRange = `-- name: ReadingRange :many
select analyzer_id, ts, kind, active_import, reactive_inductive_import, reactive_capacitive_import, t1_import, t2_import, t3_import, active_export, reactive_inductive_export, reactive_capacitive_export, t1_export, t2_export, t3_export, max_demand_kw, meter_serial, multiplier_applied, source_provider, ingested_at, raw from meter_readings
where analyzer_id = $1
  and kind = $2::reading_kind
  and ts >= $3::timestamptz
  and ts < $4::timestamptz
order by ts
`

type ReadingRangeParams struct {
	AnalyzerID uuid.UUID
	Kind       ReadingKind
	FromTs     pgtype.Timestamptz
	ToTs       pgtype.Timestamptz
}

func (q *Queries) ReadingRange(ctx context.Context, arg ReadingRangeParams) ([]MeterReading, error) {
	rows, err := q.db.Query(ctx, readingRange,
		arg.AnalyzerID,
		arg.Kind,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeterReading
	for rows.Next() {
		var i MeterReading
		if err := rows.Scan(
			&i.AnalyzerID,
			&i.Ts,
			&i.Kind,
			&i.ActiveImport,
			&i.ReactiveInductiveImport,
			&i.ReactiveCapacitiveImport,
			&i.T1Import,
			&i.T2Import,
			&i.T3Import,
			&i.ActiveExport,
			&i.ReactiveInductiveExport,
			&i.ReactiveCapacitiveExport,
			&i.T1Export,
			&i.T2Export,
			&i.T3Export,
			&i.MaxDemandKw,
			&i.MeterSerial,
			&i.MultiplierApplied,
			&i.SourceProvider,
			&i.IngestedAt,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readingVisibleAnalyzerCount = `-- name: ReadingVisibleAnalyzerCount :one

select count(*) from analyzers
where id = any($1::uuid[])
  and company_id = $2
  and ($3::boolean or building_id = any($4::uuid[]))
  and deleted_at is null
`

type ReadingVisibleAnalyzerCountParams struct {
	AnalyzerIds  []uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// ReadingRepository's queries. meter_readings has no company_id (see
// repository.go's "ROWS WITHOUT company_id" header): every method joins
// through analyzers, or checks analyzer visibility explicitly before reading
// the hypertable directly, which is why the *_range/*_latest queries below do
// not themselves join anything.
//
// BulkInsert's COPY-into-staging-then-upsert is NOT here: a per-call
// temporary table cannot appear in sqlc's schema catalogue (it does not exist
// until the transaction that creates it), so that statement is built and run
// as plain SQL in readings.go. The queries below back only the pre-write
// visibility check and the three plain reads.
// Counts how many of analyzer_ids are visible to the scope. BulkInsert
// compares this against the number of DISTINCT analyzer ids in the batch: a
// mismatch means at least one row's analyzer is not visible, and the whole
// batch is refused.
func (q *Queries) ReadingVisibleAnalyzerCount(ctx context.Context, arg ReadingVisibleAnalyzerCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, readingVisibleAnalyzerCount,
		arg.AnalyzerIds,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}
