// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const reportGet = `-- name: ReportGet :one

select id, company_id, building_id, type, period, plant_selection, payload, pdf_path, excel_path, email_subject, email_body, status, error_message, processed_at, created_at, updated_at from reports
where reports.id = $1 and reports.company_id = $2
  and ($3::boolean or reports.building_id = any($4::uuid[]))
  and exists (select 1 from buildings b where b.id = reports.building_id and b.deleted_at is null)
`

type ReportGetParams struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

// Generated building reports (migration 00010). Query names are prefixed
// Report…
// Folded minor (fix round 1): a report of a soft-deleted building must not
// stay readable through the report's own row.
func (q *Queries) ReportGet(ctx context.Context, arg ReportGetParams) (Report, error) {
	row := q.db.QueryRow(ctx, reportGet,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.Type,
		&i.Period,
		&i.PlantSelection,
		&i.Payload,
		&i.PdfPath,
		&i.ExcelPath,
		&i.EmailSubject,
		&i.EmailBody,
		&i.Status,
		&i.ErrorMessage,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reportList = `-- name: ReportList :many
select id, company_id, building_id, type, period, plant_selection, payload, pdf_path, excel_path, email_subject, email_body, status, error_message, processed_at, created_at, updated_at from reports
where reports.company_id = $1
  and ($2::boolean or reports.building_id = any($3::uuid[]))
  and ($4::uuid is null or reports.building_id = $4)
  and ($5::report_type is null or reports.type = $5)
  and ($6::text is null or reports.period = $6)
  -- Statuses is compared as text[], not report_status[]: pgx has no codec
  -- for an array of this custom enum, and fails even on an empty slice.
  and (cardinality($7::text[]) = 0 or reports.status::text = any($7::text[]))
  and exists (select 1 from buildings b where b.id = reports.building_id and b.deleted_at is null)
order by reports.created_at desc, reports.id
limit $9 offset $8
`

type ReportListParams struct {
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
	BuildingID   *uuid.UUID
	ReportType   NullReportType
	Period       *string
	Statuses     []string
	OffsetVal    int32
	LimitVal     int32
}

func (q *Queries) ReportList(ctx context.Context, arg ReportListParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, reportList,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
		arg.BuildingID,
		arg.ReportType,
		arg.Period,
		arg.Statuses,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BuildingID,
			&i.Type,
			&i.Period,
			&i.PlantSelection,
			&i.Payload,
			&i.PdfPath,
			&i.ExcelPath,
			&i.EmailSubject,
			&i.EmailBody,
			&i.Status,
			&i.ErrorMessage,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportUpdateStatus = `-- name: ReportUpdateStatus :one
update reports set status = $1, error_message = $2,
  processed_at = $3, updated_at = $3
where id = $4 and company_id = $5
  and ($6::boolean or building_id = any($7::uuid[]))
returning id, company_id, building_id, type, period, plant_selection, payload, pdf_path, excel_path, email_subject, email_body, status, error_message, processed_at, created_at, updated_at
`

type ReportUpdateStatusParams struct {
	Status       ReportStatus
	ErrorMessage *string
	ProcessedAt  pgtype.Timestamptz
	ID           uuid.UUID
	CompanyID    uuid.UUID
	AllBuildings bool
	BuildingIds  []uuid.UUID
}

func (q *Queries) ReportUpdateStatus(ctx context.Context, arg ReportUpdateStatusParams) (Report, error) {
	row := q.db.QueryRow(ctx, reportUpdateStatus,
		arg.Status,
		arg.ErrorMessage,
		arg.ProcessedAt,
		arg.ID,
		arg.CompanyID,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.Type,
		&i.Period,
		&i.PlantSelection,
		&i.Payload,
		&i.PdfPath,
		&i.ExcelPath,
		&i.EmailSubject,
		&i.EmailBody,
		&i.Status,
		&i.ErrorMessage,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reportUpsert = `-- name: ReportUpsert :one
insert into reports (
  id, company_id, building_id, type, period, plant_selection, payload, pdf_path, excel_path,
  email_subject, email_body, status, error_message, processed_at, created_at, updated_at
)
select
  gen_random_uuid(), $1, $2, $3,
  $4, $5, $6, $7,
  $8, $9, $10, $11,
  $12, $13, $14, $14
where exists (
  select 1 from buildings b
  where b.id = $2 and b.company_id = $1 and b.deleted_at is null
    and ($15::boolean or b.id = any($16::uuid[]))
)
on conflict (building_id, type, period) do update set
  plant_selection = excluded.plant_selection,
  payload = excluded.payload,
  pdf_path = excluded.pdf_path,
  excel_path = excluded.excel_path,
  email_subject = excluded.email_subject,
  email_body = excluded.email_body,
  status = excluded.status,
  error_message = excluded.error_message,
  processed_at = excluded.processed_at,
  updated_at = excluded.updated_at
where reports.company_id = $1
returning id, company_id, building_id, type, period, plant_selection, payload, pdf_path, excel_path, email_subject, email_body, status, error_message, processed_at, created_at, updated_at
`

type ReportUpsertParams struct {
	CompanyID      uuid.UUID
	BuildingID     uuid.UUID
	ReportType     ReportType
	Period         string
	PlantSelection PlantSelection
	Payload        []byte
	PdfPath        *string
	ExcelPath      *string
	EmailSubject   *string
	EmailBody      *string
	Status         ReportStatus
	ErrorMessage   *string
	ProcessedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	AllBuildings   bool
	BuildingIds    []uuid.UUID
}

// Critical Finding 1 (task-11a fix round 1): building_id is NOT NULL on
// reports, and is a stored foreign key — Scope.AllowsBuilding is an
// in-memory grant check that cannot know which company owns a building, so
// an AllBuildings Scope's Go-side pre-check alone could store ANOTHER
// TENANT's building id here. Validated in SQL instead, exactly as
// TariffCreate/BillCreate validate theirs.
func (q *Queries) ReportUpsert(ctx context.Context, arg ReportUpsertParams) (Report, error) {
	row := q.db.QueryRow(ctx, reportUpsert,
		arg.CompanyID,
		arg.BuildingID,
		arg.ReportType,
		arg.Period,
		arg.PlantSelection,
		arg.Payload,
		arg.PdfPath,
		arg.ExcelPath,
		arg.EmailSubject,
		arg.EmailBody,
		arg.Status,
		arg.ErrorMessage,
		arg.ProcessedAt,
		arg.CreatedAt,
		arg.AllBuildings,
		arg.BuildingIds,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BuildingID,
		&i.Type,
		&i.Period,
		&i.PlantSelection,
		&i.Payload,
		&i.PdfPath,
		&i.ExcelPath,
		&i.EmailSubject,
		&i.EmailBody,
		&i.Status,
		&i.ErrorMessage,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
