// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const sessionCreate = `-- name: SessionCreate :one
insert into sessions (id, user_id, refresh_token_hash, device_fingerprint, user_agent, ip, expires_at, revoked_at, created_at)
select $1, $2, $3, $4,
       $5, $6, $7, $8,
       coalesce($9::timestamptz, now()) as created_at
where exists (
    select 1 from users
    where id = $2 and company_id = $10 and deleted_at is null
)
returning id, user_id, refresh_token_hash, device_fingerprint, user_agent, ip, expires_at, revoked_at, created_at
`

type SessionCreateParams struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	RefreshTokenHash  string
	DeviceFingerprint *string
	UserAgent         *string
	Ip                *netip.Addr
	ExpiresAt         pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	At                pgtype.Timestamptz
	CompanyID         uuid.UUID
}

// Isolation: sess.UserID must be a user of company_id, checked by inserting
// only when that user is visible; if not, zero rows are inserted and the
// :one scan reports ErrNoRows, translated to ErrNotFound.
//
// coalesce(sqlc.narg(at)::timestamptz, now()): a caller that leaves CreatedAt at its zero
// value gets the database's own now() rather than writing 0001-01-01.
func (q *Queries) SessionCreate(ctx context.Context, arg SessionCreateParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionCreate,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.DeviceFingerprint,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.At,
		arg.CompanyID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceFingerprint,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const sessionDeleteExpired = `-- name: SessionDeleteExpired :execrows
delete from sessions
where sessions.expires_at < $1
  and sessions.user_id in (select users.id from users where users.company_id = $2 and users.deleted_at is null)
`

type SessionDeleteExpiredParams struct {
	Before    pgtype.Timestamptz
	CompanyID uuid.UUID
}

func (q *Queries) SessionDeleteExpired(ctx context.Context, arg SessionDeleteExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, sessionDeleteExpired, arg.Before, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sessionGet = `-- name: SessionGet :one

select s.id, s.user_id, s.refresh_token_hash, s.device_fingerprint, s.user_agent, s.ip, s.expires_at, s.revoked_at, s.created_at from sessions s
join users u on u.id = s.user_id
where s.id = $1 and u.company_id = $2 and u.deleted_at is null
`

type SessionGetParams struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
}

// SessionRepository queries. sessions has no company_id — every query joins
// through users, applying company_id = the Scope's own.
func (q *Queries) SessionGet(ctx context.Context, arg SessionGetParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionGet, arg.ID, arg.CompanyID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.DeviceFingerprint,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const sessionList = `-- name: SessionList :many
select s.id, s.user_id, s.refresh_token_hash, s.device_fingerprint, s.user_agent, s.ip, s.expires_at, s.revoked_at, s.created_at from sessions s
join users u on u.id = s.user_id
where u.company_id = $1 and u.deleted_at is null
  and ($2::uuid is null or s.user_id = $2)
  and ($3::timestamptz is null
       or (s.revoked_at is null and s.expires_at > $3))
order by s.created_at desc
limit $5 offset $4
`

type SessionListParams struct {
	CompanyID  uuid.UUID
	UserID     *uuid.UUID
	ActiveAt   pgtype.Timestamptz
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) SessionList(ctx context.Context, arg SessionListParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, sessionList,
		arg.CompanyID,
		arg.UserID,
		arg.ActiveAt,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.DeviceFingerprint,
			&i.UserAgent,
			&i.Ip,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionRevoke = `-- name: SessionRevoke :execrows
update sessions
set revoked_at = coalesce(sessions.revoked_at, $1)
where sessions.id = $2
  and sessions.user_id in (select users.id from users where users.company_id = $3 and users.deleted_at is null)
`

type SessionRevokeParams struct {
	At        pgtype.Timestamptz
	ID        uuid.UUID
	CompanyID uuid.UUID
}

// revoked_at = coalesce(revoked_at, $at): re-revoking an already-revoked
// session must keep the ORIGINAL instant, because replay detection compares
// against it — overwriting it with a later "re-revoke" time would make a
// genuine replay look like it happened before the session was revoked.
func (q *Queries) SessionRevoke(ctx context.Context, arg SessionRevokeParams) (int64, error) {
	result, err := q.db.Exec(ctx, sessionRevoke, arg.At, arg.ID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sessionRevokeAllForUser = `-- name: SessionRevokeAllForUser :execrows
update sessions
set revoked_at = $1
where sessions.user_id = $2
  and sessions.revoked_at is null
  and sessions.user_id in (select users.id from users where users.company_id = $3 and users.deleted_at is null)
`

type SessionRevokeAllForUserParams struct {
	At        pgtype.Timestamptz
	UserID    uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) SessionRevokeAllForUser(ctx context.Context, arg SessionRevokeAllForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, sessionRevokeAllForUser, arg.At, arg.UserID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sessionUserVisible = `-- name: SessionUserVisible :one
select exists(
    select 1 from users
    where id = $1 and company_id = $2 and deleted_at is null
)
`

type SessionUserVisibleParams struct {
	UserID    uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) SessionUserVisible(ctx context.Context, arg SessionUserVisibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, sessionUserVisible, arg.UserID, arg.CompanyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
