// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: smtp.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const sMTPDelete = `-- name: SMTPDelete :execrows
delete from smtp_settings where company_id = $1
`

func (q *Queries) SMTPDelete(ctx context.Context, companyID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, sMTPDelete, companyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sMTPGet = `-- name: SMTPGet :one

select company_id, host, port, secure, username, password_enc, from_address, updated_at from smtp_settings where company_id = $1
`

// SMTP settings repository queries (migration 00008). Owned by Task 11c.
//
// smtp_settings' primary key IS company_id -- one row per company, no id
// column at all, and company_id is NOT NULL (`primary key references
// companies(id)`), so unlike integration_credentials there is no
// platform-wide (company_id NULL) row here to worry about. password_enc is
// AES-256-GCM ciphertext; every query here reads/writes it as opaque bytes.
// SMTPRepository.OpenPassword is the one place in Go that decrypts it, never
// a query.
func (q *Queries) SMTPGet(ctx context.Context, companyID uuid.UUID) (SmtpSetting, error) {
	row := q.db.QueryRow(ctx, sMTPGet, companyID)
	var i SmtpSetting
	err := row.Scan(
		&i.CompanyID,
		&i.Host,
		&i.Port,
		&i.Secure,
		&i.Username,
		&i.PasswordEnc,
		&i.FromAddress,
		&i.UpdatedAt,
	)
	return i, err
}

const sMTPUpsert = `-- name: SMTPUpsert :one
insert into smtp_settings (company_id, host, port, secure, username, password_enc, from_address)
values (
    $1::uuid, $2, $3::int, $4::boolean,
    $5, $6::bytea, $7::citext
)
on conflict (company_id) do update set
    host = excluded.host,
    port = excluded.port,
    secure = excluded.secure,
    username = excluded.username,
    password_enc = excluded.password_enc,
    from_address = excluded.from_address,
    updated_at = now()
returning company_id, host, port, secure, username, password_enc, from_address, updated_at
`

type SMTPUpsertParams struct {
	CompanyID   uuid.UUID
	Host        string
	Port        int32
	Secure      bool
	Username    string
	PasswordEnc []byte
	FromAddress string
}

func (q *Queries) SMTPUpsert(ctx context.Context, arg SMTPUpsertParams) (SmtpSetting, error) {
	row := q.db.QueryRow(ctx, sMTPUpsert,
		arg.CompanyID,
		arg.Host,
		arg.Port,
		arg.Secure,
		arg.Username,
		arg.PasswordEnc,
		arg.FromAddress,
	)
	var i SmtpSetting
	err := row.Scan(
		&i.CompanyID,
		&i.Host,
		&i.Port,
		&i.Secure,
		&i.Username,
		&i.PasswordEnc,
		&i.FromAddress,
		&i.UpdatedAt,
	)
	return i, err
}
