// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: solar.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deviceProductionDeleteRange = `-- name: DeviceProductionDeleteRange :execrows
delete from plant_production pp
using power_plants p
where pp.plant_id = p.id and pp.plant_id = $1
  and p.company_id = $2 and p.deleted_at is null
  and pp.ts >= $3::timestamptz and pp.ts < $4::timestamptz
`

type DeviceProductionDeleteRangeParams struct {
	PlantID   uuid.UUID
	CompanyID uuid.UUID
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
}

func (q *Queries) DeviceProductionDeleteRange(ctx context.Context, arg DeviceProductionDeleteRangeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deviceProductionDeleteRange,
		arg.PlantID,
		arg.CompanyID,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const faultClaim = `-- name: FaultClaim :many
insert into isolar_forwarded_alarms (plant_id, alarm_ref)
select $1, unnest($2::text[])
where exists (select 1 from power_plants p
              where p.id = $1 and p.company_id = $3 and p.deleted_at is null)
on conflict do nothing
returning alarm_ref
`

type FaultClaimParams struct {
	PlantID   uuid.UUID
	Refs      []string
	CompanyID uuid.UUID
}

// R287: the insert that wins is the only sender.
func (q *Queries) FaultClaim(ctx context.Context, arg FaultClaimParams) ([]string, error) {
	rows, err := q.db.Query(ctx, faultClaim, arg.PlantID, arg.Refs, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var alarm_ref string
		if err := rows.Scan(&alarm_ref); err != nil {
			return nil, err
		}
		items = append(items, alarm_ref)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const faultCount = `-- name: FaultCount :one
select count(*) from plant_faults f
join power_plants p on p.id = f.plant_id
where f.plant_id = $1 and p.company_id = $2 and p.deleted_at is null
`

type FaultCountParams struct {
	PlantID   uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) FaultCount(ctx context.Context, arg FaultCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, faultCount, arg.PlantID, arg.CompanyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const faultForwardedPrune = `-- name: FaultForwardedPrune :execrows
delete from isolar_forwarded_alarms a
using power_plants p
where a.plant_id = p.id and p.company_id = $1 and a.sent_at < $2
`

type FaultForwardedPruneParams struct {
	CompanyID uuid.UUID
	Before    pgtype.Timestamptz
}

func (q *Queries) FaultForwardedPrune(ctx context.Context, arg FaultForwardedPruneParams) (int64, error) {
	result, err := q.db.Exec(ctx, faultForwardedPrune, arg.CompanyID, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const faultList = `-- name: FaultList :many
select f.plant_id, f.ref, f.code, f.name, f.level, f.type, f.device_name, f.occurred_at, f.closed_at, f.first_seen_at from plant_faults f
join power_plants p on p.id = f.plant_id
where f.plant_id = $1 and p.company_id = $2 and p.deleted_at is null
order by f.occurred_at desc, f.ref
limit $4 offset $3
`

type FaultListParams struct {
	PlantID    uuid.UUID
	CompanyID  uuid.UUID
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) FaultList(ctx context.Context, arg FaultListParams) ([]PlantFault, error) {
	rows, err := q.db.Query(ctx, faultList,
		arg.PlantID,
		arg.CompanyID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlantFault
	for rows.Next() {
		var i PlantFault
		if err := rows.Scan(
			&i.PlantID,
			&i.Ref,
			&i.Code,
			&i.Name,
			&i.Level,
			&i.Type,
			&i.DeviceName,
			&i.OccurredAt,
			&i.ClosedAt,
			&i.FirstSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const faultPrune = `-- name: FaultPrune :execrows
delete from plant_faults f
using power_plants p
where f.plant_id = p.id and p.company_id = $1 and f.occurred_at < $2
`

type FaultPruneParams struct {
	CompanyID uuid.UUID
	Before    pgtype.Timestamptz
}

func (q *Queries) FaultPrune(ctx context.Context, arg FaultPruneParams) (int64, error) {
	result, err := q.db.Exec(ctx, faultPrune, arg.CompanyID, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const faultRelease = `-- name: FaultRelease :execrows
delete from isolar_forwarded_alarms a
using power_plants p
where a.plant_id = p.id and a.plant_id = $1 and p.company_id = $2
  and a.alarm_ref = any($3::text[])
`

type FaultReleaseParams struct {
	PlantID   uuid.UUID
	CompanyID uuid.UUID
	Refs      []string
}

func (q *Queries) FaultRelease(ctx context.Context, arg FaultReleaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, faultRelease, arg.PlantID, arg.CompanyID, arg.Refs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const faultUnforwarded = `-- name: FaultUnforwarded :many
select f.plant_id, f.ref, f.code, f.name, f.level, f.type, f.device_name, f.occurred_at, f.closed_at, f.first_seen_at from plant_faults f
join power_plants p on p.id = f.plant_id
where f.plant_id = $1 and p.company_id = $2 and p.deleted_at is null
  and f.occurred_at >= $3
  and not exists (select 1 from isolar_forwarded_alarms a where a.plant_id = f.plant_id and a.alarm_ref = f.ref)
order by f.occurred_at, f.ref
`

type FaultUnforwardedParams struct {
	PlantID   uuid.UUID
	CompanyID uuid.UUID
	Since     pgtype.Timestamptz
}

func (q *Queries) FaultUnforwarded(ctx context.Context, arg FaultUnforwardedParams) ([]PlantFault, error) {
	rows, err := q.db.Query(ctx, faultUnforwarded, arg.PlantID, arg.CompanyID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlantFault
	for rows.Next() {
		var i PlantFault
		if err := rows.Scan(
			&i.PlantID,
			&i.Ref,
			&i.Code,
			&i.Name,
			&i.Level,
			&i.Type,
			&i.DeviceName,
			&i.OccurredAt,
			&i.ClosedAt,
			&i.FirstSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const faultUpsert = `-- name: FaultUpsert :execrows
insert into plant_faults (plant_id, ref, code, name, level, type, device_name, occurred_at, closed_at, first_seen_at)
select $1, $2, $3, $4, $5, $6,
       $7, $8, $9, $10
where exists (select 1 from power_plants p
              where p.id = $1 and p.company_id = $11 and p.deleted_at is null)
on conflict (plant_id, ref) do update set
    name = excluded.name, level = excluded.level, type = excluded.type,
    device_name = excluded.device_name, closed_at = excluded.closed_at
`

type FaultUpsertParams struct {
	PlantID     uuid.UUID
	Ref         string
	Code        string
	Name        string
	Level       *int32
	Type        *int32
	DeviceName  *string
	OccurredAt  pgtype.Timestamptz
	ClosedAt    pgtype.Timestamptz
	FirstSeenAt pgtype.Timestamptz
	CompanyID   uuid.UUID
}

func (q *Queries) FaultUpsert(ctx context.Context, arg FaultUpsertParams) (int64, error) {
	result, err := q.db.Exec(ctx, faultUpsert,
		arg.PlantID,
		arg.Ref,
		arg.Code,
		arg.Name,
		arg.Level,
		arg.Type,
		arg.DeviceName,
		arg.OccurredAt,
		arg.ClosedAt,
		arg.FirstSeenAt,
		arg.CompanyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const plantDeviceSnapshotUpdate = `-- name: PlantDeviceSnapshotUpdate :execrows
update power_plant_devices d
set snapshot_at = $1, fault_status = $2,
    active_power_kw = $3, yield_today_kwh = $4,
    yield_month_kwh = $5, yield_year_kwh = $6,
    yield_total_kwh = $7, status = $8,
    last_seen_at = coalesce($1, d.last_seen_at), updated_at = now()
from power_plants p
where d.plant_id = p.id and d.id = $9 and d.plant_id = $10
  and p.company_id = $11 and p.deleted_at is null
`

type PlantDeviceSnapshotUpdateParams struct {
	SnapshotAt    pgtype.Timestamptz
	FaultStatus   *int32
	ActivePowerKw pgtype.Numeric
	YieldTodayKwh pgtype.Numeric
	YieldMonthKwh pgtype.Numeric
	YieldYearKwh  pgtype.Numeric
	YieldTotalKwh pgtype.Numeric
	Status        *string
	ID            uuid.UUID
	PlantID       uuid.UUID
	CompanyID     uuid.UUID
}

func (q *Queries) PlantDeviceSnapshotUpdate(ctx context.Context, arg PlantDeviceSnapshotUpdateParams) (int64, error) {
	result, err := q.db.Exec(ctx, plantDeviceSnapshotUpdate,
		arg.SnapshotAt,
		arg.FaultStatus,
		arg.ActivePowerKw,
		arg.YieldTodayKwh,
		arg.YieldMonthKwh,
		arg.YieldYearKwh,
		arg.YieldTotalKwh,
		arg.Status,
		arg.ID,
		arg.PlantID,
		arg.CompanyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const plantListLinked = `-- name: PlantListLinked :many
select id, company_id, name, installation_number, plant_kind, pv_brand_model, panel_power_w, panel_efficiency_pct, panel_count, string_count, orientation, tilt_angle_deg, total_capacity_kw, yearly_target_kwh, installation_date, address, latitude, longitude, isolar_ps_id, isolar_ps_key, isolar_ps_name, isolar_installed_kw, isolar_linked_at, created_at, updated_at, deleted_at, isolar_credential_id, netting_analyzer_id, isolar_last_sync_at, isolar_last_sync_error from power_plants
where company_id = $1 and deleted_at is null and isolar_ps_id is not null
order by name
`

func (q *Queries) PlantListLinked(ctx context.Context, companyID uuid.UUID) ([]PowerPlant, error) {
	rows, err := q.db.Query(ctx, plantListLinked, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PowerPlant
	for rows.Next() {
		var i PowerPlant
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.InstallationNumber,
			&i.PlantKind,
			&i.PvBrandModel,
			&i.PanelPowerW,
			&i.PanelEfficiencyPct,
			&i.PanelCount,
			&i.StringCount,
			&i.Orientation,
			&i.TiltAngleDeg,
			&i.TotalCapacityKw,
			&i.YearlyTargetKwh,
			&i.InstallationDate,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.IsolarPsID,
			&i.IsolarPsKey,
			&i.IsolarPsName,
			&i.IsolarInstalledKw,
			&i.IsolarLinkedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsolarCredentialID,
			&i.NettingAnalyzerID,
			&i.IsolarLastSyncAt,
			&i.IsolarLastSyncError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const plantSetIsolarLink = `-- name: PlantSetIsolarLink :one
update power_plants
set isolar_ps_id = $1, isolar_ps_key = $2,
    isolar_ps_name = $3, isolar_installed_kw = $4,
    isolar_linked_at = $5, isolar_credential_id = $6,
    total_capacity_kw = $7, updated_at = now()
where id = $8 and company_id = $9 and deleted_at is null
returning id, company_id, name, installation_number, plant_kind, pv_brand_model, panel_power_w, panel_efficiency_pct, panel_count, string_count, orientation, tilt_angle_deg, total_capacity_kw, yearly_target_kwh, installation_date, address, latitude, longitude, isolar_ps_id, isolar_ps_key, isolar_ps_name, isolar_installed_kw, isolar_linked_at, created_at, updated_at, deleted_at, isolar_credential_id, netting_analyzer_id, isolar_last_sync_at, isolar_last_sync_error
`

type PlantSetIsolarLinkParams struct {
	IsolarPsID         *string
	IsolarPsKey        *string
	IsolarPsName       *string
	IsolarInstalledKw  pgtype.Numeric
	IsolarLinkedAt     pgtype.Timestamptz
	IsolarCredentialID *uuid.UUID
	TotalCapacityKw    pgtype.Numeric
	ID                 uuid.UUID
	CompanyID          uuid.UUID
}

func (q *Queries) PlantSetIsolarLink(ctx context.Context, arg PlantSetIsolarLinkParams) (PowerPlant, error) {
	row := q.db.QueryRow(ctx, plantSetIsolarLink,
		arg.IsolarPsID,
		arg.IsolarPsKey,
		arg.IsolarPsName,
		arg.IsolarInstalledKw,
		arg.IsolarLinkedAt,
		arg.IsolarCredentialID,
		arg.TotalCapacityKw,
		arg.ID,
		arg.CompanyID,
	)
	var i PowerPlant
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.InstallationNumber,
		&i.PlantKind,
		&i.PvBrandModel,
		&i.PanelPowerW,
		&i.PanelEfficiencyPct,
		&i.PanelCount,
		&i.StringCount,
		&i.Orientation,
		&i.TiltAngleDeg,
		&i.TotalCapacityKw,
		&i.YearlyTargetKwh,
		&i.InstallationDate,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.IsolarPsID,
		&i.IsolarPsKey,
		&i.IsolarPsName,
		&i.IsolarInstalledKw,
		&i.IsolarLinkedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsolarCredentialID,
		&i.NettingAnalyzerID,
		&i.IsolarLastSyncAt,
		&i.IsolarLastSyncError,
	)
	return i, err
}

const plantSetSyncState = `-- name: PlantSetSyncState :execrows
update power_plants
set isolar_last_sync_at = $1, isolar_last_sync_error = $2
where id = $3 and company_id = $4 and deleted_at is null
`

type PlantSetSyncStateParams struct {
	At        pgtype.Timestamptz
	ErrorCode *string
	ID        uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) PlantSetSyncState(ctx context.Context, arg PlantSetSyncStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, plantSetSyncState,
		arg.At,
		arg.ErrorCode,
		arg.ID,
		arg.CompanyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const solarPlantVisibleForShare = `-- name: SolarPlantVisibleForShare :one

select id from power_plants
where id = $1 and company_id = $2 and deleted_at is null
for share
`

type SolarPlantVisibleForShareParams struct {
	PlantID   uuid.UUID
	CompanyID uuid.UUID
}

// F9 solar queries. Every table here is plant-parented and company-scoped
// through power_plants in the same statement (PlantRepository's rule).
func (q *Queries) SolarPlantVisibleForShare(ctx context.Context, arg SolarPlantVisibleForShareParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, solarPlantVisibleForShare, arg.PlantID, arg.CompanyID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const totalsDeleteRange = `-- name: TotalsDeleteRange :execrows
delete from plant_production_totals t
using power_plants p
where t.plant_id = p.id and t.plant_id = $1
  and p.company_id = $2 and p.deleted_at is null
  and t.ts >= $3::timestamptz and t.ts < $4::timestamptz
`

type TotalsDeleteRangeParams struct {
	PlantID   uuid.UUID
	CompanyID uuid.UUID
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
}

func (q *Queries) TotalsDeleteRange(ctx context.Context, arg TotalsDeleteRangeParams) (int64, error) {
	result, err := q.db.Exec(ctx, totalsDeleteRange,
		arg.PlantID,
		arg.CompanyID,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const totalsFirstTs = `-- name: TotalsFirstTs :one
select min(t.ts)::timestamptz as first_ts
from plant_production_totals t
join power_plants p on p.id = t.plant_id
where t.plant_id = $1
  and p.company_id = $2 and p.deleted_at is null
`

type TotalsFirstTsParams struct {
	PlantID   uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) TotalsFirstTs(ctx context.Context, arg TotalsFirstTsParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, totalsFirstTs, arg.PlantID, arg.CompanyID)
	var first_ts pgtype.Timestamptz
	err := row.Scan(&first_ts)
	return first_ts, err
}

const totalsRange = `-- name: TotalsRange :many
select t.plant_id, t.ts, t.production_kwh, t.active_power_kw, t.basis
from plant_production_totals t
join power_plants p on p.id = t.plant_id
where t.plant_id = $1
  and p.company_id = $2 and p.deleted_at is null
  and t.ts >= $3::timestamptz and t.ts < $4::timestamptz
order by t.ts
`

type TotalsRangeParams struct {
	PlantID   uuid.UUID
	CompanyID uuid.UUID
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
}

type TotalsRangeRow struct {
	PlantID       uuid.UUID
	Ts            pgtype.Timestamptz
	ProductionKwh pgtype.Numeric
	ActivePowerKw pgtype.Numeric
	Basis         string
}

func (q *Queries) TotalsRange(ctx context.Context, arg TotalsRangeParams) ([]TotalsRangeRow, error) {
	rows, err := q.db.Query(ctx, totalsRange,
		arg.PlantID,
		arg.CompanyID,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TotalsRangeRow
	for rows.Next() {
		var i TotalsRangeRow
		if err := rows.Scan(
			&i.PlantID,
			&i.Ts,
			&i.ProductionKwh,
			&i.ActivePowerKw,
			&i.Basis,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
