// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const userCreate = `-- name: UserCreate :one
insert into users
    (id, company_id, name, email, phone, password_hash, role, is_active, created_at, updated_at)
values ($1, $2, $3, $4, $5,
        $6, $7, $8, coalesce($9::timestamptz, now()), coalesce($9::timestamptz, now()))
returning id, company_id, name, email, phone, password_hash, password_changed_at, role, is_active, last_login_at, created_at, updated_at, deleted_at
`

type UserCreateParams struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	Name         string
	Email        string
	Phone        *string
	PasswordHash string
	Role         UserRole
	IsActive     bool
	At           pgtype.Timestamptz
}

// coalesce(sqlc.narg(at)::timestamptz, now()): a caller that leaves CreatedAt at its zero
// value gets the database's own now() rather than writing 0001-01-01.
func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (User, error) {
	row := q.db.QueryRow(ctx, userCreate,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Role,
		arg.IsActive,
		arg.At,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const userGet = `-- name: UserGet :one

select id, company_id, name, email, phone, password_hash, password_changed_at, role, is_active, last_login_at, created_at, updated_at, deleted_at from users
where id = $1 and company_id = $2 and deleted_at is null
`

type UserGetParams struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
}

// UserRepository queries.
func (q *Queries) UserGet(ctx context.Context, arg UserGetParams) (User, error) {
	row := q.db.QueryRow(ctx, userGet, arg.ID, arg.CompanyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const userGetPasswordHashForUpdate = `-- name: UserGetPasswordHashForUpdate :one
select password_hash from users
where id = $1 and company_id = $2 and deleted_at is null
for update
`

type UserGetPasswordHashForUpdateParams struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
}

// Locks the row so a concurrent password change cannot race the history
// insert that SetPassword pairs this with.
func (q *Queries) UserGetPasswordHashForUpdate(ctx context.Context, arg UserGetPasswordHashForUpdateParams) (string, error) {
	row := q.db.QueryRow(ctx, userGetPasswordHashForUpdate, arg.ID, arg.CompanyID)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const userList = `-- name: UserList :many
select id, company_id, name, email, phone, password_hash, password_changed_at, role, is_active, last_login_at, created_at, updated_at, deleted_at from users
where company_id = $1
  and ($2::boolean or deleted_at is null)
  -- pgx has no static codec for a custom enum's array OID without a
  -- per-connection type registration this package does not do, and an empty
  -- slice still needs an encode plan before cardinality() can tell it is
  -- empty — so the PARAMETER is bound as text[] (a plain []string) and cast
  -- to user_role[] only inside SQL, once bound. The COLUMN itself is left
  -- uncast, so an index on role (should one ever be added) stays usable; an
  -- array element that is not a valid user_role raises a loud Postgres
  -- error rather than silently matching nothing.
  and (cardinality($3::text[]) = 0 or role = any($3::text[]::user_role[]))
  and ($4::boolean is null or is_active = $4)
  and ($5::text = '' or email ilike '%' || $5::text || '%')
order by name
limit $7 offset $6
`

type UserListParams struct {
	CompanyID      uuid.UUID
	IncludeDeleted bool
	Roles          []string
	IsActive       *bool
	EmailContains  string
	PageOffset     int32
	PageLimit      int32
}

func (q *Queries) UserList(ctx context.Context, arg UserListParams) ([]User, error) {
	rows, err := q.db.Query(ctx, userList,
		arg.CompanyID,
		arg.IncludeDeleted,
		arg.Roles,
		arg.IsActive,
		arg.EmailContains,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.PasswordHash,
			&i.PasswordChangedAt,
			&i.Role,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userPasswordHistoryInsert = `-- name: UserPasswordHistoryInsert :exec
insert into user_password_history (id, user_id, password_hash, created_at)
values ($1, $2, $3, $4)
`

type UserPasswordHistoryInsertParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	PasswordHash string
	At           pgtype.Timestamptz
}

func (q *Queries) UserPasswordHistoryInsert(ctx context.Context, arg UserPasswordHistoryInsertParams) error {
	_, err := q.db.Exec(ctx, userPasswordHistoryInsert,
		arg.ID,
		arg.UserID,
		arg.PasswordHash,
		arg.At,
	)
	return err
}

const userPasswordHistoryList = `-- name: UserPasswordHistoryList :many
select h.id, h.user_id, h.password_hash, h.created_at
from user_password_history h
join users u on u.id = h.user_id
where h.user_id = $1 and u.company_id = $2 and u.deleted_at is null
order by h.created_at desc
limit $3
`

type UserPasswordHistoryListParams struct {
	UserID    uuid.UUID
	CompanyID uuid.UUID
	RowLimit  int32
}

// Isolation: user_password_history has no company_id — join through users.
// u.deleted_at is null matters here specifically: without it, a soft-deleted
// user's password history stays reachable through this join forever.
func (q *Queries) UserPasswordHistoryList(ctx context.Context, arg UserPasswordHistoryListParams) ([]UserPasswordHistory, error) {
	rows, err := q.db.Query(ctx, userPasswordHistoryList, arg.UserID, arg.CompanyID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPasswordHistory
	for rows.Next() {
		var i UserPasswordHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PasswordHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userRecordLogin = `-- name: UserRecordLogin :execrows
update users
set last_login_at = $1
where id = $2 and company_id = $3 and deleted_at is null
`

type UserRecordLoginParams struct {
	At        pgtype.Timestamptz
	ID        uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) UserRecordLogin(ctx context.Context, arg UserRecordLoginParams) (int64, error) {
	result, err := q.db.Exec(ctx, userRecordLogin, arg.At, arg.ID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userSetPasswordHash = `-- name: UserSetPasswordHash :exec
update users
set password_hash = $1,
    password_changed_at = $2,
    updated_at = $2
where id = $3 and company_id = $4 and deleted_at is null
`

type UserSetPasswordHashParams struct {
	PasswordHash string
	At           pgtype.Timestamptz
	ID           uuid.UUID
	CompanyID    uuid.UUID
}

func (q *Queries) UserSetPasswordHash(ctx context.Context, arg UserSetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, userSetPasswordHash,
		arg.PasswordHash,
		arg.At,
		arg.ID,
		arg.CompanyID,
	)
	return err
}

const userSoftDelete = `-- name: UserSoftDelete :execrows
update users
set deleted_at = $1
where id = $2 and company_id = $3 and deleted_at is null
`

type UserSoftDeleteParams struct {
	DeletedAt pgtype.Timestamptz
	ID        uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) UserSoftDelete(ctx context.Context, arg UserSoftDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, userSoftDelete, arg.DeletedAt, arg.ID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userUpdate = `-- name: UserUpdate :one
update users
set name = $1,
    email = $2,
    phone = $3,
    role = $4,
    is_active = $5,
    updated_at = $6
where id = $7 and company_id = $8 and deleted_at is null
returning id, company_id, name, email, phone, password_hash, password_changed_at, role, is_active, last_login_at, created_at, updated_at, deleted_at
`

type UserUpdateParams struct {
	Name      string
	Email     string
	Phone     *string
	Role      UserRole
	IsActive  bool
	UpdatedAt pgtype.Timestamptz
	ID        uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) UserUpdate(ctx context.Context, arg UserUpdateParams) (User, error) {
	row := q.db.QueryRow(ctx, userUpdate,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Role,
		arg.IsActive,
		arg.UpdatedAt,
		arg.ID,
		arg.CompanyID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const userVisible = `-- name: UserVisible :one
select exists(
    select 1 from users
    where id = $1 and company_id = $2 and deleted_at is null
)
`

type UserVisibleParams struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
}

// The User-prefixed parent-visibility lookup UserRepository.PasswordHistory
// uses. Session-prefixed SessionUserVisible (queries/sessions.sql) exists
// for SessionRepository's own use and is a different query in the same
// shape — ruling 5 in wave-f-context.md is that a parent-visibility lookup
// lives under its OWN repository's prefix, not borrowed across one.
func (q *Queries) UserVisible(ctx context.Context, arg UserVisibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, userVisible, arg.ID, arg.CompanyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
