package iso50001

// catalogue is legacy isoModule.accordionItem.accordion, verbatim in both
// locales (R330). Generated once from src/app/i18n/locales/{tr,en}.json.
//
//nolint:misspell // Turkish clause text ("performans", "Adres"…), not English typos
var catalogue = []Main{
	{ID: "5", Title: map[string]string{"tr": "5. Liderlik", "en": "5. Leadership"}, Subs: []Sub{
		{ID: "5.1", Template: "",
			Title:       map[string]string{"tr": "5.1 Liderlik ve Taahhüt", "en": "5.1 Leadership and Commitment"},
			Description: map[string]string{"tr": "Üst yönetim, EnYS'nin etkililiği ve sürekli iyileştirilmesi için liderlik ve bağlılık göstermelidir. Bu, EnYS'nin kuruluşun iş süreçlerine entegrasyonunu sağlamayı, enerji politikasını ve hedeflerini oluşturmayı ve gerekli kaynakların mevcut olmasını sağlamayı içerir.", "en": "Top management must demonstrate leadership and commitment to the effectiveness and continual improvement of the EnMS. This includes ensuring the integration of the EnMS into the organization's business processes, establishing the energy policy and objectives, and ensuring the availability of necessary resources."}},
		{ID: "5.2", Template: "",
			Title:       map[string]string{"tr": "5.2 Enerji Politikası", "en": "5.2 Energy Policy"},
			Description: map[string]string{"tr": "Üst yönetim, kuruluşun amacına uygun, hedeflerin oluşturulması için bir çerçeve sunan ve sürekli iyileştirme taahhüdü içeren bir enerji politikası oluşturmalı, uygulamalı ve sürdürmelidir.", "en": "Top management must establish, implement, and maintain an energy policy that is appropriate to the purpose of the organization, provides a framework for setting objectives, and includes a commitment to continual improvement."}},
		{ID: "5.3", Template: "",
			Title:       map[string]string{"tr": "5.3 Kurumsal Görev, Sorumluluk ve Yetkiler", "en": "5.3 Organizational Roles, Responsibilities and Authorities"},
			Description: map[string]string{"tr": "Üst yönetim, EnYS ile ilgili görevler için yetki ve sorumlulukların belirlenmesini ve kuruluş içinde duyurulmasını sağlamalıdır. Enerji yönetimi ekibine özel sorumluluklar atanmalıdır.", "en": "Top management must ensure that responsibilities and authorities for relevant roles are assigned and communicated within the organization. Specific responsibilities should be assigned to the energy management team."}},
	}},
	{ID: "6", Title: map[string]string{"tr": "6. Planlama", "en": "6. Planning"}, Subs: []Sub{
		{ID: "6.1", Template: "",
			Title:       map[string]string{"tr": "6.1 Riskleri ve Fırsatları Belirleme", "en": "6.1 Actions to Address Risks and Opportunities"},
			Description: map[string]string{"tr": "Kuruluş, EnYS planlamasında, istenen sonuçları güvence altına almak, istenmeyen etkileri önlemek ve sürekli iyileşmeyi sağlamak için ilgili risk ve fırsatları belirlemeli ve ele almalıdır.", "en": "When planning for the EnMS, the organization shall consider and address the relevant risks and opportunities to assure intended outcomes, prevent undesired effects, and achieve continual improvement."}},
		{ID: "6.2", Template: "",
			Title:       map[string]string{"tr": "6.2 Amaçlar, Enerji Hedefleri ve Planlama", "en": "6.2 Objectives, Energy Targets and Planning"},
			Description: map[string]string{"tr": "Kuruluş, ilgili fonksiyon ve seviyelerde ölçülebilir enerji hedefleri belirlemeli ve bunlara ulaşmak için faaliyet planları oluşturmalı ve sürdürmelidir.", "en": "The organization shall establish and maintain measurable energy objectives at relevant functions and levels, and create action plans to achieve them."}},
		{ID: "6.3", Template: "significant-energy-uses",
			Title:       map[string]string{"tr": "6.3 Enerji Gözden Geçirmesi", "en": "6.3 Energy Review"},
			Description: map[string]string{"tr": "Kuruluş, enerji kullanımı ve tüketimini analiz ederek, önemli enerji kullanımlarını (ÖEK) ve enerji performansını iyileştirme fırsatlarını belirlemek için bir enerji gözden geçirmesi süreci geliştirmeli ve uygulamalıdır.", "en": "The organization shall develop and implement an energy review process to analyze energy use and consumption, identifying significant energy uses (SEUs) and opportunities for improving energy performance."}},
		{ID: "6.4", Template: "energy-consumption-analysis",
			Title:       map[string]string{"tr": "6.4 Enerji Performansı Göstergeleri (EnPG)", "en": "6.4 Energy Performance Indicators (EnPIs)"},
			Description: map[string]string{"tr": "Kuruluş, enerji performansındaki gelişimi göstermek için uygun enerji performansı göstergelerini (EnPG) belirlemeli ve kullanmalıdır.", "en": "The organization shall identify and use appropriate energy performance indicators (EnPIs) to demonstrate improvements in energy performance."}},
		{ID: "6.5", Template: "energy-consumption-analysis",
			Title:       map[string]string{"tr": "6.5 Enerji Referans Çizgisi (EnRÇ)", "en": "6.5 Energy Baseline (EnB)"},
			Description: map[string]string{"tr": "Kuruluş, enerji performansını karşılaştırmak amacıyla, uygun bir zaman dilimindeki verilere dayanarak bir veya daha fazla enerji referans çizgisi (EnRÇ) oluşturmalıdır.", "en": "The organization shall establish one or more energy baselines (EnBs) based on data from a suitable time period to compare energy performance."}},
		{ID: "6.6", Template: "",
			Title:       map[string]string{"tr": "6.6 Enerji Verilerinin Toplanması Planlaması", "en": "6.6 Planning for Collection of Energy Data"},
			Description: map[string]string{"tr": "Kuruluş, ÖEK'leri ve enerji performansını etkileyen diğer önemli unsurları izlemek ve analiz etmek için gerekli verileri toplayan bir veri toplama planı tanımlamalı ve uygulamalıdır.", "en": "The organization shall define and implement a data collection plan to collect the necessary data for monitoring SEUs and other key elements affecting energy performance."}},
	}},
	{ID: "7", Title: map[string]string{"tr": "7. Destek", "en": "7. Support"}, Subs: []Sub{
		{ID: "7.1", Template: "",
			Title:       map[string]string{"tr": "7.1 Kaynaklar", "en": "7.1 Resources"},
			Description: map[string]string{"tr": "Kuruluş, EnYS'nin kurulması, uygulanması, sürdürülmesi ve sürekli iyileştirilmesi için gerekli olan kaynakları belirlemeli ve sağlamalıdır.", "en": "The organization shall determine and provide the resources needed for the establishment, implementation, maintenance, and continual improvement of the EnMS."}},
		{ID: "7.2", Template: "",
			Title:       map[string]string{"tr": "7.2 Yetkinlik", "en": "7.2 Competence"},
			Description: map[string]string{"tr": "Kuruluş, enerji performansını etkileyen personelin uygun eğitim, öğretim, beceri veya tecrübeye dayalı olarak yetkin olmasını sağlamalıdır.", "en": "The organization shall ensure that personnel affecting energy performance are competent on the basis of appropriate education, training, skills, or experience."}},
		{ID: "7.3", Template: "",
			Title:       map[string]string{"tr": "7.3 Farkındalık", "en": "7.3 Awareness"},
			Description: map[string]string{"tr": "Kuruluş kontrolü altındaki kişiler enerji politikası, EnYS'ye katkıları ve gerekliliklere uymamanın sonuçları hakkında farkındalığa sahip olmalıdır.", "en": "Persons under the organization's control shall be aware of the energy policy, their contribution to the EnMS, and the implications of not conforming with its requirements."}},
		{ID: "7.4", Template: "",
			Title:       map[string]string{"tr": "7.4 İletişim", "en": "7.4 Communication"},
			Description: map[string]string{"tr": "Kuruluş, EnYS ile ilgili iç ve dış iletişim proseslerini belirlemelidir; neyin, ne zaman, kiminle, nasıl ve kimin ileteceğini planlamalıdır.", "en": "The organization shall determine the internal and external communications relevant to the EnMS, including what, when, with whom, how, and who communicates."}},
		{ID: "7.5", Template: "regression-analysis-instruction",
			Title:       map[string]string{"tr": "7.5 Dokümante Edilmiş Bilgi", "en": "7.5 Documented Information"},
			Description: map[string]string{"tr": "Kuruluşun EnYS'si, bu standardın gerektirdiği ve kuruluşun EnYS'nin etkinliği için gerekli gördüğü dokümante edilmiş bilgileri içermeli, oluşturmalı ve kontrol etmelidir.", "en": "The organization's EnMS shall include, create, and control documented information required by this standard and deemed necessary by the organization for the effectiveness of the EnMS."}},
	}},
	{ID: "8", Title: map[string]string{"tr": "8. Operasyon", "en": "8. Operation"}, Subs: []Sub{
		{ID: "8.1", Template: "",
			Title:       map[string]string{"tr": "8.1 Operasyonel Planlama ve Kontrol", "en": "8.1 Operational Planning and Control"},
			Description: map[string]string{"tr": "Kuruluş, önemli enerji kullanımları (ÖEK) ile ilgili prosesleri, belirlenen kriterlere göre uygulayarak ve kontrol ederek planlamalıdır. Değişiklikler planlanmalı ve sonuçları gözden geçirilmelidir.", "en": "The organization shall plan, implement, and control the processes related to significant energy uses (SEUs) according to established criteria. Changes must be planned, and their consequences reviewed."}},
		{ID: "8.2", Template: "",
			Title:       map[string]string{"tr": "8.2 Tasarım", "en": "8.2 Design"},
			Description: map[string]string{"tr": "Kuruluş, enerji performansı üzerinde önemli etkiye sahip olabilecek yeni, değiştirilmiş ve yenilenmiş tesislerin, ekipmanların, sistemlerin ve proseslerin tasarımında performans artırma fırsatlarını ve çalışma kontrollerini dikkate almalıdır.", "en": "The organization shall consider performance improvement opportunities and operational controls in the design of new, modified, and renovated facilities, equipment, systems, and processes that can have a significant impact on energy performance."}},
		{ID: "8.3", Template: "",
			Title:       map[string]string{"tr": "8.3 Tedarik", "en": "8.3 Procurement"},
			Description: map[string]string{"tr": "Kuruluş, enerji performansı üzerinde önemli etkisi olması beklenen enerji kullanan ürünleri, donanımı ve hizmetleri satın alırken enerji performansını değerlendirmek için kriterler oluşturmalı ve uygulamalıdır.", "en": "The organization shall establish and implement criteria for evaluating energy performance when procuring energy-using products, equipment, and services that are expected to have a significant impact on energy performance."}},
	}},
	{ID: "9", Title: map[string]string{"tr": "9. Performans Değerlendirmesi", "en": "9. Performance Evaluation"}, Subs: []Sub{
		{ID: "9.1", Template: "energy-consumption-analysis",
			Title:       map[string]string{"tr": "9.1 İzleme, Ölçüm, Analiz ve Değerlendirme", "en": "9.1 Monitoring, Measurement, Analysis and Evaluation"},
			Description: map[string]string{"tr": "Kuruluş, enerji performansını ve EnYS'nin etkinliğini planlı aralıklarla izlemeli, ölçmeli, analiz etmeli ve değerlendirmelidir. Önemli sapmaları araştırmalı ve bunlara karşı harekete geçmelidir.", "en": "The organization shall monitor, measure, analyze, and evaluate its energy performance and the effectiveness of the EnMS at planned intervals. It must investigate and act on significant deviations."}},
		{ID: "9.2", Template: "",
			Title:       map[string]string{"tr": "9.2 İç Tetkik", "en": "9.2 Internal Audit"},
			Description: map[string]string{"tr": "Kuruluş, EnYS'nin standart gerekliliklerine ve kendi belirlediği şartlara uyup uymadığını ve etkin bir şekilde uygulanıp sürdürüldüğünü belirlemek için planlı aralıklarla iç tetkikler yapmalıdır.", "en": "The organization shall conduct internal audits at planned intervals to determine whether the EnMS conforms to standard requirements and its own established criteria, and is effectively implemented and maintained."}},
		{ID: "9.3", Template: "",
			Title:       map[string]string{"tr": "9.3 Yönetimin Gözden Geçirmesi", "en": "9.3 Management Review"},
			Description: map[string]string{"tr": "Üst yönetim, EnYS'nin uygunluğunu, yeterliliğini ve etkinliğini sürekli kılmak için planlı aralıklarla gözden geçirmelidir. Gözden geçirme girdileri enerji performansı verilerini içermelidir.", "en": "Top management shall review the EnMS at planned intervals to ensure its continuing suitability, adequacy, and effectiveness. The review inputs must include energy performance data."}},
	}},
}
